In [ ]:
!pip install -q google-genai tqdm pandas rapidfuzz

# config

In [ ]:
import re
import os
import json
import time
import uuid
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
from tqdm import tqdm
from rapidfuzz import fuzz

from google import genai
from google.genai import types
from google.colab import userdata, files


logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")


# input file
BOOK_PATH = Path("/content/full_DVSK_data.json")

CHUNK_FILES = {
    "chunk_256": Path("/content/full_DVSK_data_bkai_256.json"),
    "chunk_512": Path("/content/full_DVSK_data_aiteamvn_512.json"),
    "chunk_1024": Path("/content/full_DVSK_data_aiteamvn_1024.json"),
}


# output file
OUTPUT_JSONL = Path("/content/dvsk_embedding_benchmark_qrels.jsonl")
OUTPUT_JSON = Path("/content/dvsk_embedding_benchmark_qrels.json")
OUTPUT_CSV = Path("/content/dvsk_embedding_benchmark_qrels.csv")
FAILED_JSON = Path("/content/failed_claim_windows.json")



GEMINI_MODEL = "gemini-3.1-flash-lite"
TARGET_CLAIMS = 300

PAGES_PER_WINDOW = 2
MAX_CLAIMS_PER_WINDOW = 4
SLEEP_SECONDS = 3


# match config
MIN_EXACT_LEN = 30
FUZZY_THRESHOLD = 78
TOP_MATCHES_PER_CHUNK_SIZE = 3

## sách

In [ ]:
def load_json(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


book_data = load_json(BOOK_PATH)

book_name = book_data["book_name"]
full_text = book_data["full_text"]
page_footnotes_map = book_data.get("page_footnotes_map", {})

chunk_data = {
    key: load_json(path)
    for key, path in CHUNK_FILES.items()
}


print("Book:", book_name)
print("Chunk files:")
for key, rows in chunk_data.items():
    print(key, len(rows))
# print(len(chunk_data))

# tách nội dung sách ra thành page text
def split_pages(full_text: str) -> List[Dict[str, Any]]:
    pattern = r"\n\s*\[\[\[PAGE:(\d+)\]\]\]\s*\n"
    matches = list(re.finditer(pattern, full_text))

    pages = []

    for i, match in enumerate(matches):
        page_num = int(match.group(1))
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(full_text)

        text = full_text[start:end].strip()

        if text:
            pages.append({
                "page": page_num,
                "text": text,
            })

    return pages


pages = split_pages(full_text)

print("Total pages:", len(pages))
print(pages[0]["page"])
print(pages[0]["text"][:500])


def normalize_text(text: str) -> str:
    text = re.sub(r"\s+", " ", text)
    text = text.replace(" ,", ",").replace(" .", ".")
    return text.strip()


def remove_page_marker(text: str) -> str:
    return re.sub(r"\n\s*\[\[\[PAGE:(\d+)\]\]\]\s*\n", " ", text)


def clean_for_match(text: str) -> str:
    text = remove_page_marker(text)
    text = text.lower()
    text = re.sub(r"\[\d+\]", " ", text)
    text = re.sub(r"[^0-9a-zA-ZÀ-ỹ\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def short_text(text: str, max_len: int = 500) -> str:
    text = normalize_text(text)
    return text[:max_len] + "..." if len(text) > max_len else text



def make_page_windows(
    pages: List[Dict[str, Any]],
    pages_per_window: int = 2,
) -> List[Dict[str, Any]]:

    windows = []

    for i in range(0, len(pages), pages_per_window):
        group = pages[i:i + pages_per_window]

        if not group:
            continue

        text = "\n\n".join(
            f"[[[PAGE:{p['page']}]]]\n{p['text']}"
            for p in group
        )

        page_nums = [p["page"] for p in group]

        windows.append({
            "window_id": f"window_{len(windows) + 1:05d}",
            "book_name": book_name,
            "pages": page_nums,
            "text": text,
            "footnotes": {
                str(p): page_footnotes_map.get(str(p), {})
                for p in page_nums
            }
        })

    return windows


windows = make_page_windows(pages, PAGES_PER_WINDOW)

print("Total windows:", len(windows))
print(windows[0]["window_id"], windows[0]["pages"])
print(windows[0]["text"][:1000])

Book: Đại Việt Sử Ký Toàn Thư
Chunk files:
chunk_256 1003
chunk_512 682
chunk_1024 460
Total pages: 154
154
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đ
Total windows: 77
window_00001 [154, 155]
[[[PAGE:154]]]
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định n

## prompt

``` Input: Một "window" (nội dung của 2 trang sách).

Prompt: Đóng gói nội dung vào prompt cùng với yêu cầu tạo "claim".

Interaction: Gửi prompt tới Gemini, nếu lỗi thì tự động retry.

Parse: Lấy JSON từ phản hồi của Gemini.

Clean: Xử lý dữ liệu thô, gán ID, gắn nhãn metadata.

Output: Một danh sách các "cặp" (Claim - Dẫn chứng) hoàn chỉnh, sẵn sàng làm bài kiểm tra cho hệ thống tìm kiếm thông tin. ```

In [ ]:
def build_claim_prompt(window: Dict[str, Any]) -> str:
    return f"""
Bạn là chuyên gia xây dựng benchmark truy xuất thông tin cho hệ thống RAG lịch sử Việt Nam.

Dữ liệu bên dưới là một đoạn trích từ sách {window["book_name"]}.
Nhiệm vụ của bạn là tạo các claim lịch sử để đánh giá semantic retrieval.

Yêu cầu:
- Chỉ sử dụng thông tin có trong đoạn trích.
- Không dùng kiến thức bên ngoài.
- Không copy nguyên văn toàn bộ câu dài từ đoạn trích.
- Claim phải ngắn, rõ, độc lập và có thể kiểm chứng.
- Claim phải có chủ ngữ rõ ràng.
- Claim nên liên quan đến nhân vật, sự kiện, thời gian, chức vụ, quan hệ hoặc kết quả lịch sử.
- Mỗi claim phải có source_excerpt.
- source_excerpt là đoạn ngắn nằm nguyên trong dữ liệu gốc, dùng làm căn cứ tạo claim.
- source_excerpt nên dài từ 20 đến 120 từ.
- source_excerpt không được tự viết lại.
- Tạo tối đa {MAX_CLAIMS_PER_WINDOW} claim.
- Không tạo claim nếu đoạn trích quá mơ hồ.
- Trả về JSON hợp lệ, không giải thích ngoài JSON.

Schema:
{{
  "claims": [
    {{
      "claim": "...",
      "source_excerpt": "...",
      "source_pages": [154],
      "difficulty": "easy|medium|hard",
      "explanation": "..."
    }}
  ]
}}

Dữ liệu:
{json.dumps(window, ensure_ascii=False, indent=2)}
""".strip()

In [ ]:
def extract_json(text: str) -> Dict[str, Any]:
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, flags=re.DOTALL)
        if not match:
            raise ValueError("Gemini response không có JSON hợp lệ.")
        return json.loads(match.group(0))


def call_gemini(client: genai.Client, prompt: str) -> Dict[str, Any]:
    max_retries = 6
    base_sleep = 10

    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.2,
                    response_mime_type="application/json",
                ),
            )

            if not response.text:
                raise ValueError("Gemini trả về rỗng.")

            return extract_json(response.text)

        except Exception as e:
            error_text = str(e)

            is_retryable = (
                "503" in error_text
                or "UNAVAILABLE" in error_text
                or "429" in error_text
                or "RESOURCE_EXHAUSTED" in error_text
                or "timeout" in error_text.lower()
            )

            if not is_retryable or attempt == max_retries - 1:
                raise e

            wait_time = base_sleep * (2 ** attempt)
            logging.warning(
                f"Gemini lỗi tạm thời. Retry {attempt + 1}/{max_retries} sau {wait_time}s"
            )
            time.sleep(wait_time)

    raise RuntimeError("Gemini failed after retries.")

In [ ]:
def build_claim_samples(
    gemini_output: Dict[str, Any],
    window: Dict[str, Any],
    start_index: int,
) -> List[Dict[str, Any]]:

    claims = gemini_output.get("claims", [])
    samples = []

    for obj in claims:
        claim = str(obj.get("claim", "")).strip()
        source_excerpt = str(obj.get("source_excerpt", "")).strip()
        difficulty = str(obj.get("difficulty", "medium")).strip().lower()
        explanation = str(obj.get("explanation", "")).strip()

        if not claim or not source_excerpt:
            continue

        if difficulty not in {"easy", "medium", "hard"}:
            difficulty = "medium"

        source_pages = obj.get("source_pages", window["pages"])

        if not isinstance(source_pages, list):
            source_pages = window["pages"]

        claim_id = f"claim_{start_index + len(samples):06d}"

        samples.append({
            "claim_id": claim_id,
            "claim": claim,
            "source_excerpt": source_excerpt,
            "source_pages": source_pages,
            "book_name": window["book_name"],
            "source_window_id": window["window_id"],
            "difficulty": difficulty,
            "explanation": explanation,
            "metadata": {
                "created_by": "gemini",
                "needs_human_review": True,
                "dataset_type": "multi_chunk_retrieval_benchmark"
            }
        })

    return samples

## sinh dataset

In [ ]:
api_key = userdata.get("GEMINI_API_KEY")

if not api_key:
    raise RuntimeError("Không lấy được GEMINI_API_KEY từ Colab Secrets.")

client = genai.Client(api_key=api_key)

claim_samples = []
failed_windows = []

for window in tqdm(windows, desc="Generating claims"):
    if len(claim_samples) >= TARGET_CLAIMS:
        break

    try:
        prompt = build_claim_prompt(window)
        output = call_gemini(client, prompt)

        samples = build_claim_samples(
            gemini_output=output,
            window=window,
            start_index=len(claim_samples) + 1,
        )

        claim_samples.extend(samples)

        # Lưu tạm sau mỗi window
        with Path("/content/temp_claims.jsonl").open("w", encoding="utf-8") as f:
            for row in claim_samples:
                f.write(json.dumps(row, ensure_ascii=False) + "\n")

    except Exception as e:
        failed_windows.append({
            "window_id": window["window_id"],
            "pages": window["pages"],
            "error": str(e),
        })
        logging.warning(f"Lỗi ở {window['window_id']}: {e}")

    time.sleep(SLEEP_SECONDS)


with FAILED_JSON.open("w", encoding="utf-8") as f:
    json.dump(failed_windows, f, ensure_ascii=False, indent=2)

print("Generated claims:", len(claim_samples))
print("Failed windows:", len(failed_windows))

Generating claims:  78%|███████▊  | 60/77 [08:27<01:57,  6.93s/it]WARNING:root:Gemini lỗi tạm thời. Retry 1/6 sau 10s
Generating claims:  97%|█████████▋| 75/77 [10:59<00:17,  8.79s/it]

Generated claims: 300
Failed windows: 0

## map

In [ ]:
# chec xem source_excerpt do gemini trả về và raw_text tìm được có cùng trang không
def page_overlap_score(source_pages: List[int], chunk_pages: List[int]) -> int:
    source_set = set(int(p) for p in source_pages if str(p).isdigit())
    chunk_set = set(int(p) for p in chunk_pages if str(p).isdigit())

    return len(source_set.intersection(chunk_set))


def exact_contains_match(
    source_excerpt: str,
    chunk_text: str,
) -> bool:
    source_clean = clean_for_match(source_excerpt)
    chunk_clean = clean_for_match(chunk_text)

    if len(source_clean) < MIN_EXACT_LEN:
        return False

    return source_clean in chunk_clean


def fuzzy_match_score(
    source_excerpt: str,
    chunk_text: str,
) -> float:
    source_clean = clean_for_match(source_excerpt)
    chunk_clean = clean_for_match(chunk_text)

    if not source_clean or not chunk_clean:
        return 0.0

    return fuzz.partial_ratio(source_clean, chunk_clean)


# gọi các hàm match để xem source_excerpt có trùng raw_text nào  trong các file chunking không
def find_matching_chunks(
    source_excerpt: str,
    source_pages: List[int],
    chunks: List[Dict[str, Any]],
    top_n: int = 3,
) -> List[Dict[str, Any]]:

    candidates = []
    tmp = 0;
    for chunk in chunks:
        chunk_text = chunk.get("raw_text", "")
        chunk_pages = chunk.get("pages", [])

        page_score = page_overlap_score(source_pages, chunk_pages)

        # Ưu tiên chunk cùng trang, nhưng không loại hoàn toàn chunk khác trang
        exact_match = exact_contains_match(source_excerpt, chunk_text)
        fuzzy_score = fuzzy_match_score(source_excerpt, chunk_text)

# hàm xem có trùng không (không cần trùng chính xác )
        final_score = fuzzy_score + (page_score * 10)
        tmp+=1


# trùng chính xác với nhau
        if exact_match:
            final_score += 30
# điểm số trùng lớn thì lấy
        if exact_match or final_score >= FUZZY_THRESHOLD:
            candidates.append({
                "chunk_id": chunk.get("chunk_id"),
                "pages": chunk_pages,
                "raw_text": chunk_text,
                "token_count": chunk.get("token_count", 0),
                "match_score": round(final_score, 4),
                "fuzzy_score": round(fuzzy_score, 4),
                "page_overlap": page_score,
                "exact_match": exact_match,
            })
        if tmp < 10:
            print(chunk["book_name"])
            print(chunk_pages)
            print(source_excerpt)
            print(chunk_text)
            print(f"final_score: {final_score} \n\n")

    candidates = sorted(
        candidates,
        key=lambda x: (
            x["exact_match"],
            x["page_overlap"],
            x["match_score"]
        ),
        reverse=True
    )

    return candidates[:top_n]

In [ ]:
def attach_qrels_to_claims(
    claim_samples: List[Dict[str, Any]],
    chunk_data: Dict[str, List[Dict[str, Any]]],
) -> List[Dict[str, Any]]:

    final_dataset = []

    for sample in tqdm(claim_samples, desc="Mapping source_excerpt to chunks"):
        qrels = {}

        for chunk_key, chunks in chunk_data.items():
            matches = find_matching_chunks(
                source_excerpt=sample["source_excerpt"],
                source_pages=sample["source_pages"],
                chunks=chunks,
                top_n=TOP_MATCHES_PER_CHUNK_SIZE,
            )

            qrels[chunk_key] = [
                {
                    "chunk_id": m["chunk_id"],
                    "pages": m["pages"],
                    "match_score": m["match_score"],
                    "fuzzy_score": m["fuzzy_score"],
                    "page_overlap": m["page_overlap"],
                    "exact_match": m["exact_match"],
                    "token_count": m["token_count"],
                    "text_preview": short_text(m["raw_text"], 350),
                }
                for m in matches
                if m.get("chunk_id")
            ]

        row = dict(sample)
        row["qrels"] = qrels

        row["qrels_status"] = {
            key: len(value)
            for key, value in qrels.items()
        }

        row["is_usable_for_all_chunk_sizes"] = all(
            len(qrels.get(key, [])) > 0
            for key in chunk_data.keys()
        )

        final_dataset.append(row)

    return final_dataset


final_dataset = attach_qrels_to_claims(claim_samples, chunk_data)

usable_all = [x for x in final_dataset if x["is_usable_for_all_chunk_sizes"]]

print("Total claims:", len(final_dataset))
print("Usable for all chunk sizes:", len(usable_all))
print("Example:")
print(json.dumps(final_dataset[0], ensure_ascii=False, indent=2)[:3000])

Mapping source_excerpt to chunks:   0%|          | 0/300 [00:00<?, ?it/s]

Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 83.0310262529833


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 83.27935222672065


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.56795131845842


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.42992874109264


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.10526315789473


Đại Việt Sử Ký Toàn Thư
[155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.0251572327044


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 77.20647773279353


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 83.27935222672065


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.56795131845842


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.42992874109264


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.10526315789473


Đại Việt Sử Ký Toàn Thư
[155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.51012145748988


Đại Việt Sử Ký Toàn Thư
[155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.534412955465584


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 83.27935222672065


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.91497975708503


Đại Việt Sử Ký Toàn Thư
[154]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.51012145748988


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.51012145748988


Đại Việt Sử Ký Toàn Thư
[155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.534412955465584


Đại Việt Sử Ký Toàn Thư
[155]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:   0%|          | 1/300 [00:03<16:59,  3.41s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 53.51145038167938


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 55.79124579124579


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 54.08945686900958


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 140.0


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.99674267100977


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 54.97041420118343


Đại Việt Sử Ký Toàn Thư
[155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.19526627218935


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 54.97041420118343


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 54.08945686900958


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 140.0


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.99674267100977


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 54.97041420118343


Đại Việt Sử Ký Toàn Thư
[155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 54.97041420118343


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 140.0


Đại Việt Sử Ký Toàn Thư
[154]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.562130177514796


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 54.97041420118343


Đại Việt Sử Ký Toàn Thư
[155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[155]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.74556213017751


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.

Mapping source_excerpt to chunks:   1%|          | 2/300 [00:04<09:44,  1.96s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.29390681003584


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.58004158004158


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.93927125506073


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.534412955465584


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.46981627296588


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 55.74898785425101


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 54.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.51012145748988


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.93927125506073


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.534412955465584


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.46981627296588


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 55.74898785425101


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 54.26229508196722


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 54.12955465587044


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.91497975708503


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.93927125506073


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 55.74898785425101


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 54.12955465587044


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:   1%|          | 3/300 [00:06<10:16,  2.07s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.802197802197796


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.60335195530726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 55.12820512820513


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.65129682997119


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.604395604395606


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 56.7032967032967


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 63.80116959064327


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.802197802197796


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.60335195530726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 55.12820512820513


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.65129682997119


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.604395604395606


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 56.7032967032967


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 63.2967032967033


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 140.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.35164835164834


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 56.59340659340659


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.604395604395606


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 56.7032967032967


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 140.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 61.098901098901095


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:   1%|▏         | 4/300 [00:07<08:06,  1.64s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.945945945945944


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.32432432432433


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 58.93416927899686


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 64.43768996960486


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 59.45945945945945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 58.47953216374269


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 57.83783783783784


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.945945945945944


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.32432432432433


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 58.93416927899686


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 64.43768996960486


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 59.45945945945945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 58.47953216374269


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 57.83783783783784


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.027027027027025


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.945945945945944


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 58.93416927899686


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 64.43768996960486


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 58.47953216374269


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 59.74842767295597


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 57.83783783783784


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:   2%|▏         | 5/300 [00:08<07:02,  1.43s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.727598566308245


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.0958904109589


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.141689373297


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.961352657004824


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.893719806763286


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.306122448979586


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.99516908212561


Đại Việt Sử Ký Toàn Thư
[155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.99516908212561


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.141689373297


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.961352657004824


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.893719806763286


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.306122448979586


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.99516908212561


Đại Việt Sử Ký Toàn Thư
[155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.961352657004824


Đại Việt Sử Ký Toàn Thư
[154]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.893719806763286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.360433604336045


Đại Việt Sử Ký Toàn Thư
[155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[155]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.37681159420289


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.

Mapping source_excerpt to chunks:   2%|▏         | 6/300 [00:10<07:34,  1.55s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.42394822006472


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.147208121827404


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.685279187817265


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.639593908629436


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.20812182741116


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.56410256410257


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.685279187817265


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.147208121827404


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.685279187817265


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.639593908629436


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.20812182741116


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.56410256410257


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.685279187817265


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.147208121827404


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.20812182741116


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.685279187817265


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.20812182741116


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.685279187817265


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.20812182741116


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.19289340101523


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 12, ngày mồng một Mậu Dần, Chiêu Hoàng mở hội lớn ở điện Thiên An, ngự trên sập báu, các quan mặc triều phục vào chầu, lạy ở dưới sân. Chiêu Hoàng bèn trút bỏ áo ngự mời Trần Cảnh lên ngôi hoàng đế.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:   2%|▏         | 7/300 [00:12<07:48,  1.60s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.42553191489362


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.17687074829932


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.15151515151515


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.93877551020408


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.17687074829932


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.15151515151515


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.93877551020408


Đại Việt Sử Ký Toàn Thư
[155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.29931972789115


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[154]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.29931972789115


Đại Việt Sử Ký Toàn Thư
[156]
Bầy tôi dâng tôn hiệu là Khải Thiên Lập Cực Chí Nhân Chương Hiếu Hoàng Đế. Phong Trần Thủ Độ làm Quốc thượng phụ, nắm giữ mọi việc cai trị trong nước.

Mapping source_excerpt to chunks:   3%|▎         | 8/300 [00:12<06:40,  1.37s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.08045977011494


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.22988505747126


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.0379746835443


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.22988505747126


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.0379746835443


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.12643678160919


Đại Việt Sử Ký Toàn Thư
[155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[155]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[156]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[156]
Trở lên triều Lý, 9 vua, từ Thái Tổ năm canh Tuất [1010] đến Chiêu Hoàng năm Ất Dậu [1225], cộng 216 năm.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.

Mapping source_excerpt to chunks:   3%|▎         | 9/300 [00:14<06:20,  1.31s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.13270142180095


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.5


Đại Việt Sử Ký Toàn Thư
[154, 155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.95744680851064


Đại Việt Sử Ký Toàn Thư
[155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.5


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.13270142180095


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.5


Đại Việt Sử Ký Toàn Thư
[154, 155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.95744680851064


Đại Việt Sử Ký Toàn Thư
[155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.5


Đại Việt Sử Ký Toàn Thư
[155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.83333333333333


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.13270142180095


Đại Việt Sử Ký Toàn Thư
[154]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[154, 155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.95744680851064


Đại Việt Sử Ký Toàn Thư
[155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.83333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.16666666666667


Đại Việt Sử Ký Toàn Thư
[155, 156]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 50.83333333333333


Đại Việt Sử Ký Toàn Thư
[156]
Năm Ất Dậu [1225], mùa đông, tháng 12, ngày 12 Mậu Dần, nhận thiền vị của Chiêu Hoàng, lên ngôi Hoàng Đế, đổi niên hiệu là Kiến Trung.

Mapping source_excerpt to chunks:   3%|▎         | 10/300 [00:15<06:23,  1.32s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.42105263157895


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.005181347150256


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.731070496083554


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.005181347150256


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.731070496083554


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.876288659793815


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trước kia, tổ tiên vua là người đất Mân (có người nói là người Quế Lâm), có người tên là Kinh đến ở hương Tức Mặc [1], phủ Thiên Trường, sinh ra Hấp, Hấp sinh ra Lý, Lý sinh ra Thừa, đời đời làm nghề đánh cá.

Mapping source_excerpt to chunks:   4%|▎         | 11/300 [00:17<07:18,  1.52s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.74774774774775


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.40740740740741


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.74774774774775


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.14814814814815


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.85185185185186


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.88888888888889


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.627376425855516


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.85185185185186


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155, 156]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[156]
Phong Trần Thủ Độ làm Thái sư thống quốc hành quân vụ chinh thảo sư.Phế thượng hoàng nhà Lý ra ở chùa Chân Giáo, gọi là Huệ Quang đại sư.

Mapping source_excerpt to chunks:   4%|▍         | 12/300 [00:18<06:15,  1.30s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.27736131934033


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.160583941605836


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.712574850299404


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.79256360078278


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.41880341880342


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.27736131934033


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.160583941605836


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.712574850299404


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.221105527638194


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.20958083832335


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.20958083832335


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.712574850299404


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, ngày mồng 10, Trần Thủ Độ giết Lý Huệ Tông ở chùa Chân Giáo. Trước đó, Thượng hoàng nhà Lý có lần ra chơi chợ Đông, dân chúng tranh nhau chạy đến xem, có người thương khóc. Thủ Độ sợ lòng người nhớ vua cũ, sinh biến loạn, cho dời đến ở chùa Chân Giáo; bề ngoài giả vờ là để phụng sự, mhưng bên trong thực ra là để dễ bề giữ chặt.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:   4%|▍         | 13/300 [00:22<10:14,  2.14s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.15686274509803


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.359773371104815


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.19263456090652


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.010771992818675


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.77620396600567


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.867924528301884


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.3257790368272


Đại Việt Sử Ký Toàn Thư
[155]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.252595155709336


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.77620396600567


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.359773371104815


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.19263456090652


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.010771992818675


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.77620396600567


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.867924528301884


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.3257790368272


Đại Việt Sử Ký Toàn Thư
[155]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.342776203966004


Đại Việt Sử Ký Toàn Thư
[155]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.04249291784702


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.90934844192634


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.19263456090652


Đại Việt Sử Ký Toàn Thư
[154]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.05949008498584


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nghi thức lễ đó như sau: Hàng năm vào ngày mồng 4 tháng 4, tể tướng và trăm quan đến trực ngoài cửa thành từ lúc gà gáy, tờ mờ sáng thì tiến vào triều. Vua ngự ở cửa Hữu Lang điện Đại Minh trăm quan mặc nhung phục lạy hai lạy rồi lui ra. Ai nấy đều thành đội ngũ, nghi trượng theo hầu ra cửa Tây thành, đến đền thờ thần núi Đồng Cổ, họp nhau lại uống máu ăn thề.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

Mapping source_excerpt to chunks:   5%|▍         | 14/300 [00:26<13:39,  2.86s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.25


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.405676126878134


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.22797927461139


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.90832328106152


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.610837438423644


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.01680672268907


Đại Việt Sử Ký Toàn Thư
[155]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.386243386243386


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.2183908045977


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.22797927461139


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.90832328106152


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.610837438423644


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.01680672268907


Đại Việt Sử Ký Toàn Thư
[155]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.44827586206896


Đại Việt Sử Ký Toàn Thư
[155]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.2183908045977


Đại Việt Sử Ký Toàn Thư
[154]
Sai Phụ quốc thái phó Phùng Tá Chu quyền Tri phủ Nghệ An, cho phép ban tước từ tá chức, xá nhân trở xuống cho người khác, rồi sau về triều tâu lê. Sử thần Ngô Sĩ Liên nói: Ban tước cho người là quyễn của thiên tử, không phải là quyền của kẻ làm tôi . Phùng Tá Chu là bề tôi cũ triều Lý, không có việc cần phải chuyên quyễn như ra ngoài cương giới, làm lợi cho quốc gia, vỗ yên trăm họ, mà lại cho phép chuyên quyền thì cả người cho phép đều sai cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.13793103448276


Đại Việt Sử Ký Toàn Thư
[154]

Mapping source_excerpt to chunks:   5%|▌         | 15/300 [00:34<19:49,  4.17s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.281138790035584


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.34180138568129


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38152610441767


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.79919678714859


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.168674698795186


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 53.002070393374744


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.25380710659899


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.35971223021583


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 51.315789473684205


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.34180138568129


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38152610441767


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.79919678714859


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.168674698795186


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 53.002070393374744


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.25380710659899


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.35971223021583


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.99598393574297


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.78313253012048


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38152610441767


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 49.79919678714859


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.002070393374744


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 50.35971223021583


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.05479452054795


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tý, [Kiến Trung] năm thứ 4 [1228]. (Tống Thiệu Định năm thứ 1)... Tháng 12, Nguyễn Nộn đánh giết Đoàn Thượng. Nộn đã phá được Thượng, nhân gộp cả quân của Thượng, cướp bắt con trai, con gái, tài sản, trâu ngựa đất Hồng Châu. Con của Thượng là Văn đem gia thuộc đến hàng.

Mapping source_excerpt to chunks:   5%|▌         | 16/300 [00:36<16:58,  3.59s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.6058394160584


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.52554744525548


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.58914728682171


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.00000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 57.72357723577235


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 58.26771653543308


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 55.47445255474452


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.52554744525548


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.58914728682171


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.00000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 57.72357723577235


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 58.26771653543308


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 55.47445255474452


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.44525547445255


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 56.58914728682171


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 56.00000000000001


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 58.26771653543308


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 56.69291338582677


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 57.664233576642346


Đại Việt Sử Ký Toàn Thư
[155, 156]
Kỷ Sửu,[Kiến Trung] năm thứ 5[1229], (Tống Thiệu Định năm thứ 2, Nguyên Thái Tông Oa Khoát Đài năm thứ [1]. Mùa xuân, tháng 3, nhật thực. Nguyễn Nộn ốm chết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 65.32258064516128


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:   6%|▌         | 17/300 [00:37<12:59,  2.75s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 55.483870967741936


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.24293785310734


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.363636363636374


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.268292682926834


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 54.77707006369427


Đại Việt Sử Ký Toàn Thư
[155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 54.64480874316939


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 55.483870967741936


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.24293785310734


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.363636363636374


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.268292682926834


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 54.77707006369427


Đại Việt Sử Ký Toàn Thư
[155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 54.64480874316939


Đại Việt Sử Ký Toàn Thư
[155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 55.483870967741936


Đại Việt Sử Ký Toàn Thư
[154]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 56.363636363636374


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 54.77707006369427


Đại Việt Sử Ký Toàn Thư
[155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 55.65217391304348


Đại Việt Sử Ký Toàn Thư
[155]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 56.830601092896174


Đại Việt Sử Ký Toàn Thư
[155, 156]
Canh Dần, [Kiến Trung] năm thứ 5 [1230], (Tống Thiệu Định năm thứ 3). Mùa xuân, tháng 3, khảo xét các luật lệ của triều trước, soạn thành Quốc triều thống chế và sửa đổi hình luật lễ nghi, gồm 20 quyển.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:   6%|▌         | 18/300 [00:38<10:31,  2.24s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.10058027079303


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 57.26141078838174


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.88679245283019


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.71028037383177


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.072625698324025


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.83585313174945


Đại Việt Sử Ký Toàn Thư
[155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 51.559251559251564


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.10058027079303


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 57.26141078838174


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.88679245283019


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.71028037383177


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.072625698324025


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.83585313174945


Đại Việt Sử Ký Toàn Thư
[155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.32352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 57.26141078838174


Đại Việt Sử Ký Toàn Thư
[154]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.71028037383177


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 51.83585313174945


Đại Việt Sử Ký Toàn Thư
[155]
Tân Mão, [Kiến Trung] năm thứ 7 [1231], (Tống Thiệu Định năm thứ 4). Mùa xuân, tháng giêng, sai NộI minh tự Nguyễn Bang Cốc (hoạn quan) chỉ huy binh lính phủ mình đào vét kênh Trầm và kênh Hào [1] từ phủ Thanh Hóa đến địa giớI phía nam Diễn Châu. Việc xong, thăng Bang Cốc làm Phụ Quốc thượng hầu.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:   6%|▋         | 19/300 [00:40<11:07,  2.37s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.85987261146497


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.92872117400419


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.76991150442478


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.123893805309734


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.785714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.56140350877193


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.76991150442478


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.123893805309734


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.56140350877193


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.91228070175438


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[155]
Lớn lên Bà Liệt khôi ngô, giỏi võ nghệ, xin sung vào đội đánh vật. Một hôm, bà Liệt đánh cầu với người trong đội, người kia vật ngã Bà Liệt, bóp cổ Liệt đến suýt tắt thở. Thượng hoàng thét lên : " Con ta đấy". Người ấy sợ hãi lạy tạ. Ngay hôm đó, Thượng hoàng nhận Bà Liệt làm con, cho nên có lệnh này.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:   7%|▋         | 20/300 [00:43<12:06,  2.60s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.18181818181819


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 58.57142857142856


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 57.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.28455284552846


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 61.29032258064516


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 57.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 58.57142857142856


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 57.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.28455284552846


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 61.29032258064516


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 57.857142857142854


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 58.57142857142856


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 57.857142857142854


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 61.29032258064516


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 56.809338521400775


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 55.714285714285715


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giáp Ngọ, [Thiên Ứng Chính Bình] năm thứ 3 [1234], (Tống Đoan Bình năm thứ 1). Mùa xuân, tháng giêng, ngày 18, thượng hoàng băng ở cung Phụ Thiên, thọ 51 tuổi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 60.0


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:   7%|▋         | 21/300 [00:44<09:35,  2.06s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.18032786885246


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.540983606557376


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.18032786885246


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.540983606557376


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.459016393442624


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.81967213114754


Đại Việt Sử Ký Toàn Thư
[154]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.540983606557376


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.459016393442624


Đại Việt Sử Ký Toàn Thư
[155]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.18032786885246


Đại Việt Sử Ký Toàn Thư
[155, 156]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 57.377049180327866


Đại Việt Sử Ký Toàn Thư
[156]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 49.18032786885246


Đại Việt Sử Ký Toàn Thư
[156]
Phong Trần Thủ Độ làm Thống quốc thái sư, tri Thanh Hóa phủ sự.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 49.18032786885246

Mapping source_excerpt to chunks:   7%|▋         | 22/300 [00:45<07:31,  1.62s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.783715012722645


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.08928571428571


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.95061728395062


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.51207729468599


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.875


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.21593830334191


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.19642857142857


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.783715012722645


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.08928571428571


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.95061728395062


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.51207729468599


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.875


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.08928571428571


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.53571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.53571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.53571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.875


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.98214285714286


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Hiển Hoàng [Trần] Liễu làm tri Thánh Từ cung, nhân nước to, đi thuyền vào chầu, thấy người phi cũ của triều Lý liền cưỡng dâm ở cung Lệ Thiên. Đình thân hặc tâu, vì thế mới đổi tên cung Thưởng Xuân, giáng Hiển làm Hoài Vương.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.

Mapping source_excerpt to chunks:   8%|▊         | 23/300 [00:47<07:58,  1.73s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 53.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.56521739130435


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.02164502164502


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.52845528455285


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.15447154471545


Đại Việt Sử Ký Toàn Thư
[155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.96747967479674


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.52845528455285


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 53.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.56521739130435


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.02164502164502


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.52845528455285


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.15447154471545


Đại Việt Sử Ký Toàn Thư
[155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 59.34959349593496


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.032520325203244


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[154]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.52845528455285


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.15447154471545


Đại Việt Sử Ký Toàn Thư
[155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 59.34959349593496


Đại Việt Sử Ký Toàn Thư
[155]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.59349593495935


Đại Việt Sử Ký Toàn Thư
[155, 156]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 50.40650406504066


Đại Việt Sử Ký Toàn Thư
[156]
Lập công chúa Thuận Thiên họ Lý, là vợ của Hoài Vương Liễu, anh vua, làm hoàng hậu Thuận Thiên. Giáng Chiêu Thánh làm công chúa.

Mapping source_excerpt to chunks:   8%|▊         | 24/300 [00:48<06:40,  1.45s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.41811846689895


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.52054794520548


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.57534246575342


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 57.36434108527132


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 60.769230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 59.76095617529881


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 61.354581673306775


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 56.16438356164384


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.52054794520548


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.57534246575342


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 57.36434108527132


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 60.769230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 59.76095617529881


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 61.354581673306775


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 56.16438356164384


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.31506849315068


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.57534246575342


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 57.36434108527132


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 60.769230769230774


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 61.354581673306775


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 57.14285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 56.849315068493155


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mậu Tuất, [Thiên Ứng Chính Bình] năm thứ 7 [1238], (Tống Gia Hy năm thứ 2). Mùa xuân, tháng 2, sai Thống quốc thái sư Trần Thủ Độ duyệt định sổ đinh phủ Thanh Hoá.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:   8%|▊         | 25/300 [00:49<05:51,  1.28s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.65079365079365


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.69444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.861111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.094339622641506


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.69444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 53.125


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 55.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.611111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.69444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.861111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.094339622641506


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.69444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 53.125


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 55.55555555555556


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.69444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.69444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 54.861111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.094339622641506


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 53.125


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 57.93650793650793


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 54.16666666666667


Đại Việt Sử Ký Toàn Thư
[155, 156]
Canh Tý, [Thiên Ứng Chính Bình] năm thứ 9 [1240], (Tống Gia Hy năm thứ 4). ... Tháng 9, ngày 25, hoàng đích trưởng tử là Hoảng sinh, lập làm Đông cung thái tử. Đại xá.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:   9%|▊         | 26/300 [00:49<05:16,  1.15s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.549828178694156


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.30379746835443


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 53.16455696202531


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 58.19397993311037


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.32974910394266


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.56603773584906


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 53.16455696202531


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.30379746835443


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 53.16455696202531


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 58.19397993311037


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.32974910394266


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.56603773584906


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 53.16455696202531


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.46835443037975


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.30379746835443


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 53.16455696202531


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 58.19397993311037


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 50.56603773584906


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 55.79710144927537


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 53.16455696202531


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhâm Dần, [Thiên Ứng Chính Bình] năm thứ 11 [1242], (Tống Thuần Hựu năm thứ 2). Mùa xuân, tháng 2, chia nước làm 12 lộ [1]. Đặt chức an phủ, trấn phủ, có 2 viên chánh, phó để cai trị.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:   9%|▉         | 27/300 [00:50<04:56,  1.08s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.81818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.08362369337979


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.67631103074141


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.41509433962264


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.76258992805755


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.747081712062254


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.81818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.08362369337979


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.67631103074141


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.41509433962264


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.76258992805755


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.64459930313589


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.64459930313589


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.250871080139376


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.08362369337979


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.41509433962264


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.76258992805755


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Thiên Ứng Chính Bình] năm thứ 10 [1241], (Tống Thuần Hựu năm thứ 1). ... Vua thân hành cầm quân đi đánh các trại Vĩnh An, Vĩnh Bình [3] của nước Tống phía đường bộ, vượt qua châu Khâm, châu Liêm, tự xưng là Trai Lang, bỏ thuyền lớn ở trong cõi, chỉ đi bằng các thuyền nhỏ Kim Phụng, Nhật Quang, Nguyệt Quang.

Mapping source_excerpt to chunks:   9%|▉         | 28/300 [00:53<06:57,  1.54s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.23374340949033


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.40836012861736


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.97260273972602


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.637010676156585


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.947454844006565


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.72375690607734


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.74868189806678


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.4818763326226


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.89852700490998


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.40836012861736


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.97260273972602


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.637010676156585


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.947454844006565


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.72375690607734


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.74868189806678


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.980707395498385


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.659163987138264


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.40836012861736


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.97260273972602


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.947454844006565


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Mùi, [Thiên Ứng Chính Bình] năm thứ 16 [1247], (Tống Thuần Hựu năm thứ 7). Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ. Ban cho Nguyễn Hiền đỗ trạng nguyên Lê Văn Hưu đỗ bảng nhãn; Đặng Ma La đỗ thám hoa lang. Trước đây, hai khóa Nhâm Thìn (1232) và Kỷ Hợi (1239) chia làm giáp, ất, chưa có chọn tam khôi [1]. Đến khoa này mới đặt [tam khôi].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.74868189806678


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  10%|▉         | 29/300 [00:57<09:47,  2.17s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.12896405919662


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.166666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.33178654292344


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.416666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.4516129032258


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.07772020725389


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.58333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.85987261146497


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.12896405919662


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.166666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.33178654292344


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.416666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.4516129032258


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.07772020725389


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.58333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.41666666666667


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.91666666666667


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.166666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.33178654292344


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.4516129032258


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.58333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.888888888888886


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248], (Tống Thuần Hựu năm thứ 8)... Tháng 3, lệnh các lộ đắp đê phòng lụt, gọi là để quai vạc, từ đầu nguồn đến bờ biển, để ngăn nước lũ tràn ngập. Đặt hà đê chánh phó sứ để quản đốc. Đắp đê quai vạc là bắt đầu từ đó.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  10%|█         | 30/300 [00:59<09:41,  2.15s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.96124031007752


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.837209302325576


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.6124031007752


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 51.162790697674424


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.41085271317829


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.21875


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.837209302325576


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.6124031007752


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 51.162790697674424


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.41085271317829


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.21875


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 56.58914728682171

Mapping source_excerpt to chunks:  10%|█         | 31/300 [00:59<07:49,  1.75s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.6124031007752


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 51.162790697674424


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 56.58914728682171


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.93798449612403


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 52.71317829457365


Đại Việt Sử Ký Toàn Thư
[156]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 45.736434108527135


Đại Việt Sử Ký Toàn Thư
[156]
Mậu Thân, [Thiên Ứng Chính Bình] năm thứ 17 [1248]... Mùa hạ, tháng 6, hoàng hậu Thuận Thiên băng, truy tôn là Hiển Tử Thuận Thiên hoàng thái hậu.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 53.02325581395348


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.96428571428571


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.53571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.32142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.46428571428572


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.14414414414415


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.35602094240838


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.504950495049506


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.97297297297297


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 53.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.53571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.32142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.46428571428572


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.14414414414415


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.35602094240838


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.504950495049506


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.97297297297297


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

Mapping source_excerpt to chunks:  11%|█         | 32/300 [01:00<06:27,  1.45s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.32142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 54.46428571428572


Đại Việt Sử Ký Toàn Thư
[154]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.35602094240838


Đại Việt Sử Ký Toàn Thư
[154, 155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.97297297297297


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 56.15763546798029


Đại Việt Sử Ký Toàn Thư
[155]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 52.67857142857143


Đại Việt Sử Ký Toàn Thư
[155, 156]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 53.57142857142857


Đại Việt Sử Ký Toàn Thư
[156]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[156]
Canh Tuất, [Thiên Ứng Chính Bình] năm thứ 19 [1250], (Tống Thuần Hựu năm thứ 10)... Xuống chiếu cho thiên hạ gọi vua là quan gia [4].
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 53.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.75824175824175


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.73197781885398


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.17453798767968


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.956043956043956


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[155]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.07484407484408


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.688644688644686


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.73197781885398


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.17453798767968


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn muốn lấy công chúa Thiên Thành, nhưng không làm thế nào được, mới nhân ban đêm lẻn vào chỗ ở của công chúa thông dâm với nàng... Vua bắt đắc dĩ phải gả công chúa Thiên Thành cho Quốc Tuấn, lấy 2000 khoảnh ruộng ở phủ Ứng Thiên để hoàn lại sính vật cho Trung Thành Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).

Mapping source_excerpt to chunks:  11%|█         | 33/300 [01:02<07:26,  1.67s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.48366013071896


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.751633986928105


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 59.12408759124088


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.91176470588235


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 59.01639344262295


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.172413793103445


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 57.65124555160141


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 54.90196078431373


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.751633986928105


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 59.12408759124088


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.91176470588235


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 59.01639344262295


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.172413793103445


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 57.65124555160141


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 54.90196078431373


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.673202614379086


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.751633986928105


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 59.12408759124088


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 59.01639344262295


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 57.65124555160141


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 57.0446735395189


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 57.51633986928104


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhâm Tý, Nguyên Phong năm thứ 2 [1252], (Tống Thuần Hựu năm thứ 13). Mùa xuân, tháng giêng, vua thân đi đánh Chiêm Thành, sai Khâm Thiên Đại vương Nhật Hiệu làm lưu thủ.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.

Mapping source_excerpt to chunks:  11%|█▏        | 34/300 [01:03<06:23,  1.44s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.00945626477541


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.78846153846154


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.24355971896955


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.174934725848566


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.40650406504066


Đại Việt Sử Ký Toàn Thư
[155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 49.64539007092199


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.00945626477541


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.78846153846154


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.24355971896955


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.174934725848566


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.40650406504066


Đại Việt Sử Ký Toàn Thư
[155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 49.082568807339456


Đại Việt Sử Ký Toàn Thư
[155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.082568807339456


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.95412844036697


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.00945626477541


Đại Việt Sử Ký Toàn Thư
[154]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.72389791183295


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 50.40650406504066


Đại Việt Sử Ký Toàn Thư
[155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.86876640419947


Đại Việt Sử Ký Toàn Thư
[155]
Quý Sửu, Nguyên Phong năm thứ 3 [1253], (Tống Bảo Hựu năm thứ 1). Mùa hạ, tháng 4, cho Khâm Thiên Đại Vương Nhật Hiệu làm Thái úy. Tháng 6, lập Quốc học viện. Đắp tượng Khổng Tử, Chu Công và Á Thánh (Mạnh Tử), vẽ tranh 72 người hiền để thờ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  12%|█▏        | 35/300 [01:05<06:58,  1.58s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.625


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.104803493449786


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.88962472406181


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.201834862385326


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.91943127962085


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.125313283208015


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.70422535211267


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.795823665893266


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.104803493449786


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.88962472406181


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.201834862385326


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.91943127962085


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.125313283208015


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.70422535211267


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.90829694323144


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.2882096069869


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.104803493449786


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 49.88962472406181


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.20273348519362


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 50.70422535211267


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.22394678492239


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Nguyên Phong] năm thứ 4 [1254], (Tống Bảo Hựu năm thứ 2). Mùa hạ, tháng 5, định quy chế xe kiệu, mũ áo và người hầu cho tôn thất và các quan văn võ theo thứ bậc khác nhau. Từ tông thất cho đến quan ngũ phẩm đều được đi kiệu, ngựa và võng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.

Mapping source_excerpt to chunks:  12%|█▏        | 36/300 [01:08<08:50,  2.01s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.26241134751773


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.138364779874216


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.80790960451978


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.50282485875706


Đại Việt Sử Ký Toàn Thư
[155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.93785310734464


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.189368770764126


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.80790960451978


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.50282485875706


Đại Việt Sử Ký Toàn Thư
[155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.189368770764126


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.50282485875706


Đại Việt Sử Ký Toàn Thư
[155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[155]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thế rồi hậu cung có mang. Sau quả nhiên sinh con trai, hai cánh tay có chữ "Chiêu Văn đồng tử", nét tử rất rõ, vì thế đặt hiệu là Chiêu Văn (Tức là Nhật Duật). Lớn lên, nét chữ mới mất đi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  12%|█▏        | 37/300 [01:10<07:52,  1.80s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.518518518518526


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.92982456140351


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.54385964912281


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.30699774266366


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.340425531914896


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.68421052631579


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.558086560364465


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.518518518518526


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.92982456140351


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.54385964912281


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.30699774266366


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.340425531914896


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.68421052631579


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.122807017543856


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.175438596491226


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.92982456140351


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.30699774266366


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 48.68421052631579


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.122807017543856


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Nguyên Phong] năm thứ 6 [1256]... Mùa xuân, tháng 2, mở khoa thi chọn kẻ sĩ... Hồi quốc sơ, cử người chưa phân kinh trại, người đỗ đầu ban cho [danh hiệu] trạng nguyên. Đến nay, chia Thanh Hóa, Nghệ An làm trại, cho nên có phân biệt kinh trại.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  13%|█▎        | 38/300 [01:12<08:07,  1.86s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.45454545454545


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.38775510204081


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.22562674094708


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.40816326530612


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.50127877237852


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.38775510204081


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.22562674094708


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.40816326530612


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.50127877237852


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.40816326530612


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.38775510204081


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.40816326530612


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.40816326530612


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.91836734693877


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa thu, tháng 7, Vũ Thành Vương Doãn đem cả nhà trốn sang nước Tống... (Doãn là con Yên Sinh Vương do Hiển Từ sinh. Yên Sinh có hiềm khích với vua, đến khi Hiển Từ mất, bị thất thế, nên trốn sang nước Tống).

Mapping source_excerpt to chunks:  13%|█▎        | 39/300 [01:13<07:51,  1.81s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.29850746268657


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.38709677419355


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.12676056338028


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.38709677419355


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.12676056338028


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.38709677419355


Đại Việt Sử Ký Toàn Thư
[154]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[155]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua ngự thuyền nhỏ đến thuyền Thái úy Nhật Hiệu hỏi kế sách (chống giặc)... Vua lập tức dời thuyền đến hỏi Thái sư Trần Thủ Độ, Thủ Độ trả lời: "Đầu thần chưa rơi xuống đất, bệ hạ đừng lo gì khác".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  13%|█▎        | 40/300 [01:14<06:51,  1.58s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.1747572815534


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.14563106796117


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.689320388349515


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.66019417475729


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.63106796116505


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.1747572815534


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.14563106796117


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.689320388349515


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.66019417475729


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.63106796116505


Đại Việt Sử Ký Toàn Thư
[155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.14563106796117


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.1747572815534


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.14563106796117


Đại Việt Sử Ký Toàn Thư
[154]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.66019417475729


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.14563106796117


Đại Việt Sử Ký Toàn Thư
[155]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.039603960396036


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua nói: "Cự Đà tội đáng giết cả họ, song đời xưa đã có chuyện Dương Châm không được ăn thịt dê, đến nỗi làm quân nước Trịnh bị thua. Việc Cực Đà là lỗi ở ta, tha cho hắn tội chết, cho phép hắn đánh giặc chuộc tội".

Mapping source_excerpt to chunks:  14%|█▎        | 41/300 [01:16<07:09,  1.66s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.675159235668794


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.62606232294618


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.65934065934066


Đại Việt Sử Ký Toàn Thư
[154, 155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.126074498567334


Đại Việt Sử Ký Toàn Thư
[155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.767313019390585


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.65934065934066


Đại Việt Sử Ký Toàn Thư
[154, 155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.126074498567334


Đại Việt Sử Ký Toàn Thư
[155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.23655913978495


Đại Việt Sử Ký Toàn Thư
[155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[154]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.6989247311828


Đại Việt Sử Ký Toàn Thư
[154, 155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.125348189415035


Đại Việt Sử Ký Toàn Thư
[155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[155]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.53763440860215


Đại Việt Sử Ký Toàn Thư
[155, 156]
Định công phong tước: cho Lê Phụ Trần làm Ngự sử đại phu; lại đem công chúa Chiêu Thánh gả cho. Vua nói: "Trẫm không có khanh, thì đâu có ngày nay. Khanh hãy cố gắng để cùngđược trọn vẹn về sau".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  14%|█▍        | 42/300 [01:17<06:23,  1.49s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.74626865671642


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.877192982456144


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.01492537313433


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.01492537313433


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.887445887445885


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 50.74626865671642


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.74626865671642


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.877192982456144


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.01492537313433


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.01492537313433


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.887445887445885


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.26865671641791


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.74626865671642


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.877192982456144


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.01492537313433


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.79919678714859


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.50746268656716


Đại Việt Sử Ký Toàn Thư
[156]
Tháng 2, ngày 24, vua nhường ngôi cho Hoàng thái tử Hoảng, lui ở Bắc Cung. Thái tử lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Long năm thứ 1.

Mapping source_excerpt to chunks:  14%|█▍        | 43/300 [01:18<05:31,  1.29s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 48.12499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.011600928074245


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.49438202247191


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.83544303797469


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.64508393285371


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.881856540084385


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.0379746835443


Đại Việt Sử Ký Toàn Thư
[155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.72573839662447


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.14767932489452


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.49438202247191


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.83544303797469


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.64508393285371


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.881856540084385


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.0379746835443


Đại Việt Sử Ký Toàn Thư
[155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.83544303797469


Đại Việt Sử Ký Toàn Thư
[155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.83544303797469


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.41350210970464


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.83544303797469


Đại Việt Sử Ký Toàn Thư
[154]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.881856540084385


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.03669724770643


Đại Việt Sử Ký Toàn Thư
[155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.83544303797469


Đại Việt Sử Ký Toàn Thư
[155]
Trần thị được gọi là quốc mẫu vì đó vốn là hiệu của Ngô phu nhân trước kia, tức là hoàng hậu Thái Tông thấy Linh Từ đã từng làm hoàng hậu của Lý Huệ Tông, không nỡ gọi là công chúa, cho nên phong làm quốc mẫu, cũng là biệt danh của hoàng hậu.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  15%|█▍        | 44/300 [01:21<07:34,  1.77s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.35807860262008


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.73118279569892


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.418013856812934


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.20618556701031


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.388429752066116


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.97520661157025


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.73118279569892


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.418013856812934


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.20618556701031


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.867768595041326


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.73118279569892


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.867768595041326


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi người Nguyên tắt đường vào cướp, kinh thành thất thủ, Linh Từ ở Hoàng Giang, giữ gìn hoàng thái tử, cung phi, công chúa và vợ con các tướng soái thoát khỏi giặc cướp, lại khám xét thuyền các nhà chứa giấu quân khí đều đưa dùng vào việc quân.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.

Mapping source_excerpt to chunks:  15%|█▌        | 45/300 [01:24<08:40,  2.04s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.913580246913575


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.0377358490566


Đại Việt Sử Ký Toàn Thư
[154, 155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.0377358490566


Đại Việt Sử Ký Toàn Thư
[154, 155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.93877551020408


Đại Việt Sử Ký Toàn Thư
[155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.65986394557823


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[154, 155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.65986394557823


Đại Việt Sử Ký Toàn Thư
[155]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[155, 156]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.25850340136054


Đại Việt Sử Ký Toàn Thư
[156]
Cho Chiêu Minh Đại Vương Quang Khải làm Thái úy. Bấy giờ, anh vua là Quốc Khang lớn tuổi hơn, nhưng tài năng tầm thường, nên phong Quang Khải làm tướng.

Mapping source_excerpt to chunks:  15%|█▌        | 46/300 [01:24<07:10,  1.70s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.60189573459715


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.654028436018955


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.60189573459715


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.36734693877551


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.21593830334191


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.60189573459715


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.654028436018955


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.60189573459715


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.36734693877551


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.497630331753555


Đại Việt Sử Ký Toàn Thư
[155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.60189573459715


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[155]
Đổi hương Tức Mặc làm phủ Thiên Trường, cung gọi là Trùng Quang. Lại xây riêng một khu cung khác cho vua nối ngôi ngự khi về chầu, gọi là cung Trùng Hoa. Lại làm chùa ở phía tây cung Trùng Quang gọi là chùa Phổ Minh.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  16%|█▌        | 47/300 [01:26<07:16,  1.73s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 38.095238095238095


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.351931330472105


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.412698412698404


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.65079365079365


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.412698412698404


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.351931330472105


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.412698412698404


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.65079365079365


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.412698412698404


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.412698412698404


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.412698412698404


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[156]
Tháng giêng, sai Điện tiền chỉ huy sứ Phạm Cự Địa và Trần Kiều sang Nguyên. Vua Nguyên xuống chiếu ưu đãi, cho 3 năm một lần cống.

Mapping source_excerpt to chunks:  16%|█▌        | 48/300 [01:27<06:07,  1.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.976190476190474


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.85365853658537


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 53.04878048780488


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.688705234159784


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 55.73770491803278


Đại Việt Sử Ký Toàn Thư
[155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 53.68421052631579


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.976190476190474


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.85365853658537


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 53.04878048780488


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.688705234159784


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 55.73770491803278


Đại Việt Sử Ký Toàn Thư
[155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 53.68421052631579


Đại Việt Sử Ký Toàn Thư
[155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.976190476190474


Đại Việt Sử Ký Toàn Thư
[154]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.04878048780488


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 55.73770491803278


Đại Việt Sử Ký Toàn Thư
[155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 54.15549597855228


Đại Việt Sử Ký Toàn Thư
[155]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.526315789473685


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giáp tý,[ Thiệu Long] năm thứ 7 [1264], (Tống Cảnh Định năm thứ 5, Nguyên Chí Nguyên năm thứ nhất ). Mùa xuân, tháng giêng, Thái sư Trần Thủ Độ chết (thọ 71 tuổi), truy tặng Thượng phụ Thái sư Trung Vũ Đại Vương.

Mapping source_excerpt to chunks:  16%|█▋        | 49/300 [01:28<05:39,  1.35s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 47.90874524714829


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.48669201520913


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.20532319391636


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.432225063938624


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.34600760456274


Đại Việt Sử Ký Toàn Thư
[155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.855967078189295


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.48669201520913


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.20532319391636


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.432225063938624


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.34600760456274


Đại Việt Sử Ký Toàn Thư
[155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.627376425855516


Đại Việt Sử Ký Toàn Thư
[155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.247148288973385


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.247148288973385


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.86692015209125


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.72623574144486


Đại Việt Sử Ký Toàn Thư
[155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.32224532224532


Đại Việt Sử Ký Toàn Thư
[155]
Thái Tông có lần muốn cho người anh của Thủ Độ là An Quốc làm tể tướng. Thủ Độ tâu :" An Quốc là anh thần, nếu cho giỏi hơn thần thì thần xin trí sĩ, nếu cho thần giỏi hơn An Quốc thì không thể cử An Quốc. Nếu anh em đều làm tể tướng cả thì việc triều đình sẽ ra làm sao?".

Mapping source_excerpt to chunks:  17%|█▋        | 50/300 [01:30<06:33,  1.57s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.91891891891891


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.74809160305344


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.77922077922077


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.506493506493506


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.71457085828343


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.8051948051948


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.74809160305344


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.77922077922077


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.506493506493506


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.12987012987013


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.103896103896105


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.8051948051948


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.77922077922077


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.506493506493506


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, lấy Khâm Thiên Đại Vương Nhật Hiệu làm Tướng quốc thái úy, nắm chung việc nước. Bấy giờ, vua cho Nhật Hiệu làm Thái sư , nhưng Nhật Hiệu cố ý từ chối không nhận vì xấu hổ về việc viết chữ lên mạn thuyền. Vua tuy cho ông không nhận chức Thái sư, nhưng lại ban thêm hai chữ "Tướng quốc", thành "Tướng quốc thái uý".

Mapping source_excerpt to chunks:  17%|█▋        | 51/300 [01:33<08:17,  2.00s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.07582938388626


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.733668341708544


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.86729857819905


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.654028436018955


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.03178484107579


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.07582938388626


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.52058111380145


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.07582938388626


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.733668341708544


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.86729857819905


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.654028436018955


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.03178484107579


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.07582938388626


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.52058111380145


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.39336492890995


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.86729857819905


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.07582938388626


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.39336492890995


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, xuống chiếu cho vương hầu, công chúa, phò mã, cung tần chiêu tập dân phiêu tán không có sản nghiệp làm nô tỳ để khai khẩn ruộng bỏ hoang, lập thành điền trang.Vương hầu có trang thực bắt đầu từ đấy.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.236966824644554


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  17%|█▋        | 52/300 [01:36<09:09,  2.21s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.95774647887324


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.463414634146346


Đại Việt Sử Ký Toàn Thư
[154, 155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.512195121951216


Đại Việt Sử Ký Toàn Thư
[155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.95774647887324


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.463414634146346


Đại Việt Sử Ký Toàn Thư
[154, 155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.512195121951216


Đại Việt Sử Ký Toàn Thư
[155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.12195121951219


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[154]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154, 155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.512195121951216


Đại Việt Sử Ký Toàn Thư
[155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[155]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.5609756097561


Đại Việt Sử Ký Toàn Thư
[155, 156]
Theo chế độ cũ, không phải là nội nhân (hoạn quan ) thì không được làm hành khiển, chưa bao giờ dùng nho sĩ văn học. Bắt đầu từ đây, nho sĩ văn học mới giữ được quyền bính.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.

Mapping source_excerpt to chunks:  18%|█▊        | 53/300 [01:37<07:35,  1.85s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.625


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.73504273504274


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.5


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.73504273504274


Đại Việt Sử Ký Toàn Thư
[155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.49999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.49999999999999


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa Xuân, tháng giêng, Hàn lâm viện học sĩ kiêm Quốc Sử viện giám tu Lê Văn Hưu vâng sắc chỉ soạn xong bộ Đại việt sử ký từ Triệu Vũ đế đến Lý Chiêu Hoàng, gồm 30 quyển, dâng lên. Vua xuống chiếu khen ngợi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  18%|█▊        | 54/300 [01:39<07:26,  1.81s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.16546762589928


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.57894736842105


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.01114206128134


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.82716049382716


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.72948328267477


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.57894736842105


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.01114206128134


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.82716049382716


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.72948328267477


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.8421052631579


Đại Việt Sử Ký Toàn Thư
[155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.78947368421053


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.78947368421053


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.01114206128134


Đại Việt Sử Ký Toàn Thư
[154]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.82716049382716


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.8421052631579


Đại Việt Sử Ký Toàn Thư
[155]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.78947368421053


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tĩnh Quốc Đại Vương Quốc Khang dựng phủ đệ ở Diễn Châu, hành lang, điện vũ bão quanh, tráng lệ khác thường.Vua nghe tin ,sai người đến xem .Tĩnh Quốc sợ, mới tạc tượng phật để đó (nay là chùa Thông).
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  18%|█▊        | 55/300 [01:40<06:32,  1.60s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.22641509433962


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.639593908629436


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 40.56603773584906


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.22641509433962


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.639593908629436


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.22641509433962


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[155]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155, 156]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.22641509433962


Đại Việt Sử Ký Toàn Thư
[156]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[156]
Năm ấy, Mông Cổ đặt quốc hiệu là Đại Nguyên, sai sứ sang dụ vua vào chầu. Vua lấy cớ có bệnh từ chối không đi.

Mapping source_excerpt to chunks:  19%|█▊        | 56/300 [01:41<05:31,  1.36s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.727598566308245


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.611111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.043165467625904


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.13475177304965


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.52777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.0592885375494


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.411764705882355


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.30555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.611111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.043165467625904


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.13475177304965


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.52777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.0592885375494


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.411764705882355


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 54.861111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.30555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.52777777777778


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 49.411764705882355


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 54.861111111111114


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.03149606299213


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giáp Tuất, Bảo Phù năm thứ 2 [1274]... Tháng 12, sách phong hoàng trưởng tử Khâm làm hoàng thái tử, lấy con gái trưởng của Hưng Đạo Vương làm phi cho thái tử.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 47.916666666666664


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  19%|█▉        | 57/300 [01:42<04:56,  1.22s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.625


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.92929292929293


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.43434343434344


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.97979797979798


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.97979797979798


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.753246753246756


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.47474747474747


Đại Việt Sử Ký Toàn Thư
[155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.596858638743456


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.92929292929293


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.43434343434344


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.97979797979798


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.97979797979798


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.753246753246756


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.47474747474747


Đại Việt Sử Ký Toàn Thư
[155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.95959595959596


Đại Việt Sử Ký Toàn Thư
[155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.96969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.97979797979798


Đại Việt Sử Ký Toàn Thư
[154]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.97979797979798


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.47474747474747


Đại Việt Sử Ký Toàn Thư
[155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.64542936288089


Đại Việt Sử Ký Toàn Thư
[155]
Ất Hợi, [Bảo Phù] năm thứ 3 [1275]... Mùa xuân, tháng 2, mở khoa thi chọn học trò. Ban đỗ trạng nguyên Đào Tiêu ; bảng nhãn (khuyết họ tên); thám hoa lang Quách Nhẫn ; thái học sinh 27 người, xuất thân có thứ bậc khác nhau.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.47474747474747


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  19%|█▉        | 58/300 [01:43<05:35,  1.39s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 38.79598662207358


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.87179487179487


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.360902255639104


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.07692307692307


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.794871794871796


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.87179487179487


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.360902255639104


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.07692307692307


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.794871794871796


Đại Việt Sử Ký Toàn Thư
[155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.794871794871796


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.87179487179487


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[154]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.07692307692307


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.43589743589743


Đại Việt Sử Ký Toàn Thư
[155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.01754385964912


Đại Việt Sử Ký Toàn Thư
[155]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bính Tý, [Bảo Phù] năm thứ 4 [1276]... Mùa hạ, tháng 4, Nguyên Thế Tổ đánh Giang Nam, sai Hợp Tán Nhi Hải Nha 1 sang dụ 6 việc như điều dân, giúp quân v.v . . . Vua đều không nghe.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  20%|█▉        | 59/300 [01:44<05:02,  1.26s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.48366013071896


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.82352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.647058823529406


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.026315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.82352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.82352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.647058823529406


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.026315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.82352941176471


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.352941176470594


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.82352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.647058823529406


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.026315789473685


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.352941176470594


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.588235294117645


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đinh Sửu, [Bảo Phù] năm thứ 5 [1277]... Mùa hạ, tháng 4, ngày mồng 1 , Thượng hoàng băng ở cung Vạn Thọ... Mùa đông, tháng 10 ngày mồng 4, táng [thượng hoàng] ở Chiêu Lăng, miếu hiệu là Thái Tông.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  20%|██        | 60/300 [01:45<04:47,  1.20s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.924829157175395


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.93305439330544


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.981481481481474


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.29353233830846


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.02510460251046


Đại Việt Sử Ký Toàn Thư
[155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.188284518828446


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.924829157175395


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.93305439330544


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.981481481481474


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.29353233830846


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.02510460251046


Đại Việt Sử Ký Toàn Thư
[155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.60669456066946


Đại Việt Sử Ký Toàn Thư
[155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.69874476987448


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.69874476987448


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.02510460251046


Đại Việt Sử Ký Toàn Thư
[154]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.35146443514645


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.02510460251046


Đại Việt Sử Ký Toàn Thư
[155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.69874476987448


Đại Việt Sử Ký Toàn Thư
[155]
Hôm thượng hoàng băng, công chúa Thiều Dương (con gái thứ của Thượng hoàng tên là Thúy ) đương ở cữ, bỗng nghe tiếng chuông liên hồi... Những người hầu bên cạnh nói dối, nhưng công chúc chúa không nghe, cứ thương khóc, kêu gào, mắt nhắm nghiền rồi mất.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  20%|██        | 61/300 [01:49<07:24,  1.86s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.580777096114524


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.60093896713615


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.580777096114524


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.60093896713615


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.30612244897959


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.12244897959184


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.12244897959184


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.12244897959184


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Uy Văn Vương Toại lấy con gái của Thượng Hhàng là công chúa Thụy Bảo. Toại ham học, hay thơ... Vua từng hỏi ông nghĩa chữ "Quan gia". Ông đáp: "Năm đời đế lấy thiên hạ làm của công (quan), ba đời vương lấy thiên hạ làm của nhà (gia) nên gọi là quan gia".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  21%|██        | 62/300 [01:51<07:44,  1.95s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.643923240938165


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.213114754098356


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.46868250539957


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.29074889867841


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.4364640883978


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.80327868852459


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.213114754098356


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.46868250539957


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.29074889867841


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.4364640883978


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.889117043121146


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.29074889867841


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai điểm xem người nào đến chữa cháy và kiểm xem ai đến trước . Khung ấn đầu từng người một bảo ngồi xuống để đếm... Khung trả lời :" Thần ấn đầu người nào mà thấy mồ hôi thấm tóc và có tro bụi bám vào thì đó là những người đến trước và cố sức chữa".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  21%|██        | 63/300 [01:53<08:00,  2.03s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.27868852459016


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.018450184501845


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.30538922155688


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.20496894409938


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.10778443113772


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.50299401197605


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 51.49700598802396


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.30538922155688


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.20496894409938


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.10778443113772


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.50299401197605


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.694610778443106


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 55.68862275449102


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.20496894409938


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.10778443113772


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.694610778443106


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.70059880239521


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa đông, tháng 10, ngày 22, vua nhường ngôi cho hoàng thái tử Khâm. Khâm lên ngôi Hoàng đế, xưng là Hiếu Hoàng... NHÂN TÔNG HOÀNG ĐẾ Tên húy là Khâm, con trưởng của Thánh Tông.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  21%|██▏       | 64/300 [01:54<06:43,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.61702127659575


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.58757062146892


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.58757062146892


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.87234042553191

Mapping source_excerpt to chunks:  22%|██▏       | 65/300 [01:55<05:31,  1.41s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.58757062146892


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.93617021276596


Đại Việt Sử Ký Toàn Thư
[155]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[156]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[156]
Chiêm Thành sai Chế Năng, Tra Diệp sang cống. Bọn Chế Năng xin ở lại làm nội thần, vua không nhận.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.49586776859504


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.14285714285714


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.065693430656935


Đại Việt Sử Ký Toàn Thư
[155]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.54929577464789


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.14285714285714


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.065693430656935


Đại Việt Sử Ký Toàn Thư
[155]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[155]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Khi Nhật Duật trở về, Mật đem gia thuộc đến doanh trại đầu hàng. Mọi người đều vui lòng kính phục vì không mất một mũi tên mà bình được Đà Giang.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]

Mapping source_excerpt to chunks:  22%|██▏       | 66/300 [01:56<04:53,  1.25s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.924398625429546


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.52287581699346


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.790849673202615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.97047970479705


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.52287581699346


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.790849673202615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.97047970479705


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa hạ, tháng 4, bọn Trần Di Ái đi sứ về nước. Tháng 6, trị tội bọn phán thủ Trần Ải. Ải phải đồ làm khao giáp binh Thiên Trường, Lê Tuân phải đồ làm Tống binh.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư

Mapping source_excerpt to chunks:  22%|██▏       | 67/300 [01:57<04:30,  1.16s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.269841269841265


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.39941690962099


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.47311827956989


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.582043343653254


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.397849462365585


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.39941690962099


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.47311827956989


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.582043343653254


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.47311827956989


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.582043343653254


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.16129032258065


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hưng Đạo Vương Quốc Tuấn nghe thấy thế, tâu xin đến sứ quán xem Xuân làm gì. Lúc ấy Quốc Tuấn đã gọt tóc, mặc áo vải. Đến sứ quán, ông đi thẳng vào trong phòng. Xuân đứng dậy vái chào mời ngồi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  23%|██▎       | 68/300 [01:58<04:24,  1.14s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.80064308681673


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.5374149659864


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.95677233429395


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.782122905027926


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.89944134078212


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.95677233429395


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.782122905027926


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bấy giờ có cá sấu đến sông Lô [1]. Vua sai Hình bộ thượng thư Nguyễn Thuyên làm bài văn ném xuống sông, cá sấu bỏ đi. Vua cho việc này giống như việc của Hàn Dũ [2], bèn ban gọi là Hàn Thuyên.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  23%|██▎       | 69/300 [01:59<04:24,  1.14s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.12195121951219


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.50681198910081


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.3089430894309


Đại Việt Sử Ký Toàn Thư
[155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.12195121951219


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.50681198910081


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.3089430894309


Đại Việt Sử Ký Toàn Thư
[155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.52845528455285


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.12195121951219


Đại Việt Sử Ký Toàn Thư
[154]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.91525423728814


Đại Việt Sử Ký Toàn Thư
[155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[155]
Ít lâu sau xuống chiếu đoạt hết quan tước, quân tịch thu tài sản không để lại cho một chút gì. Châu Chí Linh vốn là của riêng của Thượng tướng Trần Phó Duyệt, nên Khánh Dư mới giữ lại được. Khánh Dư lui về ở Chí Linh, cùng bọn hèn hạ làm nghề bán than.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  23%|██▎       | 70/300 [02:02<07:07,  1.86s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.65573770491804


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.89944134078212


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.27129337539432


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.66480446927374


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.27129337539432


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.66480446927374


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[155, 156]
Lại khi ấy, vua thấy Hoài Văn Hầu Quốc Toản, Hoài Nhân Vương Kiện đều còn trẻ tuổi, không cho dự bàn. Quốc Toản trong lòng hổ thẹn, phẫn kích, tay cầm quả cam, bóp nát lúc nào không biết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  24%|██▎       | 71/300 [02:03<06:11,  1.62s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.12539184952978


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.40229885057471


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.85365853658537


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.25287356321839


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.40229885057471


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.85365853658537


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.25287356321839


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.29411764705882


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.40229885057471


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.29411764705882


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thượng hoàng triệu phụ lão trong nước họp ở thềm điện Diên Hồng, ban yến và hỏi kế đánh giặc. Các phụ lão điều nói "đánh", muôn người cùng hô một tiếng, như bật ra từ một cửa miệng.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  24%|██▍       | 72/300 [02:04<05:29,  1.45s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.76729559748428


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51207729468599


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.21608040201005


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.7860696517413


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.57971014492754


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.99516908212561


Đại Việt Sử Ký Toàn Thư
[155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.0363196125908


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51207729468599


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.21608040201005


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.7860696517413


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.57971014492754


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.99516908212561


Đại Việt Sử Ký Toàn Thư
[155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.0363196125908


Đại Việt Sử Ký Toàn Thư
[155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.37681159420289


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.961352657004824


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.89027431421446


Đại Việt Sử Ký Toàn Thư
[155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.37681159420289


Đại Việt Sử Ký Toàn Thư
[155]
Lúc đó, vua ngự thuyền nhẹ ra Hải Đông [4], chiều rồi mà vẫn chưa ăn cơm sáng. Có người lính là Trần Lai dâng cơm gạo xấu, vua khen là trung, ban cho chức thượng phẩm , kiêm chức tiểu tư xã xã Hữu Triều Môn ở Bạch Đằng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  24%|██▍       | 73/300 [02:06<05:55,  1.57s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 40.869565217391305


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.220338983050844


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.34968017057569


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.16222760290557


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.644067796610166


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.33898305084746


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.220338983050844


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.220338983050844


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.34968017057569


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.3728813559322


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.16222760290557


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.644067796610166


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.33898305084746


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.91525423728814


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.34968017057569


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.220338983050844


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.644067796610166


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.91525423728814


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Vũ Vương Nghiễn, Minh Hiến Vương Uất, Hưng Nhượng Vương Tảng, Hưng Trí Vương Hiện đốc suất 20 vạn quân các xứ Bàng Hà [8], Na Sầm [9], Trà Hương, Yên Sinh, Long Nhãn [10] đến hội ở Vạn Kiếp, theo quyền điều khiển của Hung Đạo Vương để chống quân Nguyên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  25%|██▍       | 74/300 [02:08<06:33,  1.74s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.44827586206896


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.068965517241374


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.15444015444015


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.13793103448276


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.068965517241374


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.44827586206896


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.068965517241374


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.15444015444015


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.13793103448276


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.490842490842496


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.75862068965517


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.44827586206896


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.13793103448276


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.75862068965517


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.44827586206896


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trước đây, Hưng Đạo Vương có người nô là Dã Tượngvà Yết Kiêu [11], đối xử rất hậu. Khi quân Nguyên tới, Yết Kiêu giữ thuyền ở Bãi Tân [12], Dã Tượng thì đi theo.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.


Mapping source_excerpt to chunks:  25%|██▌       | 75/300 [02:09<05:34,  1.49s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.16403785488959


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.233082706766915


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.02334630350194


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.796875


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.08416833667334


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.233082706766915


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.02334630350194


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.796875


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.72932330827067


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.233082706766915


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[155]
Vua muốn sai người dò xét tình hình giặc mà chưa tìm được ai. Chi hậu cục thủ Đỗ Khắc Chung tiến lên tâu rằng: "Thần hèn mọn bất tài, nhưng xin được đi". Vua mừng, nói rằng: "Ngờ đâu trong đám ngựa xe kéo xe muối lại có ngựa kỳ, ngựa ký như thế!"8 Rồi sai đem thư xin giảng hoà.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  25%|██▌       | 76/300 [02:12<06:20,  1.70s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.244224422442244


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.261904761904766


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.425076452599384


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.66473988439307


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.77456647398844


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.425076452599384


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.66473988439307


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.398843930635834


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.93063583815029


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.66473988439307


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.398843930635834


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.08670520231214


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 2, ngày Giáp Thìn mồng 1, con thứ của Tĩnh Quốc Đại Vương Quốc Khang là thượng vị Chương Hiến hầu [Trần] Kiện và liêu thuộc là bọn Lê Trắc đem cả quân đầu hàng quân Nguyên [4].
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  26%|██▌       | 77/300 [02:13<06:03,  1.63s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.910290237467024


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.364532019704434


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.7860696517413


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.112994350282484


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.33497536945813


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.910290237467024


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.364532019704434


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.7860696517413


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.112994350282484


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.33497536945813


Đại Việt Sử Ký Toàn Thư
[155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.812807881773395


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.320197044334975


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.355191256830594


Đại Việt Sử Ký Toàn Thư
[155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.812807881773395


Đại Việt Sử Ký Toàn Thư
[155]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.30541871921182


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bảo Nghĩa Vương Trần Bình Trọng (Vương là dòng dõi Lê Đại Hành, chồng sau của công chúa Thuỵ Bảo, ông cha làm quan đời Thái Tông, được ban quốc tính) đánh nhau với giặc ở bãi Đà Mạc, nay là bãi Mạn Trù) bị chết.

Mapping source_excerpt to chunks:  26%|██▌       | 78/300 [02:16<07:19,  1.98s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.99674267100977


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.16243654822335


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.6605504587156


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.2914798206278


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.69525959367946


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.70403587443946


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.97163120567376


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.497757847533634


Đại Việt Sử Ký Toàn Thư
[155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.600896860986545


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.16243654822335


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.6605504587156


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.2914798206278


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.69525959367946


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.70403587443946


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.97163120567376


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.497757847533634


Đại Việt Sử Ký Toàn Thư
[155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.04932735426009


Đại Việt Sử Ký Toàn Thư
[155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.94618834080718


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.39461883408071


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.2914798206278


Đại Việt Sử Ký Toàn Thư
[154]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.84304932735426


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.497757847533634


Đại Việt Sử Ký Toàn Thư
[155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.94618834080718


Đại Việt Sử Ký Toàn Thư
[155]
Kế đó, Chiêu Quốc Vương Trần Ích Tắc và bọn Phạm Cự Địa, Lê Diễn, Trịnh Long đem gia thuộc đầu hàng quân Nguyên... Đến nay, người Nguyên vào cướp, Ích Tắc xin hàng chúng để mong được làm vua. Người Nguyên phong làm An Nam Quốc Vương.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.

Mapping source_excerpt to chunks:  26%|██▋       | 79/300 [02:18<07:19,  1.99s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.57597173144877


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.07142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.047619047619044


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.07142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.047619047619044


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.29065743944637


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.047619047619044


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.047619047619044


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quan quân giao chiến với quân Nguyên ở Hàm Tử Quan [11]. Các quân đều có mặt. Riêng quân của Chiêu Văn Vương Nhật Duật có cả người Tống, mặc quần áo Tống, cầm cung tên chiến đấu.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  27%|██▋       | 80/300 [02:19<06:11,  1.69s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.891891891891895


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.97041420118343


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.19526627218935


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.20462046204621


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.37299035369775


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.97041420118343


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.19526627218935


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.20462046204621


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.37299035369775


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.928994082840234


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.74556213017751


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.74556213017751


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trước kia, nhà Tống mất, nhiều người Tống theo ta, Nhật Duật thu nạp họ, có Triệu Trung làm gia tướng. Cho nên chiến công đánh bại giặc Nguyên, Nhật Duật lập được nhiều hơn cả.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  27%|██▋       | 81/300 [02:20<05:26,  1.49s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.48727984344423


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.47787610619469


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.53537284894837


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.08658743633276


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.344709897610926


Đại Việt Sử Ký Toàn Thư
[155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.82776801405975


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.47787610619469


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.53537284894837


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.08658743633276


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.344709897610926


Đại Việt Sử Ký Toàn Thư
[155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[155]
Du binh giặc đến huyện Phù Ninh [5], viên phụ đạo huyện ấy là Hà Đặc lên núi Trĩ Sơn cố thủ. Giặc đóng ở động Cự Đà [6]. Hà Đặc lấy tre đan thành những hình người to lớn, cho mặc áo, cứ đến chiều tối thì dẫn ra dẫn vào. Lại dùi thủng cây to, cắm tên người lớn vào giữa lỗ để giặc ngờ là sức bắn khoẻ xuyên suốt được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;

Mapping source_excerpt to chunks:  27%|██▋       | 82/300 [02:22<06:36,  1.82s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.16634429400386


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.12539184952978


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.55844155844156


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.78014184397163


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.692789968652036


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.16216216216216


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.06583072100314


Đại Việt Sử Ký Toàn Thư
[155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.16417910447762


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.12539184952978


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.55844155844156


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.78014184397163


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.692789968652036


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.16216216216216


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.06583072100314


Đại Việt Sử Ký Toàn Thư
[155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 41.692789968652036


Đại Việt Sử Ký Toàn Thư
[155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.94670846394985


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.31974921630094


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.63322884012539


Đại Việt Sử Ký Toàn Thư
[154]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.692789968652036


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 41.06583072100314


Đại Việt Sử Ký Toàn Thư
[155]
Hôm đó, ta đánh bại giặc ở Tây Kết, giết và làm bị thương rất nhiều, chém đầu Nguyên Soái Toa Đô [8]. Vua trông thấy thủ cấp của Toa Đô, thương hại nói: "Người làm tôi phải nên như thế này". Rồi cởi áo ngự, sai quân đem liệm chôn, nhưng ngầm sai lấy đầu Toa Đô đem tẩm dầu để răn, vì cớ Toa Đô mượn đường vào cướp nước ta đã ba năm vậy.

Mapping source_excerpt to chunks:  28%|██▊       | 83/300 [02:25<07:38,  2.11s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.190669371196755


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.20255863539445


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.662100456621005


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.56862745098039


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.490196078431374


Đại Việt Sử Ký Toàn Thư
[155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.48496993987976


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.20255863539445


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.662100456621005


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.56862745098039


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.490196078431374


Đại Việt Sử Ký Toàn Thư
[155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.058350100603626


Đại Việt Sử Ký Toàn Thư
[155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.31372549019608


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.490196078431374


Đại Việt Sử Ký Toàn Thư
[155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.27450980392157


Đại Việt Sử Ký Toàn Thư
[155]
Thượng tướng Quang Khải, Hoài Văn Hầu Quốc Toản và Trần Thông, Nguyễn Khả Lạp cùng em là Nguyễn Truyền đem dân binh các lộ đánh bại quân giặc ở các xứ Kinh Thành, Chương Dương [3]. Quân giặc tan vỡ lớn. Bọn thái tử Thoát Hoan, Bình chương A Lạt rút chạy qua sông Lô [4].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.

Mapping source_excerpt to chunks:  28%|██▊       | 84/300 [02:29<09:14,  2.57s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.17460317460318


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.31182795698925


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.56824512534819


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.98507462686567


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.31182795698925


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.56824512534819


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.31182795698925


Đại Việt Sử Ký Toàn Thư
[154]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[155]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quan chấp chính xin bọn tráng đinh sung quân để tăng quân số lên nhiều. Trần Hưng Đạo nói :"Quân quý ở tinh nhuệ, không quý ở số đông. Dẫu đến 100 vạn quân mà như Bồ Kiên [5] thì cũng làm gì được?"
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  28%|██▊       | 85/300 [02:30<07:38,  2.13s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.56378600823045


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.22821576763485


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.88747346072187


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.7645788336933


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.509433962264154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.855967078189295


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.206008583690995


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.56378600823045


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.22821576763485


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.88747346072187


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.7645788336933


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.509433962264154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.855967078189295


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.26748971193416


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.188284518828446


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.26748971193416


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.79835390946503


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.855967078189295


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.26748971193416


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư liệu biết quân giặc đã qua, thuyền vận tải tất theo sau, nên thu thập tàn binh đợi chúng. Chẳng bao lâu thuyền vận tải quả nhiên đến, [Khánh Dư] đánh bại chúng, bắt được quân lương khí giới của giặc nhiều không kể xiết, tù binh cũng rất nhiều.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  29%|██▊       | 86/300 [02:32<07:42,  2.16s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.28767123287671


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.6973293768546


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.269841269841265


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.07772020725389


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.6973293768546


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.269841269841265


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.55958549222798


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.07772020725389


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.6973293768546


Đại Việt Sử Ký Toàn Thư
[154]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.55958549222798


Đại Việt Sử Ký Toàn Thư
[155]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.55958549222798


Đại Việt Sử Ký Toàn Thư
[155, 156]
Kháng Dư duyệt quân các trang, ra lệnh: "Quân trấn giữ Vân Đồn là để ngăn phòng giặc Hồ, không thể đội nón của phương Bắc, sợ khi vội vàng khó lòng phân biệt, nên đội nón Ma Lôi... ai trái tất phải phạt".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  29%|██▉       | 87/300 [02:34<07:10,  2.02s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.518518518518526


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.56756756756757


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.14814814814815


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.56756756756757


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.14814814814815


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.14814814814815


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.668393782383426


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.958333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.07407407407407


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[156]
Đinh Hợi, Trùng Hưng năm thứ 3 [1287]... Tháng 2, cá nhà táng chết cạn ở sông Bạch Đằng, dài 2 trượng 6 thước, dày 6 thước.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  29%|██▉       | 88/300 [02:35<05:50,  1.65s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.36569579288025


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.48148148148149


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.546498277841565


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.9553264604811


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.626168224299064


Đại Việt Sử Ký Toàn Thư
[155]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.90657439446367


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.340425531914896


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.48148148148149


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.546498277841565


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.9553264604811


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.626168224299064


Đại Việt Sử Ký Toàn Thư
[155]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.42342342342342


Đại Việt Sử Ký Toàn Thư
[155]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.80530973451327


Đại Việt Sử Ký Toàn Thư
[154]
Nước triều xuống, thuyền giặc vướng cọc hết. Nguyễn Khoái chỉ huy quân Thánh dực dũng nghĩa đánh nhau với giặc, bắt sống Bình chương Áo Lỗ Xích [4]. Hai vua đem quân tiếp đến, tung quân đánh lớn, quân Nguyên chết đuối nhiều không kể xiết, nước sông do vậy đỏ ngầu cả. Đến khi Văn Hổ tới quân mai phục hai bên bờ hăng hái xông ra đánh, , lại đánh bại chúng. Nước triều rút nhanh, thuyền lương của Văn Hổ mắc trên cọc, nghiêng đắm gần hết. Quân Nguyên chết đuối rất nhiều. Bắt được 400 chiếc thuyền. Nội Minh tự Đỗ Hành bắt được Ô Mã Nhi và Tích Lê Cơ Ngọc [5] dâng lên thượng hoàng [6].

Mapping source_excerpt to chunks:  30%|██▉       | 89/300 [02:47<17:07,  4.87s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.64383561643835


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.453608247422686


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.9381443298969


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.378151260504204


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.1948051948052


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.453608247422686


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.9381443298969


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.378151260504204


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.1948051948052


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.453608247422686


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.9381443298969


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.876288659793815


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.391752577319586


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa xuân, tháng 2, sai Nội thư Hoàng Tá Thốn đưa bọn Ô Mã Nhi về nước, dùng kế của Hưng Đạo Vương, lấy người giỏi bơi lặn, sung làm phu thuyền, ban đêm dùi thuyền cho đắm, bọn Ô Mã Nhi đều chết đuối cả.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  30%|███       | 90/300 [02:49<13:43,  3.92s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.978003384094755


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.03105590062112


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.362292051756


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.7888198757764


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.39249146757679


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.252595155709336


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.61158432708688


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.03105590062112


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.362292051756


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.7888198757764


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.39249146757679


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.30434782608695


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.03105590062112


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.7888198757764


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.39249146757679


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ, Lê Tòng Giáo làm tả phụ, vốn bất hòa với Hàn kâm phụng chỉ Đinh Củng Viên. Ngày tuyên đọc lời vua đã đến rồi mà Củng Viên vẫn cố ý không đưa bản thảo. Tòng Giáo đòi nhiều lần vẫn không được. Hôm ấy, xa giá sắp ra ngoài cung, Củng Viên mới đưa bản thảo. Tòng Giáo tuyên đọc tờ chiếu đại xá, không hiểu âm nghĩa, phải im lặng.

Mapping source_excerpt to chunks:  30%|███       | 91/300 [02:53<14:05,  4.05s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 51.04166666666667


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.875


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.88757396449704


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.958333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 51.04166666666667


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.875


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.88757396449704


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.958333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 53.125


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.04166666666667


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.958333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 53.125


Đại Việt Sử Ký Toàn Thư
[155]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.958333333333336


Đại Việt Sử Ký Toàn Thư
[156]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 47.916666666666664


Đại Việt Sử Ký Toàn Thư
[156]
Mù thu, tháng 9, phu nhân Hưng Đạo Vương Nguyên từ quốc mẫu Trần thị (tức công chúa Thiên Thành) mất.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 48.958333333333336

Mapping source_excerpt to chunks:  31%|███       | 92/300 [02:54<11:08,  3.21s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 48.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.54545454545455


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.54545454545455


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72727272727273


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.54545454545455


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.54545454545455


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72727272727273


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.27272727272728


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.27272727272728


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 52.727272727272734


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[156]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 48.18181818181818


Đại Việt Sử Ký Toàn Thư
[156]
Đỗ Hành chỉ được phong Quan nội hầu, vì khi bắt được Ô Mã Nhi không dâng lên quan gia [1], lại dâng lên Thượng hoàng.

Mapping source_excerpt to chunks:  31%|███       | 93/300 [02:56<08:57,  2.60s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.51145038167938


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.43891402714932


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.51145038167938


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.95744680851064


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.221374045801525


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.43891402714932


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.51145038167938


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.95744680851064


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.221374045801525


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.038167938931295


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.56488549618321


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.038167938931295


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.95744680851064


Đại Việt Sử Ký Toàn Thư
[154]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.27480916030534


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.56488549618321


Đại Việt Sử Ký Toàn Thư
[155]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.85496183206107


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.038167938931295


Đại Việt Sử Ký Toàn Thư
[156]
Hưng Trí Vương không được thăng trật, vì đã có chiếu cho người Nguyên về nước, các tướng không được cản trở, mà lại còn đón đánh chúng.

Mapping source_excerpt to chunks:  31%|███▏      | 94/300 [02:56<07:09,  2.09s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.59585492227979


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.34975369458128


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.19138755980861


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.34975369458128


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.19138755980861


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.27272727272728


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.63636363636364


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.18181818181818


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.36363636363636


Đại Việt Sử Ký Toàn Thư
[156]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 44.54545454545455


Đại Việt Sử Ký Toàn Thư
[156]
Đến khi giặc thua bắt được cả một hòm biểu xin hàng. Thượng hoàng sai đốt hết đi để yên lòng những kẻ phản trắc.

Mapping source_excerpt to chunks:  32%|███▏      | 95/300 [02:57<05:50,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.80874316939891


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.77777777777778


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.355191256830594


Đại Việt Sử Ký Toàn Thư
[155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.80874316939891


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.77777777777778


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.355191256830594


Đại Việt Sử Ký Toàn Thư
[155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.355191256830594


Đại Việt Sử Ký Toàn Thư
[155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.80874316939891


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.355191256830594


Đại Việt Sử Ký Toàn Thư
[155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[155]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.496815286624205


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua thân đi đánh Ai Lao. Triều thần can rằng: "Giặc Hồ vùa rút, vết thương chưa lành, đâu đã có thể dấy binh đao!". Vua nói: "Chỉ có thể lúc này ra quân thôi... cho nên phải cất quân lớn để thị uy".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  32%|███▏      | 96/300 [02:58<05:13,  1.54s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.577060931899645


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.875346260387815


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.55828220858896


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.76744186046512


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.875346260387815


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.55828220858896


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.340425531914896


Đại Việt Sử Ký Toàn Thư
[155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.27659574468085


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.340425531914896


Đại Việt Sử Ký Toàn Thư
[155]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[155, 156]
Xuống chiếu cho những mua dân lương thiện làm nô tỳ thì phải cho chuộc lại; ruộng đất, nhà cửa không theo luật này. Vì là nạn đói hai năm Canh Dần và Tân Mão, nhiều người chết, [nên có chiếu này].
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  32%|███▏      | 97/300 [03:00<04:46,  1.41s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.090146750524106


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.891891891891895


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.12896405919662


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.409207161125316


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.41245136186771


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.090146750524106


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.891891891891895


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.12896405919662


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.409207161125316


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.13618677042801


Đại Việt Sử Ký Toàn Thư
[155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.190661478599225


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.190661478599225


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.12896405919662


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.13618677042801


Đại Việt Sử Ký Toàn Thư
[155]
Đại Phạp trả lời" "Việc đời đổi thay, Đại Phạp trước vốn là tên biên chép cho Chiêu Đạo Vương, nay là sứ giả, cũng như Bình chương xưa kia là con vua, nay lại là người đầu hàng giặc". Ích Tắc có vẻ hổ thẹn. Từ đấy về sau, sứ ta đến, hắn không còn ngồi ở tỉnh đường nữa.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.

Mapping source_excerpt to chunks:  33%|███▎      | 98/300 [03:02<05:26,  1.62s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.465753424657535


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.872180451127825


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.05479452054795


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.0565371024735


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.872180451127825


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.05479452054795


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.0565371024735


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.29545454545454


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.872180451127825


Đại Việt Sử Ký Toàn Thư
[154]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.05479452054795


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.477351916376314


Đại Việt Sử Ký Toàn Thư
[155]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 52.84090909090908


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quý Tỵ, [Trùng Hưng] năm thứ 9 [1293], (từ tháng 3 trở đi là Anh Tông Hưng Long năm thứ 1, Nguyên Chí Nguyên năm thứ 30). Mùa xuân, tháng 3, ngày mồng 9, vua nhường ngôi cho Hoàng thái tử Thuyên.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  33%|███▎      | 99/300 [03:03<04:50,  1.45s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.26241134751773


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.97163120567376


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.17670682730924


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.26241134751773


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.97163120567376


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.09929078014184


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.09929078014184


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.80152671755725


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[156]
Thái hậu nghĩ không khỏi bị hại, mới lấy chiếc chiếu che cho Thượng hoàng và tự che mình. Hổ lên lầu gầm rống rồi nhảy xuống không vồ hại ai cả.

Mapping source_excerpt to chunks:  33%|███▎      | 100/300 [03:04<04:18,  1.29s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.246231155778894


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 56.315789473684205


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.36585365853658


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.18362282878412


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.8780487804878


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.43902439024391


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.547314578005114


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.26829268292683


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 56.315789473684205


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.36585365853658


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.18362282878412


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.8780487804878


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.43902439024391


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.547314578005114


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 55.60975609756098


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.36585365853658


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.80487804878049


Đại Việt Sử Ký Toàn Thư
[155, 156]
Kỷ Nhà Trần Anh Tông Hoàng Đế Tên là Thuyên, con trưởng Nhân Tông, mẹ là Khâm Từ Bảo Thánh hoàng thái hậu, ở ngôi 21 năm, nhường ngôi 6 năm, thọ 45 tuổi, băng ở cung Trùng Quang, phủ Thiên Trường, táng ở Thái Lăng.

Mapping source_excerpt to chunks:  34%|███▎      | 101/300 [03:05<04:49,  1.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.2


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.599999999999994


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.2


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 51.2


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.4


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.2


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 57.60000000000001


Đại Việt Sử Ký Toàn Thư
[156]
Giáp Ngọ, Hưng Long năm thứ 2 [1294]... Mùa thu, tháng 7, ngày mồng 3, Thượng tướng thái sư Chiêu Minh Đại Vương Quang Khải mất, thọ 54 tuổi.

Mapping source_excerpt to chunks:  34%|███▍      | 102/300 [03:07<04:48,  1.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.39482200647249


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.218798151001536


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.50704225352112


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.5


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.33807266982622


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.94463667820069


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.218798151001536


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.50704225352112


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.5


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.33807266982622


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.225352112676056


Đại Việt Sử Ký Toàn Thư
[155]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.225352112676056


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[154]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.50704225352112


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước kia, Thánh Tông thân đi đánh giặc, Quang Khải theo hầu, ghế tể tướng bỏ không, vừa lúc có sứ phương Bắc đến. Thái Tông gọi Hưng Đạo Vương Quốc Tuấn tới bảo: "Thượng tướng đi theo hầu vắng, trẫm định lấy khanh làm Tư đồ để tiếp sứ phương Bắc". Quốc Tuấn trả lời: "Việc tiếp sứ giả, thần không dám từ chối, còn như phong thần làm Tư đồ thì thần không dám vâng chiếu."

Mapping source_excerpt to chunks:  34%|███▍      | 103/300 [03:12<08:25,  2.57s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.70616113744076


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.85185185185186


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.601941747572816


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.518518518518526


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.85185185185186


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.601941747572816


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.85185185185186


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.601941747572816


Đại Việt Sử Ký Toàn Thư
[154]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.29629629629629


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.14814814814815


Đại Việt Sử Ký Toàn Thư
[156]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.07843137254902


Đại Việt Sử Ký Toàn Thư
[156]
Tháng giêng năm năm sau, nguyên Thế Tổ băng. [Nguyên] Thành Tông [3] lên ngôi, xuống chiếu bãi binh, thả Tử Kỳ về nước.

Mapping source_excerpt to chunks:  35%|███▍      | 104/300 [03:13<06:38,  2.03s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.52249134948097


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.59861591695502


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.0958904109589


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.252595155709336


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.52249134948097


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.59861591695502


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.0958904109589


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.252595155709336


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.90909090909091


Đại Việt Sử Ký Toàn Thư
[155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.59861591695502


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.86851211072664


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.63667820069204


Đại Việt Sử Ký Toàn Thư
[154]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.252595155709336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.94463667820069


Đại Việt Sử Ký Toàn Thư
[155]
Một hôm, Quốc Tuấn từ Vạn Kiếp tới, Quang Khải xuống thuyền chơi suốt ngày mới trở về. Lại Quang Khải vốn sợ tắm gội, Quốc Tuấn thì thích tắm thơm, từng đùa bảo Quang Khải: "Mình mẩy cáo bẩn, xin tắm giùm", rồi cởi áo Quang Khải ra, dùng nước thơm tắm cho ông và nói: "Hôm nay được tắm cho Thượng tướng".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  35%|███▌      | 105/300 [03:15<07:03,  2.17s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.006269592476485


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.69005847953217


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.916913946587535


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.69005847953217


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.76608187134503


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.69005847953217


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.916913946587535


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.69005847953217


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.76608187134503


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.27485380116959


Đại Việt Sử Ký Toàn Thư
[155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.02923976608187


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.27485380116959


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.02923976608187


Đại Việt Sử Ký Toàn Thư
[155]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quang Khải ham học hay thơ, có Lạc đạo tập lưu hành ở đời. Con ông là Văn Túc Vương Đạo Tái cũng nổi tiếng về văn học thời đó, được Thượng hoàng ưu ái hơn các em thúc bá khác.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.

Mapping source_excerpt to chunks:  35%|███▌      | 106/300 [03:16<05:57,  1.84s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.417910447761194


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.20289855072463


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.67353951890034


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.99288256227758


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.539906103286384


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.991212653778554


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.20289855072463


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.67353951890034


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.99288256227758


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.539906103286384


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.67353951890034


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.619217081850536


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.986254295532646


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.67353951890034


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.32871972318338


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, Thượng hoàng đích thân đi đánh Ai Lao, bắt được người và súc vật nhiều không kể xiết. Trong chiến dịch này, Trung Thành Vương (không rõ tên) làm tiên phong, bị quân Ai Lao bao vây, Phạm Ngũ Lão dẫn quân ập tới, giải vây, rồi tung quân nghênh chiến, đánh bại quân Ai Lao. Ban kim phù cho Ngũ Lão.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  36%|███▌      | 107/300 [03:19<06:35,  2.05s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.561983471074385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.51724137931034


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.388429752066116


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.18614718614719


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.561983471074385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.51724137931034


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.388429752066116


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.18614718614719


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.644067796610166


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.628099173553714


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, lấy Trần Thì Kiến làm Kiểm pháp quan, nhậm chức Đại an phủ Kinh sư. Thì Kiến tính người cương trực... Mỗi khi có kiện tụng, thì dùng lý lẽ mà bắt bẻ, việc đến thì tìm phương pháp để ứng phó. Người đời đều cho là giỏi xét đoán kiện tụng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  36%|███▌      | 108/300 [03:22<07:58,  2.49s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.09929078014184


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.5177304964539


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.09929078014184


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.5177304964539


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 49.64539007092199


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.5177304964539


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.39007092198582


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mậu Tuất, [Hưng Long] năm thứ 6 [1298]... Lấy Trần Thì Kiến làm Nhập nội hành khiển hữu gián nghị đại phu. Vua ban cho ông cái hốt có khắc bài minh ngự chế.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.22695035460993


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  36%|███▋      | 109/300 [03:23<06:25,  2.02s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.97222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.52249134948097


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.57534246575342


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.52249134948097


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.57534246575342


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.57534246575342


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[155, 156]
Kỷ Hợi, [Hưng Long] năm thứ 7 [1299]... Các các chữ Ngụy, Thấp, Nam, Càn, Tô, Tuấn, Anh, Tảng khi làm văn phải viết bớt nét. Nhà Trần kiêng tên huý họ ngoại bắt đầu từ đây.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.

Mapping source_excerpt to chunks:  37%|███▋      | 110/300 [03:24<05:25,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.23848238482385


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.07843137254902


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.647058823529406


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.96782841823056


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.7860696517413


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.07843137254902


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.07843137254902


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.647058823529406


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.96782841823056


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.7860696517413


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.07843137254902


Đại Việt Sử Ký Toàn Thư
[155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.549019607843135


Đại Việt Sử Ký Toàn Thư
[154]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.529411764705884


Đại Việt Sử Ký Toàn Thư
[155]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua từ Thiên Trường trở về [Kinh], phong Nhữ Hài làm Ngự sử trung tán. Bấy giờ có người ghen Nhữ Hài tuổi trẻ làm quan to, làm thơ chế giễu rằng: Phong hiến luận đàm truyền cổ ngữ, Khẩu tồn nhữ xú Đoàn trung tán.

Mapping source_excerpt to chunks:  37%|███▋      | 111/300 [03:26<05:31,  1.76s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.269841269841265


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.05263157894738


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.526170798898065


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.05263157894738


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.526170798898065


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.526170798898065


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[155]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quốc phụ có xăm hình rồng ở đùi, mà về sau nối ngôi không xăm ở đùi nữa là bắt đầu từ Anh Tông. Lại hồi quốc sơ, quân sĩ đều xăm hình rồng ở bụng, ở lưng và hai bắp đùi, gọi là "thái long" (rồng hoa).
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  37%|███▋      | 112/300 [03:27<04:55,  1.57s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.77215189873418


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.25842696629213


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.990654205607484


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.134831460674164


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.87915407854985


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.25842696629213


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.990654205607484


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.134831460674164


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.87915407854985


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.25842696629213


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[155]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua thích vi hành, cứ đêm đến, lại lên kiệu, cùng với hơn chục thị vệ đi khắp trong kinh kỳ, gà gáy mới trở về cung. Có đêm, ra đến quân phường, bị bọn vô lại ném gạch trúng vào đầu vua.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  38%|███▊      | 113/300 [03:29<04:28,  1.44s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.08510638297872


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.74393530997305


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.61702127659575


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.21276595744681


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.74393530997305


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.61702127659575


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.21276595744681


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.21276595744681


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.808510638297875


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.35820895522388


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 3 nhuận, Trần Quốc Khang chết. Quốc Khang từng cai trị Diễn Châu, chọn con gái đẹp trong châu làm vợ lẽ nàng hầu, nên các con thứ như Huệ Nghĩa, Quốc Trinh đều do các bà Diễn Châu sinh ra.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  38%|███▊      | 114/300 [03:30<04:10,  1.34s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.223443223443226


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.76534296028881


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.41637010676157


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.65734265734265


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.38783269961977


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.76534296028881


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.41637010676157


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.65734265734265


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.38783269961977


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.951048951048946


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.65734265734265


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.951048951048946


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.55244755244755


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[156]
Mùa thu, tháng 8, ngày 20, Hưng Đạo Vương Quốc Tuấn mất ở phủ đệ Vạn Kiếp, được tặng Thái sư thượng phụ thượng quốc công Nhân Vũ Hưng Đạo Đại Vương.

Mapping source_excerpt to chunks:  38%|███▊      | 115/300 [03:31<03:45,  1.22s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.128113879003564


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.57894736842105


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.03669724770643


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.57894736842105


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.799472295514505


Đại Việt Sử Ký Toàn Thư
[155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155, 156]
Lại một hôm Quốc Tuấn đem chuyện ấy hỏi người con thứ là Hưng Nhượng Vương Quốc Tảng. Quốc Tảng tiến lên thưa: "Tống Thái Tổ vốn là một ông lão làm ruộng, đã thừa cơ dấy vận nên có được thiên hạ".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  39%|███▊      | 116/300 [03:32<03:40,  1.20s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.816326530612244


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.91836734693877


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.08108108108108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 40.88397790055248


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.91836734693877


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.08108108108108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 40.88397790055248


Đại Việt Sử Ký Toàn Thư
[155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.91836734693877


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[155]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[156]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[156]
Quốc Tuấn từng soạn sách Binh gia diệu lý yếu lược để dạy các tỳ tướng, dụ họ rằng bài hịch như sau
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 43.87755102040817

Mapping source_excerpt to chunks:  39%|███▉      | 117/300 [03:33<03:30,  1.15s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.93023255813954


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.604651162790695


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.76744186046512


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.604651162790695


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.604651162790695


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.93023255813954


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.604651162790695


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.76744186046512


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.604651162790695


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.604651162790695


Đại Việt Sử Ký Toàn Thư
[155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.76744186046512


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.93023255813954


Đại Việt Sử Ký Toàn Thư
[154]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.76744186046512


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.18604651162791


Đại Việt Sử Ký Toàn Thư
[155]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.76744186046512


Đại Việt Sử Ký Toàn Thư
[155, 156]
Khi sắp mất, ông dặn con rằng: Ta chết thì phải hỏa táng, lấy vật tròn đựng xương, bí mật chôn trong vườn An Lạc, rồi san đất và trồng cây như cũ, để người đời không biết chỗ nào
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  39%|███▉      | 118/300 [03:34<03:57,  1.30s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.75235109717868


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.10778443113772


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.51497005988024


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.10778443113772


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.51497005988024


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.91017964071856


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bọn Phạm Ngũ Lão, Trần Thì Kiến, Trương Hán Siêu, Phạm Lãm, Trịnh Dũ, Ngô Sĩ Thường, Nguyễn Thế Trực vốn là môn khách của ông, đều nổi tiếng thời đó về văn chương và chính sự
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.

Mapping source_excerpt to chunks:  40%|███▉      | 119/300 [03:36<04:14,  1.40s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.96296296296296


Đại Việt Sử Ký Toàn Thư
[155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[155]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155, 156]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[156]
Xem như khi Thánh Tông vờ bảo Quốc Tuấn rằng: "Thế giặc như vậy, ta phải hàng thôi". Quốc Tuấn trả lời: "[Bệ hạ] chém đầu tôi trước rồi hãy hàng".

Mapping source_excerpt to chunks:  40%|████      | 120/300 [03:37<03:48,  1.27s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.54929577464789


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 40.70796460176991


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.99134199134199


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.19642857142857


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.789473684210535


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.14209115281502


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.92035398230089


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.72294372294372


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.99134199134199


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.19642857142857


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.789473684210535


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.14209115281502


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.72294372294372


Đại Việt Sử Ký Toàn Thư
[155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.58874458874459


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.72294372294372


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.72294372294372


Đại Việt Sử Ký Toàn Thư
[154]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.207126948775056


Đại Việt Sử Ký Toàn Thư
[155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.58874458874459


Đại Việt Sử Ký Toàn Thư
[155]
Nay ta chọn binh pháp các nhà, soạn thành một quyển, gọi là Binh thư yếu lược. Các ngươi nếu biết chuyên tập tập sách, theo lời ta dạy bảo, thì trọn đời là tôi chủ, nhược bằng khinh bỏ sách này, trái lời ta dạy bảo, thì trọn đời là cừu thù.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  40%|████      | 121/300 [03:39<04:34,  1.53s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.534412955465584


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.90265486725663


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.72573839662447


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.220338983050844


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.12955465587044


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.12955465587044


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.93927125506073


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.19015659955258


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.90265486725663


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.72573839662447


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.220338983050844


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.12955465587044


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.12955465587044


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.93927125506073


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.582995951417004


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.582995951417004


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.534412955465584


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.12955465587044


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.12955465587044


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.582995951417004


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật coi là trách nhiệm của mình, chăm sóc, nuôi nấng, không khác gì con mình. Nhật Duật nghĩ rằng con trưởng của mình tên là Thánh An, con gái tên là Thánh Nô, mới đặt tên cho hoàng tử là Thánh Sinh, vì muốn [tên hoàng tử[ cũng giống với tên con mình.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  41%|████      | 122/300 [03:41<05:09,  1.74s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.29390681003584


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.717791411042946


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.239263803680984


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.717791411042946


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 49.079754601227


Đại Việt Sử Ký Toàn Thư
[155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.079754601227


Đại Việt Sử Ký Toàn Thư
[155]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.62576687116564


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ai Lao sang cướp Đà Giang, sai Phạm Ngũ Lão đi đánh, gặp quân giặc ở Mường Mai [6], giao chiến, bắt được rất nhiều. Phong Ngũ Lão làm Thân vệ đại tướng quân, ban cho quy phù.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.

Mapping source_excerpt to chunks:  41%|████      | 123/300 [03:42<04:30,  1.53s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.12738853503185


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.94117647058824


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.271186440677965


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.588235294117645


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.054054054054056


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.836120401337794


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 53.642384105960275


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 51.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.94117647058824


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.271186440677965


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.588235294117645


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.054054054054056


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.836120401337794


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 53.642384105960275


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 51.17647058823529


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 56.271186440677965


Đại Việt Sử Ký Toàn Thư
[154]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.054054054054056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 53.642384105960275


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.17647058823529


Đại Việt Sử Ký Toàn Thư
[155]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 53.529411764705884


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tân Sửu, [Hưng Long] năm thứ 9 [1301], (Nguyên Đại Đức năm thứ 5). Mùa xuân, tháng giêng, xuống chiếu rằng các quan văn võ đều đội mũ chữ đinh, thêm miếng lụa bọc tóc màu tía xen màu biếc.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  41%|████▏     | 124/300 [03:43<04:04,  1.39s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.29390681003584


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.00000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.40282685512368


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.446366782006926


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.205479452054796


Đại Việt Sử Ký Toàn Thư
[155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.40282685512368


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.446366782006926


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.205479452054796


Đại Việt Sử Ký Toàn Thư
[155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[155]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155, 156]
Sau này, đi sứ Chiêm Thành, không lạy chúa Chiêm là bắt đầu từ Nhữ Hài. Khi về nước, vua rất khen ngợi ông và quyết ý dùng vào chức to, cho nên có lệnh này.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  42%|████▏     | 125/300 [03:45<03:43,  1.28s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.45283018867924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.69565217391304


Đại Việt Sử Ký Toàn Thư
[156]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[156]
Tháng 3, thi kẻ sĩ trong nước. Ban cho trạng nguyên. Mạc Đĩnh Chi chức Thái học sinh hỏa dũng thủ, sung làm nội thư gia

Mapping source_excerpt to chunks:  42%|████▏     | 126/300 [03:45<03:21,  1.16s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.36363636363636


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.29616724738676


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.69747899159664


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.17687074829932


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.69747899159664


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.17687074829932


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.098976109215016


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[156]
Thượng hoàng cho rằng họ Phí từ xưa không thấy có, mới đổi làm họ Bùi, cái tên Mộc Lạc là điềm chẳng lành, mới đổi thành Mộc Đạc, sai theo hầu ngày đêm.

Mapping source_excerpt to chunks:  42%|████▏     | 127/300 [03:47<03:21,  1.16s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 50.76142131979695


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.04932735426009


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.34782608695652


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 51.304347826086946


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.04932735426009


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.34782608695652


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.304347826086946


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.08695652173913


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.95652173913043


Đại Việt Sử Ký Toàn Thư
[156]
Nguyễn Trung Ngạn đỗ hoàng giáp; tất cả 44 người đỗ thái học sinh... Trung Ngạn mới 16 tuổi, đương thời gọi là thần đồng.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  43%|████▎     | 128/300 [03:48<03:28,  1.21s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.61073825503355


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.242424242424235


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.90909090909091


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.16438356164384


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.849315068493155


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.829268292682926


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 54.0


Đại Việt Sử Ký Toàn Thư
[155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 55.15151515151515


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.90909090909091


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.16438356164384


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.849315068493155


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.829268292682926


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 54.0


Đại Việt Sử Ký Toàn Thư
[155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 55.15151515151515


Đại Việt Sử Ký Toàn Thư
[155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.727272727272734


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.90909090909091


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 56.16438356164384


Đại Việt Sử Ký Toàn Thư
[154]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 56.849315068493155


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 54.0


Đại Việt Sử Ký Toàn Thư
[155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 56.42857142857143


Đại Việt Sử Ký Toàn Thư
[155]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 53.93939393939393


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ất Tỵ, [Hưng Long] năm thứ 13 [1305], (Nguyên Đại Đức năm thứ 9). Mùa xuân, tháng giêng, sách phong hoàng tử thứ tư là Mạnh làm Đông cung thái tử, (vua) làm bài Dược thạch châm [1] ban cho.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  43%|████▎     | 129/300 [03:50<03:47,  1.33s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.91338582677165


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.881889763779526


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.30708661417323


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.881889763779526


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.375586854460096


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.7007874015748


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.30708661417323


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.09448818897638


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.91338582677165


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.881889763779526


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.30708661417323


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.881889763779526


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.375586854460096


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.7007874015748


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.30708661417323


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.2755905511811


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.09448818897638


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.669291338582674


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.881889763779526


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.7007874015748


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.2755905511811


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, Chiêm Thành sai Chế Bồ Đài và bộ đảng hơn trăm người dâng hiến vàng bạc, hương quý, vật lạ làm lễ vật cầu hôn. Các quan trong triều đều cho là không nên, duy có Văn Túc Vương Đạo Tái chủ trương bàn việc đó, Trần Khắc Chung tán thành, việc bàn mới quyết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  43%|████▎     | 130/300 [03:52<04:54,  1.73s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.19419237749547


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.5129740518962


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.05594405594405


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.93785310734464


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.223443223443226


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.77879341864717


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.5129740518962


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.05594405594405


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.93785310734464


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.223443223443226


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.8041958041958


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.05594405594405


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.70629370629371


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.05594405594405


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.223443223443226


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ có viên độc bạ là Trần Cụ tính khoan hậu, cẩn thận, thật thà... Cụ người Cứu Liên, vốn có mối hận với Cứu Liên, thề rằng chân không giẫm lên đất ấy nữa. Sau này trở về Cứu Liên thì đi thuyền, đến khi lên bộ thì đi kiệu vào cửa, tới giường mới xuống kiệu, thức ngủ, ăn uống đều ở trên giường.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  44%|████▎     | 131/300 [03:55<05:28,  1.94s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.933810375670845


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.83985765124555


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.91187739463601


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.35946462715105


Đại Việt Sử Ký Toàn Thư
[155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.51005484460695


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.933810375670845


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.83985765124555


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.91187739463601


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.35946462715105


Đại Việt Sử Ký Toàn Thư
[155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.83985765124555


Đại Việt Sử Ký Toàn Thư
[155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.48398576512456


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.41637010676157


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.83985765124555


Đại Việt Sử Ký Toàn Thư
[154]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.195729537366546


Đại Việt Sử Ký Toàn Thư
[155]
Sai Nhập nội hành khiển thượng thư tả bộc xạ Trần Khắc Chung, An phủ Đặng Văn sang Chiêm Thành đón công chúa Huyền Trân và thế tử Đa Da về... Khắc Chung dùng thuyền nhẹ cướp lấy công chúa đem về, rồi tư thông với công chúa, đi đường biển loanh quanh chậm chạp, lâu ngày mới về đến kinh đô.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.83985765124555



Mapping source_excerpt to chunks:  44%|████▍     | 132/300 [03:57<06:00,  2.15s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.523809523809526


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.523809523809526


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.42857142857142


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 50.476190476190474


Đại Việt Sử Ký Toàn Thư
[156]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[156]
Mùa thu, tháng 11, ngày mồng 1, mặt trời có hai quầng. Ngày mồng 3, Thượng hoàng băng ở am Ngọa Vân núi Yên Tử.

Mapping source_excerpt to chunks:  44%|████▍     | 133/300 [03:58<04:51,  1.75s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.49659863945578


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.76245210727969


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 39.5112016293279


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.36125654450262


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.6829268292683


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.76245210727969


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 39.5112016293279


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.36125654450262


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.42105263157895


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.061302681992345


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Nay trong bức trướng của tể tướng lại thêu cành trúc với chim sẽ. Trúc là bậc quân tử, chim sẽ là kẻ tiểu nhân. Tể tướng thêu như vậy là để tiểu nhân trên quân tử, sợ rằng đạo của tiểu nhân sẽ mạnh, đạo của quân tử sẽ suy. Tôi vì thánh triều mà trừ giúp bọn tiểu nhân.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.

Mapping source_excerpt to chunks:  45%|████▍     | 134/300 [04:00<05:11,  1.87s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.515151515151516


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 59.29203539823009


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 58.57740585774059


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.077253218884124


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 58.33333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 56.060606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.484848484848484


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.515151515151516


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 59.29203539823009


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 58.57740585774059


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.077253218884124


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 58.33333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 56.060606060606055


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 53.78787878787878


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 51.515151515151516


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 59.29203539823009


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 58.57740585774059


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 58.33333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 59.166666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 57.57575757575757


Đại Việt Sử Ký Toàn Thư
[155, 156]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 58.33333333333333


Đại Việt Sử Ký Toàn Thư
[156]
Kỷ Dậu, [Hưng Long] năm thứ 17 [1309], (Nguyên Chí Đại năm thứ 2). Mùa xuân, tháng giêng, đại xá. Sách phong Đông cung thái tử Mạnh làm Hoàng thái tử.

Mapping source_excerpt to chunks:  45%|████▌     | 135/300 [04:02<04:43,  1.72s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.705882352941174


Đại Việt Sử Ký Toàn Thư
[156]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[156]
Thứ phi của vua là Phạm thị, là con gái Phạm Ngũ Lão, không có con, xin xuất gia, vua cho.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 54.117647058823536

Mapping source_excerpt to chunks:  45%|████▌     | 136/300 [04:03<04:14,  1.55s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 47.5


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.56451612903226


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.9244060475162


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.559718969555036


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.7004048582996


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.96551724137932


Đại Việt Sử Ký Toàn Thư
[155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.83266932270916


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.56451612903226


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.9244060475162


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.559718969555036


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.7004048582996


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.96551724137932


Đại Việt Sử Ký Toàn Thư
[155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.426294820717125


Đại Việt Sử Ký Toàn Thư
[155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.426294820717125


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.418326693227094


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.82470119521913


Đại Việt Sử Ký Toàn Thư
[154]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.82470119521913


Đại Việt Sử Ký Toàn Thư
[155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.426294820717125


Đại Việt Sử Ký Toàn Thư
[155]
Trọng Tử lo dọc đường thế nào cũng có chỗ cao thấp quanh co, nếu nghiêm túc im lặng, thì sợ có sự nghiêng lệch, nếu truyền gọi bảo ban thì lại e ồn ào, bèn đem những lời dặn về cách đi đứng dàn hàng, phổ vào khúc hát Long Ngâm, sai người hát lên để bảo nhau.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  46%|████▌     | 137/300 [04:06<05:21,  1.97s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.86617100371747


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.606516290726816


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.627450980392155


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.192307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.269230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.542787286063565


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.3420365535248


Đại Việt Sử Ký Toàn Thư
[155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.627450980392155


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.192307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.269230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.542787286063565


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.3420365535248


Đại Việt Sử Ký Toàn Thư
[155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.230769230769226


Đại Việt Sử Ký Toàn Thư
[155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.71153846153846


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.632768361581924


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.192307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.269230769230774


Đại Việt Sử Ký Toàn Thư
[154, 155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.3420365535248


Đại Việt Sử Ký Toàn Thư
[155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.71153846153846


Đại Việt Sử Ký Toàn Thư
[155]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.71153846153846


Đại Việt Sử Ký Toàn Thư
[155, 156]
Xá lỵ của Nhân Tông đưa cất vào bảo tháp, có sư Trí Thông phụng hầu. Trước đây, khi Nhân Tông xuất gia, sư chùa Siêu Loại là Trí Thông tự đốt cánh tay mình, từ bàn tay đến tận khuỷu tay, vẫn ung dung không biến sắc.

Mapping source_excerpt to chunks:  46%|████▌     | 138/300 [04:08<05:17,  1.96s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.73504273504274


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.66019417475729


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.880341880341874


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 49.13793103448276


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.73504273504274


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.66019417475729


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.880341880341874


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 49.13793103448276


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.299145299145295


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.42268041237113


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.299145299145295


Đại Việt Sử Ký Toàn Thư
[156]
Mùa hạ, tháng 5, dụ bắt được chúa Chiêm Thành Chế Chí đem về; phong em hắn là Chế Đà A Bà Niêm làm Á hầu trấn giữ đất ấy.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  46%|████▋     | 139/300 [04:09<04:24,  1.65s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.22310756972112


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154, 155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.74329501915708


Đại Việt Sử Ký Toàn Thư
[155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.17687074829932


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.22310756972112


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154, 155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.74329501915708


Đại Việt Sử Ký Toàn Thư
[155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21487603305785


Đại Việt Sử Ký Toàn Thư
[154]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154, 155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.74329501915708


Đại Việt Sử Ký Toàn Thư
[155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.97701149425287


Đại Việt Sử Ký Toàn Thư
[155]
Minh Hiến Vương Uất (con út của Thái Tông) ở trong doanh trại, bàn tán biện bác, mê hoặc lòng quaân. Vua giận, đuổi ra khỏi dinh, lệnh cho các quân không được thu nhận. Minh Hiến bèn cùng vài mươi gia đồng ngủ ở ngoài nội. Phạm Ngũ Lão nghe tin ấy vội mời vào trong quân
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.

Mapping source_excerpt to chunks:  47%|████▋     | 140/300 [04:11<04:49,  1.81s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.01294498381877


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.94202898550725


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.78378378378378


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.13145539906104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.28832630098453


Đại Việt Sử Ký Toàn Thư
[155]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.314500941619585


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.432432432432435


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.94202898550725


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.78378378378378


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.13145539906104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.28832630098453


Đại Việt Sử Ký Toàn Thư
[155]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.17180616740088


Đại Việt Sử Ký Toàn Thư
[155]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.32432432432433


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.78378378378378


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.054054054054056


Đại Việt Sử Ký Toàn Thư
[154]
Lập đền thờ thần ở cửa biển Cần Hải [3]. Trước đây, vua đi đánh Chiêm Thành, đến cửa biển Cần Hải (trước là Càn, tránh tên huý đổi là Cần), đóng quân lại, đêm nằm mơ thấy một thần nữ khóc lóc nói với vua: "Thiếp là cung phi nhà Triệu Tống, bị giặc bức bách, gặp phải sóng gió, trôi giạt đến đây. Thượng đế phong thiếp làm thần biển đã lâu. Nay bệ hạ mang quân đi, thiếp xin giúp đỡ lập công".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.78378378378378


Đại Việt Sử Ký Toàn Thư
[154, 155]

Mapping source_excerpt to chunks:  47%|████▋     | 141/300 [04:16<07:48,  2.95s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.41811846689895


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.23711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.508710801393725


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.710526315789465


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.23711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.508710801393725


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.056603773584904


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.76315789473685


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.05263157894737


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.056603773584904


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.68421052631579


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa đông, tháng 10, duyệt định Vũ quân, đổi quân Vũ tiệp thành quân Thiết ngạch, lấy Đại liêu ban Trần Thanh Ly làm Vũ vệ đại tướng quân thống lĩnh quân này.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 52.63157894736843


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  47%|████▋     | 142/300 [04:18<06:39,  2.53s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.19850187265918


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.94250513347022


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.220588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.13375796178344


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.476635514018696


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.826291079812215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.987854251012145


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.92307692307692


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.94250513347022


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.220588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.13375796178344


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.80155642023347


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.476635514018696


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.826291079812215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.987854251012145


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.529411764705884


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.79411764705882


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.220588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.13375796178344


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.476635514018696


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 48.987854251012145


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Hưng Long] năm thứ 22 [124], (từ tháng 3 trở đi là Đại Khánh năm thứ 1, Nguyên Diên Hựu năm thứ 1). Mùa xuân, tháng 3, sắc cho Trung thư ban tên húy của bản triều, thêm các tên húy của Ninh Hoàng và của hai thái hậu Tuyên Từ, Bảo Từ [2]. Ngày 18, vua nhường ngôi cho hoàng thái tử Mạnh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  48%|████▊     | 143/300 [04:20<06:23,  2.44s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.40127388535032


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.58385093167702


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.83044982698962


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.270270270270274


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.58385093167702


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.83044982698962


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.270270270270274


Đại Việt Sử Ký Toàn Thư
[155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.58385093167702


Đại Việt Sử Ký Toàn Thư
[154]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.00638977635783


Đại Việt Sử Ký Toàn Thư
[155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[155]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua mặc áo tràng vạt bằng là màu vàng, đội mũ có thao, sứ giả khen vua là "thanh thoát như thần tiên". Đến khi về nước, [sứ giả] thường nói đến vẻ người thanh tú của vua.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.

Mapping source_excerpt to chunks:  48%|████▊     | 144/300 [04:21<05:14,  2.02s/it]

Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.57768052516411


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 55.53047404063205


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.35680751173709


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.73858921161826


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.21608040201005


Đại Việt Sử Ký Toàn Thư
[154, 155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.643153526970956


Đại Việt Sử Ký Toàn Thư
[155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.96073903002309


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.37759336099585


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 55.53047404063205


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.35680751173709


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.73858921161826


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.21608040201005


Đại Việt Sử Ký Toàn Thư
[154, 155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.643153526970956


Đại Việt Sử Ký Toàn Thư
[155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.47899159663865


Đại Việt Sử Ký Toàn Thư
[155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.37759336099585


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.69709543568465


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.717842323651446


Đại Việt Sử Ký Toàn Thư
[154]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154, 155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.643153526970956


Đại Việt Sử Ký Toàn Thư
[155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.37759336099585


Đại Việt Sử Ký Toàn Thư
[155]
MINH TÔNG HOÀNG ĐẾ Tên húy là Mạnh, con thứ tư của Anh Tông, mẹ đích là Thuận Thánh Bảo Từ hoàng thái hậu Trần thị, con gái của Hưng Nhượng Đại Vương Quốc Tảng, mẹ sinh là Chiêu Hiến hoàng thái hậu Trần thị, con gái của Bảo Nghĩa Vương Bình Trọng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.

Mapping source_excerpt to chunks:  48%|████▊     | 145/300 [04:23<05:20,  2.07s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.282685512367486


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 53.37423312883436


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.063492063492056


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.318042813455655


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.09034267912773


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 51.19047619047619


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 53.37423312883436


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 52.063492063492056


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.318042813455655


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.09034267912773


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 51.19047619047619


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 53.37423312883436


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.063492063492056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 51.09034267912773


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.359516616314195


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 55.35714285714286


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ất Mão, [Đại Khánh] năm thứ 2 [1315], (Nguyên Diên Hựu năm thứ 2). Mùa hạ, tháng 4, ngày mồng 7, đua thuyền. Tháng 5, xuống chiếu cấm cha con, vợ chồng và gia nô không được tố cáo lẫn nhau.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  49%|████▊     | 146/300 [04:24<04:32,  1.77s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.26415094339623


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.132075471698116


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.15094339622642


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.08196721311475


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.66144814090019


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.32553606237816


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.132075471698116


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.15094339622642


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.08196721311475


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.66144814090019


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.0188679245283


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.15094339622642


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.77358490566038


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.77358490566038


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.15094339622642


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trần Khắc Chung làm Hành khiển. Quan ngự sử dâng sớ nói: "Chức vụ tể tướng, trước hết phải điều hoà âm dương. Nay Khắc Chung ở ngôi tể tướng, không biết phối hợp đất trời cho khí tiết điều hòa, để đến nỗi mưa nắng trái thời, thế là làm quan không được công trạng gì".

Mapping source_excerpt to chunks:  49%|████▉     | 147/300 [04:27<04:52,  1.91s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.644067796610166


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.04545454545454


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.04545454545454


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.560606060606055


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[155]
Sử thần Ngô Sĩ Liên nói: Vua vốn nhân hậu với họ hàng, nhất là đối với bậc bề trên mà hiển quý lại càng tôn kính. Kẻ thần hạ hễ ai cùng tên (với họ hàng nhà vua) đều phải đổi cả... [Vua] có quyển sổ nhỏ biên những chữ húy không được nói đến, trao cho các hoàng tử và cung phi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  49%|████▉     | 148/300 [04:29<05:31,  2.18s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.66310160427807


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.98930481283422


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.953216374269005


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.24598930481284


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.98930481283422


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.66310160427807


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.98930481283422


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.953216374269005


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.24598930481284


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.98930481283422


Đại Việt Sử Ký Toàn Thư
[155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.865951742627345


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.19786096256684


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.98930481283422


Đại Việt Sử Ký Toàn Thư
[154]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.26737967914438


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.40540540540541


Đại Việt Sử Ký Toàn Thư
[155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.865951742627345


Đại Việt Sử Ký Toàn Thư
[155]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bính là cận thần của Thượng hoàng, tính người trong sạch thẳng thắn, năm trước đứng đầu hành nhân sang sứ nước Nguyên, trở về không mua thứ gì, Thượng hoàng khen ngợi, đặc cách ban thưởng 2 tư.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  50%|████▉     | 149/300 [04:31<05:09,  2.05s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.0976430976431


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.91845493562232


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.269230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.91845493562232


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.77682403433476


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.34763948497854


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.232227488151665


Đại Việt Sử Ký Toàn Thư
[154, 155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.91845493562232


Đại Việt Sử Ký Toàn Thư
[155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.63519313304721


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.34763948497854


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.269230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.91845493562232


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.77682403433476


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.34763948497854


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.232227488151665


Đại Việt Sử Ký Toàn Thư
[154, 155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.91845493562232


Đại Việt Sử Ký Toàn Thư
[155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.63519313304721


Đại Việt Sử Ký Toàn Thư
[155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.493562231759654


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.206008583690995


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.77682403433476


Đại Việt Sử Ký Toàn Thư
[154]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.34763948497854


Đại Việt Sử Ký Toàn Thư
[154, 155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.59550561797752


Đại Việt Sử Ký Toàn Thư
[155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.922746781115876


Đại Việt Sử Ký Toàn Thư
[155]
Có người khai là bắt được một tên cướp, giải lên nộp quan và bảo nó là Văn Khánh. Đến lúc tra hỏi, tên ấy nhận ngay, ai cũng cho là thực, duy có mỗi Trực vẫn ngờ... Một tháng sau, Văn Khánh quả nhiên bị bắt. Thượng hoàng do đó khen Trực có tài.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  50%|█████     | 150/300 [04:34<05:20,  2.13s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.95774647887324


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.5820895522388


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.5820895522388


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[155]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.896551724137936


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quản Thiên võ quân Phạm Ngũ Lão tung quân đánh phía sau giặc. Quân giặc thua chạy, bắt được rất nhiều. Phong Ngũ Lão tước Quan nội hầu, ban cho phi ngư phù và cho con ông làm quan.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  50%|█████     | 151/300 [04:35<04:31,  1.82s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.05555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.0188679245283


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.147157190635454


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.22648752399232


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.214285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.68627450980392


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.14381270903011


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.0188679245283


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.147157190635454


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.22648752399232


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.214285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.68627450980392


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.14381270903011


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.812709030100336


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.97986577181208


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.812709030100336


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.147157190635454


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.80936454849499


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.14381270903011


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng tính tình khiêm tốn hoà nhã, hoà mục với người trong họ, mọi việc của triều đình đều tự mình quyết đoán. Khi thư rỗi trong muôn việc bận, Thượng hoàng để tâm tới việc trước thuật. Nhưng viết được gì, vẽ được gì, ngài đều đốt cả. Tập thơ ngự chế tên là Thủy vân tùy bút, trước khi mất, cũng đốt đi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;

Mapping source_excerpt to chunks:  51%|█████     | 152/300 [04:37<05:04,  2.06s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.318681318681314


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.162393162393165


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.26877470355731


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.492440604751614


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.24505928853755


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.43661971830986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.37623762376238


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.77510040160642


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.873517786561266


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.162393162393165


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.26877470355731


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.492440604751614


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.24505928853755


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.43661971830986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.37623762376238


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.873517786561266


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.873517786561266


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.873517786561266


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.24505928853755


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.29249011857708


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.873517786561266


Đại Việt Sử Ký Toàn Thư
[155]
Nguyễn Sĩ Cố, Chu Bộ là cận thần của thái tử. Đến khi thái tử lên ngôi. Cố và Bộ đều vì không có đức hạnh nên đều không được cất nhắc. Cố làm đến Thiên chương các học sĩ, chức này thực đặt làm vì, chứ không có quyền hành gì. Bộ thì chỉ coi mấy bộ cấm binh Khôi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  51%|█████     | 153/300 [04:40<05:16,  2.15s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.592592592592595


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.65390505359877


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.068965517241374


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.577030812324935


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72300469483567


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.29691876750701


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.36741767764298


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.65390505359877


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.068965517241374


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.577030812324935


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72300469483567


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.29691876750701


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.89772727272727


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.577030812324935


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.577030812324935


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ rước linh cữu [thượng hoàng] đưa về Thiên Trường. Thuyền của Bảo Từ thái hậu có 8 dây kéo, thuyền của Huy Tư hoàng phi có 2 dây kéo. Người coi cấm quan có ý nịnh vua, lấy dây buộc thêm vào thuyền của hoàng phi. Tướng quân Trần Hựu nói: "Thuyền của thái hậu có 8 dây kéo là quy chế của nhà Trần để tỏ rõ danh phận trên dưới", lập tước rút gươm cắt dây bỏ bớt đi.

Mapping source_excerpt to chunks:  51%|█████▏    | 154/300 [04:45<07:52,  3.24s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.26241134751773


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.301115241635685


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.301115241635685


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 11, Điện súy thượng tướng quân Phạm Ngũ Lão mất tại phũ đệ vua ban ở vườn cau trong thành, thọ 66 tuổi. Vua nghỉ chầu 5 ngày, đó là ân điển đặc biệt.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  52%|█████▏    | 155/300 [04:46<06:14,  2.58s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.01544401544402


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.738977072310405


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.933810375670845


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.36283185840708


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.24778761061947


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.608567208271786


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.219076005961256


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.29065743944637


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.24778761061947


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.933810375670845


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.36283185840708


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.24778761061947


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.608567208271786


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.219076005961256


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.72271386430678


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.54277286135693


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.24778761061947


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.83775811209439


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, Anh Tông không khoẻ, vua ngày đêm ơ luôn ngoài cửa phòng ngủ của Thượng hoàng, mỗi khi vào thăm thì cùng đi với Quốc Chẩn. Vì Anh Tông tin cậy Quốc Chẩn hơn cả, định đem vua gửi gắm Quốc Chẩn, cho nên không cho vào thăm một mình, mà phải cùng đi với Quốc Chẩn, cốt để cho tình nghĩa vua tôi được khăng khít và không còn nghi ngại gì nữa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.067846607669615


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  52%|█████▏    | 156/300 [04:50<07:15,  3.02s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.007194244604314


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.975903614457835


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.78074866310161


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.919786096256686


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.6551724137931


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.85026737967914


Đại Việt Sử Ký Toàn Thư
[155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.78074866310161


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.919786096256686


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.6551724137931


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.85026737967914


Đại Việt Sử Ký Toàn Thư
[155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.524064171122994


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.919786096256686


Đại Việt Sử Ký Toàn Thư
[154]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thái học sinh Đặng Tảo thường xuyên đứng hầu bên giường ngự để viết di chiếu. Anh Tông băng, vua đích thân khâm liệm. Chỉ có Quốc phụ cùng Tảo và gia nhi chủ nô là Lê Chung tham gia việc này.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  52%|█████▏    | 157/300 [04:52<05:52,  2.47s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.02564102564102


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.764705882352935


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.12149532710281


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.764705882352935


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.529411764705884


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.12149532710281


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.23529411764705


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.470588235294116


Đại Việt Sử Ký Toàn Thư
[155, 156]
Sau này Nghệ Hoàng đến Yên Sinh, tưởng nhớ hai người bề tôi đó, liền sai Trần An trùng tu chùa cũ của Tảo và Chung, lại cấp ruộng để thờ cúng, ban tên chùa là chùa Trung Tiết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.

Mapping source_excerpt to chunks:  53%|█████▎    | 158/300 [04:53<04:51,  2.05s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.53312302839116


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57478005865103


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.01769911504425


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.20123839009288


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57478005865103


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.01769911504425


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.20123839009288


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.01769911504425


Đại Việt Sử Ký Toàn Thư
[154]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[155]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[155, 156]
Có tên Mặc trong quân Thiên thuộc ở Hoàng Giang đỗ khoa thi Thái học sinh, vua xuống chiếu bắt trở lại quân ngũ, làm quân lại quân Thiên đinh, đến khi thi đánh gậy, [Mặc] lại đỗ cao.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  53%|█████▎    | 159/300 [04:54<04:11,  1.78s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.79835390946503


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[154]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154, 155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[155]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[155, 156]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[156]
Vua sai Thị ngự sử Nguyễn Trung Ngạn ra đón. Trung Ngạn lấy lẽ bẻ lại, Hợp Mưu đuối lý, phải xuống ngựa bưng chiếu đi bộ. Vua rất hài lòng.

Mapping source_excerpt to chunks:  53%|█████▎    | 160/300 [04:55<03:35,  1.54s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.80701754385965


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.273764258555126


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.390977443609025


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.59259259259259


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 53.74149659863945


Đại Việt Sử Ký Toàn Thư
[155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 52.38095238095239


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.273764258555126


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 56.390977443609025


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.59259259259259


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 53.74149659863945


Đại Việt Sử Ký Toàn Thư
[155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 52.38095238095239


Đại Việt Sử Ký Toàn Thư
[155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.578231292517


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 56.273764258555126


Đại Việt Sử Ký Toàn Thư
[154]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 56.390977443609025


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 53.74149659863945


Đại Việt Sử Ký Toàn Thư
[155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 55.01858736059479


Đại Việt Sử Ký Toàn Thư
[155]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 56.4625850340136


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ất Sửu, [Khai Thái] năm thứ 2 [1325], (Nguyên Thái Định năm thứ 2). Mùa xuân, đặt ty Liêm phỏng ở các lộ. Lấy Đặng Lộ làm Liêm phỏng sứ hai lộ Đại Hoàng và An Tiêm.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:  54%|█████▎    | 161/300 [04:56<03:32,  1.53s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.61702127659575


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.82687338501292


Đại Việt Sử Ký Toàn Thư
[154, 155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.82687338501292


Đại Việt Sử Ký Toàn Thư
[154, 155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.90721649484536


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.81443298969072


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[154]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.845360824742265


Đại Việt Sử Ký Toàn Thư
[154, 155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.36082474226804


Đại Việt Sử Ký Toàn Thư
[155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.90721649484536


Đại Việt Sử Ký Toàn Thư
[155]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.876288659793815


Đại Việt Sử Ký Toàn Thư
[155, 156]
Theo quy chế cũ, Hành khiển ty ở cung Quan Triều và Thánh Từ, cùng Nội thư hỏa cục thì gọi chung là Nội mật viện. Đến nay, đổi Hành khiển ty thành Môn hạ sảnh, còn Nội thư hỏa cục vẫn là Nội mật viện.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  54%|█████▍    | 162/300 [04:59<04:17,  1.86s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.29032258064517


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.93063583815029


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.27777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.19653179190751


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.92307692307692


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.61849710982659


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.93063583815029


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.27777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.19653179190751


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.92307692307692


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.93063583815029


Đại Việt Sử Ký Toàn Thư
[155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.92307692307692


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[155]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.50867052023122


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giáng Nguyễn Trung Ngạn làm An phủ sứ Thanh Hóa. Trung Ngạn có tính hay sơ xuất. Bấy giờ, Bảo Vũ Vương được ban tước Tạo y thượng vị hầu, Trung Ngạn ghi sổ, lại xếp vào hàng Tử y.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  54%|█████▍    | 163/300 [05:00<03:44,  1.64s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.005181347150256


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.932642487046635


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.266666666666666


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.86422976501305


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.96891191709845


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.005181347150256


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.932642487046635


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.266666666666666


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.86422976501305


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.005181347150256


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.04145077720207


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bấy giờ Trương Hán Siêu làm Hành khiển. Một hôm, Siêu nói trong triều rằng hình quan Phạm Ngộ và Lê Duy ăn hối lộ. Vua lập tức sai điều tra... Đến khi tra hỏi, Hán Siêu đuối lý phải phạt 300 quan tiền.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  55%|█████▍    | 164/300 [05:02<03:50,  1.69s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51700680272109


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.168658698539176


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.88961892247043


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.78074866310161


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.51497005988024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.774574049803405


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.593869731800766


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.998585572843


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.168658698539176


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.88961892247043


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.78074866310161


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.51497005988024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.774574049803405


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.13259668508287


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.529262086513995


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.00254452926209


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.529262086513995


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, sét đánh lăng tẩm. Quần thần bàn việc ấy. Xuống chiếu phạt bọn Thiếu bảo Trần Khắc Chung, Hành khiển Đoàn Nhữ Hài theo mức độ khác nhau. Sau hôm sét đánh, các quan họp bàn ở Nội nhân văn cục. Các vương hầu cùng giải lao với Trần Khắc Chung và Đoàn Nhữ Hài. Khắc Chung nói chuyện có giọng hài hước. Nhữ Hài vội đứng dậy bỏ đi. Khắc Chung nói xong mọi người đều cười, bị quan Ngự sử hặc tội.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.


Mapping source_excerpt to chunks:  55%|█████▌    | 165/300 [05:07<06:23,  2.84s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.29896907216495


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.20603015075377


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.25806451612903


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.41245136186771


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.01197604790419


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.78260869565217


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.3931623931624


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.25806451612903


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.41245136186771


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.01197604790419


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.01197604790419


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.01197604790419


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 3, giết Quốc phụ thượng tể Quốc Chẩn... Cương Đông Văn Hiến hầu... đem 100 lạng vàng đút lót cho gia thần của Quốc Chẩn là Trần Phẫu, bảo nó vu cáo Quốc Chẩn âm mưu phản loạn. Vua tin là thực, giam Quốc Chẩn ở chùa Tư Phúc rồi đem việc ấy hỏi Thiếu bảo Trần Khắc Chung... Vua mới cấm tuyệt không cho Quốc Chẩn ăn uống, bắt phải tự tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.41317365269462


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  55%|█████▌    | 166/300 [05:13<08:04,  3.61s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.7680250783699


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.7032967032967


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.95402298850575


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.25274725274725


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.05494505494505


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.7680250783699


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.7032967032967


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.95402298850575


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.25274725274725


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.54945054945055


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.802197802197796


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.7032967032967


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.25274725274725


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.54945054945055


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ngày 15, vua nhường ngôi, Vượng lên ngôi hoàng đế, đổi niên hiệu là Khai Hựu năm thứ 1. Đại xá. (Vua tự) xưng là Triết Hoàng, Tôn Thượng hoàng là Chương Nghiêu Văn Triết Thái Thượng Hoàng Đế.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  56%|█████▌    | 167/300 [05:14<06:22,  2.87s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.875


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.8849902534113


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.112828438949


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.9553264604811


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.43661971830986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.08955223880597


Đại Việt Sử Ký Toàn Thư
[155]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.94463667820069


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.737430167597765


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.112828438949


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.9553264604811


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.43661971830986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.08955223880597


Đại Việt Sử Ký Toàn Thư
[155]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[155]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.66412213740458


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.737430167597765


Đại Việt Sử Ký Toàn Thư
[154]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66812227074236


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái bảo Uy Túc Văn Bích nói: "Xét bàn nhân vật để dạy hoàng tử, chỉ nên nhắc tới người thiện, còn kẻ ác hãy bỏ chớ bàn đến, sợ các hoàng tử nghe được, có thể sẽ có người bắt chước". Thượng hoàng nói: "Thiện ác đều phải nêu để đối chiếu, không thể bỏ một bên nào. Nếu con ta quả là hiền, thì nghe điều thiện tất phải theo mà học tập, nghe điều ác tất phải ghét mà tránh xa".

Mapping source_excerpt to chunks:  56%|█████▌    | 168/300 [05:19<07:28,  3.40s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.18181818181819


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.430830039525695


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.94007490636704


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.430830039525695


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.94007490636704


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.430830039525695


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.28571428571429


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 50.71428571428571


Đại Việt Sử Ký Toàn Thư
[156]
Mùa đông, Thượng hoàng đi tuần thú đạo Đà Giang, đích thân đi đánh man Ngưu Hống, sai Thiêm tri Nguyễn Trung Ngạn đi theo để biên soạn thực lục.

Mapping source_excerpt to chunks:  56%|█████▋    | 169/300 [05:20<05:50,  2.67s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.135188866799204


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.935779816513765


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.92857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.13145539906104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.81338742393509


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.07116104868914


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.935779816513765


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.92857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.13145539906104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.81338742393509


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.64609800362977


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.785714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung can rằng: "Đà Giang vốn có tiếng là đất lam chướng, lại nhiều ghềnh thác chảy xiết, không lợi cho việc hành quân. Chiêm Thành không có lam chướng, khí độc, vả lại đế vương đời trước thân chinh, nhiều lần bắt được chúa nó. Chi bằng bỏ Ngưu Hống đấy mà đánh ChiêmThành là hơn."
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  57%|█████▋    | 170/300 [05:22<05:37,  2.60s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.23107569721115


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.23107569721115


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.96774193548387


Đại Việt Sử Ký Toàn Thư
[155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.76119402985075


Đại Việt Sử Ký Toàn Thư
[155]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.52238805970149


Đại Việt Sử Ký Toàn Thư
[155, 156]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[156]
Chiêu Nghĩa hầuj tới Chiêm Chiêu, muốn tâng công, tấn công trại, bị thua. Tuyên uy tướng quân Vũ Tư Hoằng liều sức chiến đấu, chết tại trận.

Mapping source_excerpt to chunks:  57%|█████▋    | 171/300 [05:23<04:48,  2.24s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.0348162475822


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.921875


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.982698961937714


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.694200351493855


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.94463667820069


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.40540540540541


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.0348162475822


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.921875


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.982698961937714


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.694200351493855


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.94463667820069


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.40540540540541


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.020761245674734


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.674740484429066


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.694200351493855


Đại Việt Sử Ký Toàn Thư
[154]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.21739130434783


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.79717813051146


Đại Việt Sử Ký Toàn Thư
[155]
Sau này Hưng Hiếu Vương đi đánh man Đà Giang, đỗ thuyền trên sông Bạch Hạc, đêm thấy thần báo mộng rằng: "Năm trước vua có lệnh khen thưởng mà đến nay vẫn chưa thấy gì". Hưng Hiếu Vương về tâu lại, Thượng hoàng bèn phong thêm cho hai chữ: Quỷ thần thiêng liêng, ứng nghiệm, quả không sai là ngoa vậy.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  57%|█████▋    | 172/300 [05:27<05:29,  2.57s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.692307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 57.65765765765766


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.76902887139107


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.98976982097187


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.83561643835616


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.3469387755102


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.95918367346938


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 57.65765765765766


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.76902887139107


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.98976982097187


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.83561643835616


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.3469387755102


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.93877551020408


Đại Việt Sử Ký Toàn Thư
[155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.97959183673469


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 55.10204081632652


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.95918367346938


Đại Việt Sử Ký Toàn Thư
[154]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.38775510204081


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.97959183673469


Đại Việt Sử Ký Toàn Thư
[155]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.97959183673469


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hiến Tông Hoàng Đế Tên húy là Vượng, con thứ của Minh Tông, mẹ đích là Hiến Từ tuyên thánh hoàng thái hậu, mẹ sinh là Minh Từ hoàng thái phi Lê thị. Ở ngôi 13 năm, thọ 23 tuổi, băng táng ở lăng Xương An.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  58%|█████▊    | 173/300 [05:29<04:56,  2.33s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.860465116279066


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.61538461538461


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.53846153846153


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154, 155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.61538461538461


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.53846153846153


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154, 155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154, 155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.07692307692308


Đại Việt Sử Ký Toàn Thư
[155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[155]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[155, 156]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[156]
Từ khi rước linh cữu Anh Tông về Yên Sinh, mọi điều khổ hạnh, bữa cháo, bữa chay, không việc gì bà không làm... Bà ở núi mười năm rồi mất.

Mapping source_excerpt to chunks:  58%|█████▊    | 174/300 [05:30<04:01,  1.92s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.22873900293255


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.07650273224044


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.02325581395349


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.22873900293255


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.63157894736842


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.07650273224044


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.684210526315795


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.30386740331491


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhật Duật thích chơi với người nước ngoài... Nếu là khách Tống thì ông kéo ghế ngồi gần, chuyện trò suốt buổi, nếu là người Chiêm hay người các man khác, thì đều theo phong tục nước họ mà tiếp đãi.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  58%|█████▊    | 175/300 [05:31<03:34,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.41414141414141


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.97082228116711


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.92929292929293


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.145833333333336


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.8989898989899


Đại Việt Sử Ký Toàn Thư
[154, 155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.97082228116711


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.92929292929293


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.145833333333336


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.8989898989899


Đại Việt Sử Ký Toàn Thư
[154, 155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.43434343434344


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.92929292929293


Đại Việt Sử Ký Toàn Thư
[154]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.919191919191924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.67816091954023


Đại Việt Sử Ký Toàn Thư
[155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.791666666666664


Đại Việt Sử Ký Toàn Thư
[155, 156]
Anh Tông có hai chiếc mũ võ, là mũ đội khi duyệt và giảng võ mà chưa có tên gọi. Khi đi đánh Chiêm Thành, định đội đi, sai Nhật Duật đặt tên, Nhật Duật liền đặt tên một chiếc là Vũ Uy, một chiếc là Vũ Đức.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  59%|█████▊    | 176/300 [05:33<03:36,  1.75s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.98473282442748


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.76729559748428


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.40404040404041


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.76729559748428


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.40404040404041


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.65408805031446


Đại Việt Sử Ký Toàn Thư
[155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[155]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.79874213836478


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ông là người hòa nhã, độ lượng, mừng giận không lộ ra sắc mặt, trong nhà không bao giờ chứa roi vọt để đánh nô lệ. Nếu có đánh thì cũng kể tội lỗi sau rồi mới đánh.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:  59%|█████▉    | 177/300 [05:34<03:09,  1.54s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.05479452054795


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.05479452054795


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[154]
Trần Khắc Chung chết, tặng chức Thiếu sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[155]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 56.41025641025641


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 56.41025641025641


Đại Việt Sử Ký Toàn Thư
[156]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 48.71794871794872


Đại Việt Sử Ký Toàn Thư
[156]
Trần Khắc Chung chết, tặng chức Thiếu sư.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 53.84615384615385

Mapping source_excerpt to chunks:  59%|█████▉    | 178/300 [05:34<02:36,  1.28s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.694493783303734


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.147157190635454


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.84858044164039


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.27767354596624


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.53312302839116


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.3931484502447


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.291592128801426


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.84858044164039


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.147157190635454


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.84858044164039


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.27767354596624


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.53312302839116


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.3931484502447


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.84858044164039


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.16403785488959


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.479495268138805


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.03361344537815


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.53312302839116


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.84858044164039


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng lại hỏi rằng: "Nếu sang năm trở đi, ta chắc chắn không chết, thì hoãn việc chôn mẫu hậu cũng được; nếu sang năm ta chết, thì lo xong việc chôn cất mẫu hậu chẳng hơn là chết mà chưa lo được việc đó ư? Lễ cát lễ hung phải chọn ngày là vì coi trọng việc đó thôi, chứ đâu có phải câu nệ họa phúc như các nhà âm dương."

Mapping source_excerpt to chunks:  60%|█████▉    | 179/300 [05:38<03:51,  1.91s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.13636363636363


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.060606060606055


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.13636363636363


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[156]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[156]
Mùa thu, tháng 7 lấy Nguyễn Trung Ngạn làm Tri thẩm hình viện sự, kiêm An phủ sứ Thanh Hóa.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 44.31818181818182

Mapping source_excerpt to chunks:  60%|██████    | 180/300 [05:39<03:21,  1.68s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 38.538205980066444


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.29268292682927


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[155]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đến ngày giao chiến, mây mù che tối, giặc đã phục sẵn voi ngựa, hai mặt giáp công, quan quân thua to, sa xuống nước chết đuối đến quá nửa. Nhữ Hài cũng ở trong số người chết đuối đó.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  60%|██████    | 181/300 [05:40<03:12,  1.62s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.033112582781456


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.85990338164251


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.410628019323674


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.410628019323674


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.6015037593985


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.893719806763286


Đại Việt Sử Ký Toàn Thư
[155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.50704225352112


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.85990338164251


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.410628019323674


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.410628019323674


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.93548387096774


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.6015037593985


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.893719806763286


Đại Việt Sử Ký Toàn Thư
[155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.85990338164251


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.410628019323674


Đại Việt Sử Ký Toàn Thư
[154]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.893719806763286


Đại Việt Sử Ký Toàn Thư
[155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[155]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.85990338164251


Đại Việt Sử Ký Toàn Thư
[155, 156]
Khi Thượng hoàng thân chinh thì Đỗ Thiên Hư chỉ huy quân Khoái Hộ (tức là quân Thần Sách) đang bị ốm nặng. [Thượng hoàng ] bảo ở lại Thiên Hư liền sai người nhà khiêng mình đến ngoài cửa Vĩnh An, cố xin theo xa giá

Mapping source_excerpt to chunks:  61%|██████    | 182/300 [05:42<03:22,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.18181818181819


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.25547445255474


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.0188679245283


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.559845559845556


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.652173913043484


Đại Việt Sử Ký Toàn Thư
[155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.37681159420289


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.927536231884055


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.25547445255474


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.0188679245283


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.559845559845556


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.652173913043484


Đại Việt Sử Ký Toàn Thư
[155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.37681159420289


Đại Việt Sử Ký Toàn Thư
[155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.10144927536232


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.10144927536232


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.25547445255474


Đại Việt Sử Ký Toàn Thư
[154]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.10144927536232


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.652173913043484


Đại Việt Sử Ký Toàn Thư
[155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.10144927536232


Đại Việt Sử Ký Toàn Thư
[155]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.10144927536232


Đại Việt Sử Ký Toàn Thư
[155, 156]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.37681159420289


Đại Việt Sử Ký Toàn Thư
[156]
Sai Hưng Hiếu Vương dẹp người man Ngưu Hống. [Hưng Hiếu Vương] tiến quân vào trại Trịnh Kỳ, đánh tan quân man, chém tù trưởng của họ là Xa Phần.

Mapping source_excerpt to chunks:  61%|██████    | 183/300 [05:43<02:54,  1.49s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.61370716510904


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.89944134078212


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.106145251396654


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.61370716510904


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.89944134078212


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.106145251396654


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.36871508379888


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.134078212290504


Đại Việt Sử Ký Toàn Thư
[154]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.89944134078212


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.36871508379888


Đại Việt Sử Ký Toàn Thư
[155]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155, 156]
Lấy Nguyễn Trung Ngạn làm An phủ sứ Nghệ An, kiêm Quốc sử viện giám tu quốc sử, hành Khoái Châu lộ tào vận sứ Trung Ngạn kiến nghị lập tào thương chứa thóc tô để chẩn cấp dân bị đói.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  61%|██████▏   | 184/300 [05:44<02:42,  1.40s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.07894736842105


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.033112582781456


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.81605351170569


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.243902439024396


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.033112582781456


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.81605351170569


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.243902439024396


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.170731707317074


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.731707317073166


Đại Việt Sử Ký Toàn Thư
[154]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.34146341463414


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.170731707317074


Đại Việt Sử Ký Toàn Thư
[155]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trong chiến dịch này, gia đồng của Hưng Hiếu là Phạm Ngải có lập chiến công, Thượng hoàng nói: "Gia nô tuy có chút công lao nhưng không được dự vào quan tước triều đình".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.

Mapping source_excerpt to chunks:  62%|██████▏   | 185/300 [05:46<02:30,  1.31s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.122676579925646


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.257383966244724


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.52532833020638


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.35680751173709


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.237918215613384


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.86617100371747


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.122676579925646


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.257383966244724


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.52532833020638


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.35680751173709


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.237918215613384


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.840148698884754


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.98141263940521


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.86617100371747


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.257383966244724


Đại Việt Sử Ký Toàn Thư
[154]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154, 155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.237918215613384


Đại Việt Sử Ký Toàn Thư
[155]
Kỷ Mão, [Khai Hựu] năm thứ 11[1339], (Nguyên Chí Nguyên năm thứ 5). Mùa xuân, đổi tên lịch Thụ thành lịch Hiệp kỷ. Khi ấy, Hậu nghi lang thái sử cục lệnh là Đặng Lộ cho rằng lịch các đời trước đều gọi là lịch Thụ thì, xin đổi tên thành lịch Thụ thì, xin đổi thành lịch Hiệp kỷ. Vua y theo.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.


Mapping source_excerpt to chunks:  62%|██████▏   | 186/300 [05:48<03:03,  1.61s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.137614678899084


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.884488448844884


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.49376114081996


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.40727902946274


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.13145539906104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.565217391304344


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.55445544554455


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.884488448844884


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.49376114081996


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.40727902946274


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.13145539906104


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.20462046204621


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.1947194719472


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.54455445544554


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.21452145214522


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.884488448844884


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.224422442244226


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng đón hoàng tử Hạo lên ngôi Hoàng đế, đổi niên hiệu là Thiệu Phong năm thứ 1. Đại xá. [ Vua ] tự xưng là Dụ Hoàng. Các quan dâng tôn hiệu là Thống Thiên Thể Đạo Nhân Minh Quang Hiếu Hoàng Đế. Vua lúc ấy mới lên 6 tuổi. [Thượng hoàng ] không lập con trưởng là Cung Túc Vương Dục, Vì [Dục] là người ngông cuồng.

Mapping source_excerpt to chunks:  62%|██████▏   | 187/300 [05:51<03:42,  1.97s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.80327868852459


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.02277039848197


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.599277978339344


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.14587332053743


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.123711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.509433962264154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.4043321299639


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.91338582677165


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.321299638989174


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.02277039848197


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.599277978339344


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.14587332053743


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.123711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.509433962264154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.4043321299639


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.04332129963899


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.4043321299639


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.682310469314075


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.76534296028881


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.123711340206185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.4043321299639


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ngự đến Ngự sử đài. Giám sát ngự sử Doãn Định và Nguyễn Như Vi bị bãi chức... [Hai người] bèn làm sớ kháng nghị, nói là Thượng hoàng không được vào Ngự sử đài và hặc tội Lê Duy không biết can ngăn, lời lẽ rất gay gắt. Vua dụ họ hai, ba lần cũng không được, bèn bị bãi chức cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.4043321299639



Mapping source_excerpt to chunks:  63%|██████▎   | 188/300 [05:54<04:29,  2.41s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.87179487179487


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.56410256410257


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 53.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.15447154471545


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.87179487179487


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.56410256410257


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 53.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.15447154471545


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 53.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.56410256410257


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.84615384615385


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 53.84615384615385


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 51.28205128205128


Đại Việt Sử Ký Toàn Thư
[156]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[156]
Mùa xuân, tháng 2, người Trà Hương [1] là Ngô Bệ họp bọn ở núi Yên Phụ [2] làm giặc cướp.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 47.43589743589743

Mapping source_excerpt to chunks:  63%|██████▎   | 189/300 [05:55<03:32,  1.92s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.35164835164834


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.35164835164834


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[156]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.0


Đại Việt Sử Ký Toàn Thư
[156]
Ngày 15 an táng Hiến Tông vào An Lăng ở Kiến Xương [3].
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 50.0

Mapping source_excerpt to chunks:  63%|██████▎   | 190/300 [05:56<02:51,  1.56s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.92156862745098


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.84100418410041


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.61538461538461


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.69260700389105


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.92156862745098


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.84100418410041


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.02788844621514


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.61538461538461


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.69260700389105


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.692307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.61538461538461


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.61538461538461


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.692307692307686


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.38461538461539


Đại Việt Sử Ký Toàn Thư
[156]
Mùa hạ, tháng 6 , Bảo Uy Vương Hiến có tội bị đuổi ra làm Phiêu kỵ tướng quân trấn Vọng Giang [1], rồi bị giết ở sông Vạn Nữ [2], lộ Trường Yên.

Mapping source_excerpt to chunks:  64%|██████▎   | 191/300 [05:57<02:31,  1.39s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.07352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.91176470588235


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.323651452282164


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.07352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.91176470588235


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.323651452282164


Đại Việt Sử Ký Toàn Thư
[155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.77456647398844


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.91176470588235


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.22310756972112


Đại Việt Sử Ký Toàn Thư
[155]
Đặt quan trấn, quan lộ vá sát hải sứ ở trấn Vân Đồn, lại đặt quân Bình Hải để trấn giữ. Trước đây, thời nhà Lý, thuyền buôn tới thì váo từ các cửa biển Tha, Viên [8] ở Châu Diễn. Đến nay, đường biển đổi dời, cửa biển nông cạn, thuyền buôn phần nhiều tụ tập ở Vân Đồn, cho nên có lệnh này.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  64%|██████▍   | 192/300 [05:59<03:03,  1.70s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.888888888888886


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.20603015075377


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.867924528301884


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.888888888888886


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.20603015075377


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.867924528301884


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.111111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.55555555555556


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.111111111111114


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, có người Nguyên là Đinh Bàng Đức, nhân nước có lọan, đem cả nhà đi thuyền vượt biển chạy sang ta. Bàng Đức giỏi leo dây, làm trò ca múa. Người nước ta bắt chước làm trò múa leo dây. Trò leo dây bắt đầu có từ đó.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.

Mapping source_excerpt to chunks:  64%|██████▍   | 193/300 [06:01<03:13,  1.81s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.45439469320066


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.313269493844054


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.990654205607484


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.01718213058419


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.228758169934636


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.69310793237972


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.63667820069204


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.313269493844054


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.990654205607484


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.01718213058419


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.228758169934636


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.69310793237972


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[155]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Bấy giờ Trâu Canh thấy vua bị liệt dương, dâng phương thuốc nói rằng giết đứa bé con trai, lấy mật hòa với dương khởi thạch mà uống và thông dâm với chị hay em ruột của mình thì sẽ hiệu nghiệm. Vua làm theo, thông dâm với chị ruột là công chúa Thiên Ninh, quả nhiên công hiệu. Canh liền thông dâm với cung nữ. Việc phát giác, Thượng hoàng địng bắt Canh chết, nhưng vì có công chữa khỏi bệnh cho vua nên được tha.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

Mapping source_excerpt to chunks:  65%|██████▍   | 194/300 [06:08<05:57,  3.37s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.038216560509554


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.76470588235294


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.89247311827957


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.23711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 51.546391752577314


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.71573604060914


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.59825327510917


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.55172413793104


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.76470588235294


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.89247311827957


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.23711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 51.546391752577314


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.71573604060914


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.59825327510917


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.490196078431374


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.27450980392157


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 49.89247311827957


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.546391752577314


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.59825327510917


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Thìn, [Thiệu Phong] năm thứ 12, [1352], (Nguyên Chí Chính năm thứ 12). Mùa xuân, tháng 3, Chế Mỗ người Chiêm Thành chạy sang ta, dâng voi trắng, ngựa trắng, mỗi thứ một con, một con kiến lớn (dài 1 thước 9 tấc) và các cống vật xin đánh Trà Hòa Bố Để mà lập y làm vương quốc.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.18181818181818


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  65%|██████▌   | 195/300 [06:11<05:25,  3.10s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 38.87147335423198


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.19526627218935


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.01183431952663


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.506493506493506


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.828402366863905


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.97041420118343


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.19526627218935


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.01183431952663


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.506493506493506


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.828402366863905


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.97041420118343


Đại Việt Sử Ký Toàn Thư
[155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.19526627218935


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[154]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.37869822485207


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.562130177514796


Đại Việt Sử Ký Toàn Thư
[155]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tả tham tri chính sự Trương Hán Siêu trấn giữ Hóa Châu, biên thùy trở lại yên ổn. Ông xin trở về triều, vua y cho, nhưng về chưa tới kinh sư thì chết, được truy tặng Thái bảo.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.

Mapping source_excerpt to chunks:  65%|██████▌   | 196/300 [06:12<04:21,  2.51s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.599277978339344


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.48286604361371


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.83985765124555


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.42586750788643


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31147540983606


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.047619047619044


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.48286604361371


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.83985765124555


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.42586750788643


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31147540983606


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.64285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.80952380952381


Đại Việt Sử Ký Toàn Thư
[155]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hán Siêu người Phúc Thành,[ huyện] Yên Ninh [1], [phủ] Trường Yên,là người chính trực, bài xích dị đoan, có tài văn chương và chính sự. Nhà vua chỉ gọi ông là thầy chứ không gọi tên.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  66%|██████▌   | 197/300 [06:13<03:35,  2.10s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.42105263157895


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.54385964912281


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.382716049382715


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.708542713567844


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.91943127962085


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.17906336088154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.004608294930875


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.42105263157895


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.54385964912281


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.382716049382715


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.708542713567844


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.91943127962085


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.17906336088154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.42105263157895


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 49.382716049382715


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.91943127962085


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.896551724137936


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mùi, [Thiệu Phong] năm thứ 15 [1355], (Nguyên Chí Chính năm thứ 15)... Lấy Nguyễn Trung Ngạn làm kinh lược sứ trấn Lạng Giang, Nhập nội đại hành khiển, thượng thư hữu bật, kiêm tri khu mật viện sự, thị kinh diên đại học sĩ, trụ quốc Khai Huyện bá.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  66%|██████▌   | 198/300 [06:15<03:36,  2.12s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.070460704607044


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.42857142857142


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.57894736842105


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.76190476190476


Đại Việt Sử Ký Toàn Thư
[155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.33249370277078


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.42857142857142


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.57894736842105


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.76190476190476


Đại Việt Sử Ký Toàn Thư
[155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.33249370277078


Đại Việt Sử Ký Toàn Thư
[155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.76190476190476


Đại Việt Sử Ký Toàn Thư
[155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[155]
Bà thứ phi của Anh Tông tên hiệu là Tĩnh Huệ, là con gái Điện súy Phạm Ngũ Lão, trước đã xuất gia... Thế rồi sữa lại chùa đó , lại làm điện ở phía bên đông chùa và làm nhà ở phía đằng sau để cúng lễ tổ tiên thần thánh.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.76190476190476


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  66%|██████▋   | 199/300 [06:17<03:32,  2.11s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.079365079365076


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.919786096256686


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.100840336134446


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.48916408668731


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.513966480446925


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.69121813031161


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 50.80213903743316


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.19774011299435


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.100840336134446


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.31550802139037


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.48916408668731


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.513966480446925


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.69121813031161


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 50.80213903743316


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.80213903743316


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.100840336134446


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.48916408668731


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.69121813031161


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.352941176470594


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.871657754010705


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đinh Dậu, [Thiệu Phong] năm thứ 7 [1357], ( Nguyên Chí Chính năm thứ 17). Mùa xuân, tháng 2, ngày 19, Thượng hoàng băng ở cung Bảo Nguyên, miếu hiệu là Minh Tông, tên thụy là Chương Nghiêu Văn Triết Hoàng Đế.

Mapping source_excerpt to chunks:  67%|██████▋   | 200/300 [06:19<03:18,  1.99s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.126074498567334


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.111111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.582043343653254


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.888888888888886


Đại Việt Sử Ký Toàn Thư
[155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.77777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.111111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.582043343653254


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.22222222222223


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.888888888888886


Đại Việt Sử Ký Toàn Thư
[155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.111111111111114


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.55555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.05797101449276


Đại Việt Sử Ký Toàn Thư
[155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.111111111111114


Đại Việt Sử Ký Toàn Thư
[155, 156]
Khi bệnh nguy kịch, sai thị thần là Nguyễn Dân Vọng đem bản thảo tập thơ ngự chế đốt đi. Dân Vọng còn do dự, thì Minh Tông nói: "Vật đáng tiếc còn không thể tiếc được, tiếc làm gì thứ ấy".
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  67%|██████▋   | 201/300 [06:20<03:09,  1.91s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.92156862745098


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.366013071895416


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.790849673202615


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.52459016393442


Đại Việt Sử Ký Toàn Thư
[155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.366013071895416


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.790849673202615


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 48.52459016393442


Đại Việt Sử Ký Toàn Thư
[155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 49.673202614379086


Đại Việt Sử Ký Toàn Thư
[155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.71241830065359


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.751633986928105


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.366013071895416


Đại Việt Sử Ký Toàn Thư
[154]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 48.366013071895416


Đại Việt Sử Ký Toàn Thư
[155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.673202614379086


Đại Việt Sử Ký Toàn Thư
[155]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[155, 156]
Lại dặn Hiến Từ thái hậu: "Sau khi ta mất, người ở lại cung Thánh Từ, đừng vào núi [đi tu]". Sau khi Minh Tông băng, thái hậu theo lời dặn, không thụ giới nhà Phật.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:  67%|██████▋   | 202/300 [06:22<02:49,  1.73s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.27303754266212


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.94117647058824


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.452380952380956


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.94117647058824


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.2513966480447


Đại Việt Sử Ký Toàn Thư
[154]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.01675977653632


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.6927374301676


Đại Việt Sử Ký Toàn Thư
[155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.36871508379888


Đại Việt Sử Ký Toàn Thư
[155]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.575418994413404


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ngô bệ lại đem quân tụ họp ở núi Yên Phụ, dựng cờ lớn ở trên núi, tiếm sưng vị hiệu, yết bảng nói cứu giúp dân nghèo.Từ Thiên Liêu [2] đến Chí Linh. Bệ chiếm giữ cả... Tháng 3, Ngô Bệ bị giết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  68%|██████▊   | 203/300 [06:23<02:33,  1.58s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.69747899159664


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.95798319327731


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72300469483567


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.79831932773109


Đại Việt Sử Ký Toàn Thư
[155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.53781512605042


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.69747899159664


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.95798319327731


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72300469483567


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.79831932773109


Đại Việt Sử Ký Toàn Thư
[155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.53781512605042


Đại Việt Sử Ký Toàn Thư
[155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.396145610278374


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.378151260504204


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.95798319327731


Đại Việt Sử Ký Toàn Thư
[154]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.88747346072187


Đại Việt Sử Ký Toàn Thư
[154, 155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.79831932773109


Đại Việt Sử Ký Toàn Thư
[155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.378151260504204


Đại Việt Sử Ký Toàn Thư
[155]
Khi vua ở Đông cung, đang tuổi ấu thơ, có lần nghịch làm chiếc giá đèn bằng tre, Anh Tông đòi xem, sợ không dám dâng. Hôm khác, vào hầu tẩm điện Anh Tông đang rửa mặt, nhânhỏi đến trò nghịch cũ, Anh Tông giận lắm, cầm ngay cái chậu rửa mặt ném vua.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.

Mapping source_excerpt to chunks:  68%|██████▊   | 204/300 [06:25<02:53,  1.80s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.364532019704434


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.65482233502538


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.34975369458128


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.94949494949495


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.79848866498741


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.364532019704434


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.65482233502538


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.34975369458128


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.94949494949495


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.79848866498741


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.364532019704434


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.812807881773395


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.94949494949495


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.812807881773395


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.768472906403936


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 12, xuống chiếu bắt gia nô của các vương hầu, công chúa đều phải thích chữ vào trán và phải gọi theo loại hàm. Kẻ nào không thích chữ, không khai sổ bị coi là giặc cướp, lớn thì trị tội, bé thì sung công.

Mapping source_excerpt to chunks:  68%|██████▊   | 205/300 [06:27<02:53,  1.83s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.63822525597269


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.48148148148149


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.69478908188585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.79328165374677


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.73913043478261


Đại Việt Sử Ký Toàn Thư
[155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.173913043478265


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.69478908188585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.79328165374677


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.73913043478261


Đại Việt Sử Ký Toàn Thư
[155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.559718969555036


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.913043478260875


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 41.73913043478261


Đại Việt Sử Ký Toàn Thư
[155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.559718969555036


Đại Việt Sử Ký Toàn Thư
[155]
Trước đấy, khi đánh Toa Đô, bắt được người phường hát là Lý Phương Cát rất giỏi hát, những con ở trẻ của các nhà thế gia theo y tập hát điệu phương Bắc. Nguyên Cát sáng tác các vở tuồng truyện cổ... Nước ta có tuồng truyện bắt đầu từ đấy.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.

Mapping source_excerpt to chunks:  69%|██████▊   | 206/300 [06:29<03:01,  1.93s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.24324324324324


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.62576687116564


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.93959731543624


Đại Việt Sử Ký Toàn Thư
[154, 155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.171779141104295


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.94478527607362


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.62576687116564


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.93959731543624


Đại Việt Sử Ký Toàn Thư
[154, 155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.20123839009288


Đại Việt Sử Ký Toàn Thư
[155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.62576687116564


Đại Việt Sử Ký Toàn Thư
[154]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.398773006134974


Đại Việt Sử Ký Toàn Thư
[154, 155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.78527607361963


Đại Việt Sử Ký Toàn Thư
[155]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.016077170418015


Đại Việt Sử Ký Toàn Thư
[155, 156]
Dẫn cậy giàu có thông dâm với người con gái khác, lại có những lời lăng nhục công chúa. Công chúa đem việc ấy tâu vua. Dẫn được tha tội chết, nhưng bị tịch thu gia sản.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.

Mapping source_excerpt to chunks:  69%|██████▉   | 207/300 [06:31<02:37,  1.70s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.52249134948097


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.70860927152318


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.70860927152318


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.70860927152318


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.70860927152318


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.6953642384106


Đại Việt Sử Ký Toàn Thư
[155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.35761589403974


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.70860927152318


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.6953642384106


Đại Việt Sử Ký Toàn Thư
[155]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.353159851301115


Đại Việt Sử Ký Toàn Thư
[155, 156]
Lại sai người hải Đông chở nước mặn chứa vào đó, đem các thứ hải vật như đồi mồi, cua, cá nuôi ở trong hồ. Lại sai người Hóa Châu chở cá sấu đến thả vào đó.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  69%|██████▉   | 208/300 [06:32<02:22,  1.55s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.9753086419753


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.65734265734265


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.73504273504274


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.85314685314685


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.05594405594405


Đại Việt Sử Ký Toàn Thư
[154, 155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.73504273504274


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.85314685314685


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.05594405594405


Đại Việt Sử Ký Toàn Thư
[154, 155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.55244755244755


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.85314685314685


Đại Việt Sử Ký Toàn Thư
[154]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154, 155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.55244755244755


Đại Việt Sử Ký Toàn Thư
[155]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.85314685314685


Đại Việt Sử Ký Toàn Thư
[155, 156]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.85314685314685


Đại Việt Sử Ký Toàn Thư
[156]
Triều đình nghe biết chuyện ấy, khôi phục quan chức cho ông, trong quân lại có câu ca: "Trời đã thấu oan, ông Thiều lại làm quan". Ít lâu sau, ông chết.

Mapping source_excerpt to chunks:  70%|██████▉   | 209/300 [06:33<02:18,  1.52s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.21212121212122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.6969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.484848484848484


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.24242424242424


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.21212121212122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.21212121212122


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.24242424242424


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.21212121212122


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.96969696969697


Đại Việt Sử Ký Toàn Thư
[156]
Tháng 3, người Chiêm cướp phủ Lâm Bình. Quan phủ Phạm A Song đánh bại chúng. Thăng A Song làm đại tri phủ Lâm Bình, Hành quân thủ ngự sứ.

Mapping source_excerpt to chunks:  70%|███████   | 210/300 [06:35<02:14,  1.49s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.15025906735752


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 53.018372703412076


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 51.29533678756477


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.28901734104046


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.66106442577031


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 50.259067357512954


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.15025906735752


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.523316062176164


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 53.018372703412076


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.48704663212435


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 51.29533678756477


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.28901734104046


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.66106442577031


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 50.259067357512954


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.29533678756477


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.15025906735752


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 53.018372703412076


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 51.29533678756477


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.66106442577031


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.32558139534884


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.259067357512954


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đinh Mùi, [Đại Trị] năm thứ 10 [1367], (Nguyên Chí Chính năm thứ 27). Mùa đông, tháng 12, lấy Minh tự Trần Thế hung làm Thống quân hành khiển đồng tri thượng thư tả ty sự, Đỗ Tử Bình làm phó, đi đánh Chiêm Thành.

Mapping source_excerpt to chunks:  70%|███████   | 211/300 [06:37<02:33,  1.72s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.33333333333333


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.60431654676259


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.33333333333333


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 49.33333333333333


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[155]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 49.33333333333333


Đại Việt Sử Ký Toàn Thư
[156]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 48.0


Đại Việt Sử Ký Toàn Thư
[156]
Ngày vua sắp băng, vì không có con, xuống chiếu đón Nhật Lễ vào nối đại thống.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 52.0

Mapping source_excerpt to chunks:  71%|███████   | 212/300 [06:38<02:07,  1.45s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.05283757338552


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.217484008528785


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.15196998123827


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.16417910447762


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.8235294117647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 40.90909090909091


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.029850746268664


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.217484008528785


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.28358208955224


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.15196998123827


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.16417910447762


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.8235294117647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.53731343283582


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.91044776119403


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.85633270321361


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.149253731343286


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.40298507462687


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.32209737827716


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.91044776119403


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ là con người làm trò tên là Dương Khương. Mẹ Nhật Lễ khi đóng trò có tên hiệu là Vương Mẫu (Trò có tích "Vương Mẫu hiến bàn đào ", Mẹ Nhật lễ đóng vai Vương Mẫu, nên lấy tên làm hiệu), đương có thai, Dục thấy nàng xinh đẹp, nên lấy làm vợ. Đến khi đẻ, Dục nhận làm con mình.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.85633270321361


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  71%|███████   | 213/300 [06:40<02:28,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.53125


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.692307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.673202614379086


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.790849673202615


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.51145038167938


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.71241830065359


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.673202614379086


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.790849673202615


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.51145038167938


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.71241830065359


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.673202614379086


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.09803921568627


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.353159851301115


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.01960784313726


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.97297297297297


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhật Lễ phong Hữu tướng quốc Nguyên trác làm Thượng tướng quốc thái tể. Tháng 12, ngày 14, Nhật lễ giết Hiến Từ Tuyên Thánh Thái hoàng thái hậu ở trong cung.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  71%|███████▏  | 214/300 [06:41<02:08,  1.50s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.751633986928105


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.2914798206278


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.956043956043956


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.983402489626556


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.15352697095436


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.67990074441688


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.08294930875576


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.983402489626556


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.751633986928105


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.2914798206278


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.956043956043956


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.983402489626556


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.15352697095436


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.67990074441688


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.08294930875576


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.22821576763485


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.81327800829875


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.47302904564315


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.81327800829875


Đại Việt Sử Ký Toàn Thư
[154]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.15352697095436


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.058091286307054


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.22821576763485


Đại Việt Sử Ký Toàn Thư
[155]
Thái hậu tâu: "Đây là việc trong cung, không nên để hở ra ngoài. Thứ phi Triều Môn là con gái của Cung Tĩnh Vương, nếu để hở ra thì Quan gia sẽ sinh hiềm khích với Thái úy. Thiếp xin ỉm việc này đi không xét hỏi nữa!". Minh Tông khen bà là người hiền.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  72%|███████▏  | 215/300 [06:43<02:30,  1.77s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.31210191082803


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.126789366053174


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.27642276422764


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.2183908045977


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.708542713567844


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.083900226757365


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.08943089430895


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.27642276422764


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.2183908045977


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.708542713567844


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.083900226757365


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.71544715447154


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.3089430894309


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.49593495934959


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.71544715447154


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ tiếm vị, rượu chè dâm dật, hằng ngày chỉ rong chơi, thích các trò hát xướng, muốn đổi lại họ là Dương. Người tôn thất và các quan đều thất vọng. Mùa thu, tháng 9, ngày 20, thái tể Nguyên Trác cùng con là Nguyên Tiết giết Nhật Lễ không được, bị giết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  72%|███████▏  | 216/300 [06:46<02:44,  1.96s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.038216560509554


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.40282685512368


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.02564102564102


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.40282685512368


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.02564102564102


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.962732919254655


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[155]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.3416149068323


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhật Lễ gọi Ngô Lang vào trong màn, nói dối rằng: "Ta có lọ vàng chôn ở trong cung, ngươi đi lấy về đây". Ngô Lang qùy xuống vâng lệnh. Nhật Lễ bóp cổ Ngô Lang đến chết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.

Mapping source_excerpt to chunks:  72%|███████▏  | 217/300 [06:47<02:34,  1.86s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.07692307692307


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.33333333333333


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.553191489361694


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.07692307692307


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.33333333333333


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.553191489361694


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.5


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.553191489361694


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.33333333333333


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[156]
Ngày 15, [vua] lên ngôi hoàng đế, đổi niên hiệu, đại xá. [Vua] tự xưng là Nghĩa hoàng. Mọi công việc đều theo lệ cũ đời Khai Thái [2].

Mapping source_excerpt to chunks:  73%|███████▎  | 218/300 [06:49<02:22,  1.73s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.405204460966544


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.57831325301205


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57831325301205


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57831325301205


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.56626506024096


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.975903614457835


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.78313253012048


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.57831325301205


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57831325301205


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.56626506024096


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.975903614457835


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.397590361445786


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.78313253012048


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.59036144578314


Đại Việt Sử Ký Toàn Thư
[154]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.3855421686747


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.975903614457835


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.397590361445786


Đại Việt Sử Ký Toàn Thư
[155]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.18072289156626


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đến khi vua lên ngôi lấy Nhiên làm hành khiển, thăng làm tả tham ty chính sự. Nhiên chữ nghĩa ít, khai phê giấy tờ, vua thường bảo vẽ các nét chữ đưa cho Nguyễn Nhiên xem.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.

Mapping source_excerpt to chunks:  73%|███████▎  | 219/300 [06:51<02:18,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.19774011299435


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.956043956043956


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.19774011299435


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.956043956043956


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.554913294797686


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[156]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[156]
Quốc tử giám tư nghiệp Chu An mất, được truy tặng tước Văn Trinh công, ban cho tòng tự ở Văn Miếu.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 48.08743169398907

Mapping source_excerpt to chunks:  73%|███████▎  | 220/300 [06:51<01:56,  1.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.60143626570916


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.22678843226788


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.30484330484331


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.9553264604811


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.90358126721763


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.44186046511628


Đại Việt Sử Ký Toàn Thư
[155]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.29065743944637


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.1063829787234


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.22678843226788


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.30484330484331


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.9553264604811


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.90358126721763


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.44186046511628


Đại Việt Sử Ký Toàn Thư
[155]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.84724186704385


Đại Việt Sử Ký Toàn Thư
[155]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.005509641873275


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.35261707988981


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.80165289256198


Đại Việt Sử Ký Toàn Thư
[154]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.90358126721763


Đại Việt Sử Ký Toàn Thư
[154, 155]
Văn Trinh không gặp vua (anh minh) nên chính học của ông, đời sau mới thấy được. Hãy lấy Văn Trinh mà nói, thờ vua tất thẳng thắn can ngăn, xuất xử thì làm theo nghĩa lý, đào tạo nhân tài thì công khanh đều ở cửa ông mà ra, tiết tháo cao thượng thì thiên tử cũng không thể bắt làm tôi được... Ông thực đáng được coi là ông tổ của các nhà nho nước Việt ta mà thờ vào Văn Miếu.

Mapping source_excerpt to chunks:  74%|███████▎  | 221/300 [06:56<03:10,  2.42s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.36569579288025


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.34527687296416


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.6179604261796


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.756183745583044


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.19653179190751


Đại Việt Sử Ký Toàn Thư
[155]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.113772455089816


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.34527687296416


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.6179604261796


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.756183745583044


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.19653179190751


Đại Việt Sử Ký Toàn Thư
[155]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.48554913294797


Đại Việt Sử Ký Toàn Thư
[155]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.48554913294797


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.77456647398844


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[154]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.77456647398844


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bỏ phép cắt chân bãi bồi. Xóa lệnh kiểm kê tài sản. Trước đây, các nhà vương hầu, công chúa lập điền trang ở ven sông thì đất phù sa mới bồi đều thuộc về người chủ [điền trang]. Thái hậu Chiêu Từ [nhân đó] mới lập thành phép cắt chân bãi bồi... Những người quyền quý chết thì tài sản đều thuộc về con cháu họ. Dụ Tông mới có lệnh kiểm kê... Đến đây đều bãi bỏ cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

Mapping source_excerpt to chunks:  74%|███████▍  | 222/300 [07:00<03:55,  3.01s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.0


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.45549738219895


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.97905759162304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.31413612565446


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.93193717277487


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.97905759162304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.45549738219895


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.97905759162304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.45810055865922


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.31413612565446


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.93193717277487


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.97905759162304


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.45549738219895


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.45549738219895


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.97905759162304


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.45549738219895


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.45549738219895


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.120418848167546


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 3 nhuận, Chiêm Thành vào cướp, từ cửa biển Đại An [1] tiến thẳng đến kinh sư... Chiêm Thành sở dĩ sang cướp là vì mạ Nhật Lễ chạy trốn sang nước ấy, xúi giục chúng vào cướp để báo thù cho Nhật Lễ.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  74%|███████▍  | 223/300 [07:02<03:24,  2.66s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.36546184738956


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.162393162393165


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.391304347826086


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.76706827309237


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.80327868852459


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.201312910284464


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.162393162393165


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.391304347826086


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.76706827309237


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.38152610441767


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.57028112449799


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.78313253012048


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.38152610441767


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 5, lấy người họ ngoại là Lê Quý Ly làm khu mật viện đại sứ. Hai chị em bà cô của Quý Ly, Minh Tông đều lấy làm cung nhân. Một bà sinh ra vua, đó là bà Minh Từ. Một bà sinh ra Duệ Tông, đó là bà Đôn Từ. Cho nên vua khi mới lên ngôi rất tín nhiệm Quý Ly.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  75%|███████▍  | 224/300 [07:06<03:34,  2.82s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.72049689440993


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.899224806201545


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.124031007751945


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57364341085272


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.79256360078278


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.575221238938056


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.899224806201545


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.124031007751945


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57364341085272


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.79256360078278


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.736434108527135


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.06201550387597


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.899224806201545


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.124031007751945


Đại Việt Sử Ký Toàn Thư
[154]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.34883720930233


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.124031007751945


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.06201550387597


Đại Việt Sử Ký Toàn Thư
[155]
Mùa đông, tháng 10, vua ngự đến phủ Thiên Trường, sửa lại miếu thờ ở các lăng. Tháng 11, ngày mồng 9, vua nhường ngôi cho hoàng thái tử Kính. Kính lên ngôi hoàng đế. Đại xá. [Vua tự] xưng là Khâm hoàng. Các quan dâng tôn hiệu là Kế thiên ứng vận nhân minh khâm hhoàng đế.

Mapping source_excerpt to chunks:  75%|███████▌  | 225/300 [07:08<03:18,  2.64s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.28776978417267


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51497005988024


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.66457680250783


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.712574850299404


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.10958904109589


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.27963525835866


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.20338983050847


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 52.09580838323353


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.712574850299404


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 52.66457680250783


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.712574850299404


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.10958904109589


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 52.27963525835866


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.20338983050847


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 52.09580838323353


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.706586826347305


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.50898203592815


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 52.66457680250783


Đại Việt Sử Ký Toàn Thư
[154]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.10958904109589


Đại Việt Sử Ký Toàn Thư
[154, 155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.20338983050847


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.25225225225225


Đại Việt Sử Ký Toàn Thư
[155]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.49700598802396


Đại Việt Sử Ký Toàn Thư
[155, 156]
Nhâm Tý, [Thiệu Khánh] năm thứ 3 [1372], (Minh HồngVũ năm thứ 5). Mùa xuân, tháng giêng, xét công lao của các quan văn võ. Mùa hạ, tháng 4, lấy Đỗ Tử Bình làm hành khiển, tham mưu quân sự.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  75%|███████▌  | 226/300 [07:09<02:42,  2.19s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 59.493670886075954


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.3416149068323


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[154, 155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.20496894409938


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.68944099378882


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 59.493670886075954


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.3416149068323


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.37086092715232


Đại Việt Sử Ký Toàn Thư
[154, 155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.20496894409938


Đại Việt Sử Ký Toàn Thư
[155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 58.38509316770186


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.3416149068323


Đại Việt Sử Ký Toàn Thư
[154, 155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.3416149068323


Đại Việt Sử Ký Toàn Thư
[155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.82608695652174


Đại Việt Sử Ký Toàn Thư
[155]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.5527950310559


Đại Việt Sử Ký Toàn Thư
[155, 156]
Duệ TÔNG HOÀNG ĐẾ Tên húy là Kính, con thứ 11 của Minh Tông, em Nghệ Tông. Mẹ là Đôn Từ hoàng thái phi. Sinh năm Đinh Sửu, Khai Hựu năm thứ 9 (1337), tháng 6, ngày mồng 2.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.

Mapping source_excerpt to chunks:  76%|███████▌  | 227/300 [07:10<02:17,  1.88s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.776735459662284


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.349650349650354


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.80790960451978


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.38805970149254


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.591016548463365


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.1166077738516


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 49.590163934426236


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.349650349650354


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.80790960451978


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.38805970149254


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.591016548463365


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.1166077738516


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.85314685314685


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.349650349650354


Đại Việt Sử Ký Toàn Thư
[154]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.38805970149254


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 49.1166077738516


Đại Việt Sử Ký Toàn Thư
[155]
Giáp Dần, [Long Khánh] năm thứ 2 [1347], (Minh Hồng Vũ năm thứ 7). Mùa xuân, tháng 2, thượng hoàng về ở cung Trùng Hoa, phủ Thiên Trường. [Tổ chức] thi đinh cho các tiến sĩ. Ban cho Đào Sư Tích đỗ trạng nguyên, Lê Hiến Phủ đỗ bảng nhãn, Trần Đình Thám đỗ thám hoa, bọn La Tu đỗ hoàng giáp cập đệ và đồng cập đệ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;

Mapping source_excerpt to chunks:  76%|███████▌  | 228/300 [07:13<02:29,  2.08s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.80099502487562


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.82539682539682


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 57.60000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.063492063492056


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.46218487394958


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.968253968253975


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 57.14285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 51.58730158730158


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.82539682539682


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 57.60000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.063492063492056


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.46218487394958


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 53.968253968253975


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 57.14285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 51.58730158730158


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.82539682539682


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 57.60000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.46218487394958


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 57.14285714285714


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 51.52838427947598


Đại Việt Sử Ký Toàn Thư
[155]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 53.968253968253975


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 56.34920634920635


Đại Việt Sử Ký Toàn Thư
[156]
Ất Mão, [Long Khánh] năm thứ 3 [1375], (Minh Hồng Vũ năm thứ 8). Mùa xuân, tháng giêng, lấy Khu mât viện đại sứ Lê Quý Ly làm tham mưu quân sự.

Mapping source_excerpt to chunks:  76%|███████▋  | 229/300 [07:14<02:04,  1.76s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 40.23668639053254


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.61849710982659


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.542435424354245


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.80442804428044


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.542435424354245


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.68585131894484


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.80442804428044


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.484716157205234


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.69741697416974


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.61849710982659


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.542435424354245


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.80442804428044


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.542435424354245


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.68585131894484


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.80442804428044


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.80442804428044


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.06642066420664


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.542435424354245


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.542435424354245


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.80442804428044


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, chúa Chiêm Thành Chế Bồng Nga quấy rối biên giới, vua sai han2h khiển Đỗ Tử Bình đem quân trấn giữ Hóa Châu. Bồng Nga đem 10 mâm vàng dâng lên [vua]. Tử Bình ỉm đi, cướp làm của mình, nối dối là Bồng Nga ngạo mạn vô lễ, nên đem quân đánh. Vua giận lắm, quyết ý thân chinh.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.91143911439115


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  77%|███████▋  | 230/300 [07:17<02:34,  2.20s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.310679611650485


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.36241610738255


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.90419161676647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.76872964169381


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 53.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 56.310679611650485


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 54.36241610738255


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.90419161676647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 52.76872964169381


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 53.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.142857142857146


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 56.310679611650485


Đại Việt Sử Ký Toàn Thư
[154]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 54.36241610738255


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 52.76872964169381


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 54.02298850574713


Đại Việt Sử Ký Toàn Thư
[155]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.857142857142854


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bính Thìn, [Long Khánh] năm thứ 4 [1376], (Minh Hồng Vũ năm thứ 9). Mùa xuân, tháng giêng, gả công chúa Tuyên Huy cho quan phục đại vương Húc (con của thượng hoàng). Thượng hoàng thân đi đón dâu.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  77%|███████▋  | 231/300 [07:19<02:21,  2.06s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.50561797752809


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.43820224719101


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.75280898876404


Đại Việt Sử Ký Toàn Thư
[155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.50561797752809


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 49.43820224719101


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.311377245508986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.75280898876404


Đại Việt Sử Ký Toàn Thư
[155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.06741573033708


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.06741573033708


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 49.43820224719101


Đại Việt Sử Ký Toàn Thư
[154]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.9438202247191


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.75280898876404


Đại Việt Sử Ký Toàn Thư
[155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.06741573033708


Đại Việt Sử Ký Toàn Thư
[155]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.06741573033708


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bồng Nga dựng trại bên ngoại thành Đồ Bàn [6], sai viên quan nhỏ là Mục Bà Ma đến trá hàng, nối dối là Bồng Nga đã chạy trốn, chỉ còn lại thành không, nên tiến quân gấp, đừng để lỡ cơ hội.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  77%|███████▋  | 232/300 [07:20<02:02,  1.80s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.608695652173914


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51968503937008


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.03149606299213


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.51968503937008


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.643153526970956


Đại Việt Sử Ký Toàn Thư
[155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.09448818897638


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.51968503937008


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.03149606299213


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.51968503937008


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.643153526970956


Đại Việt Sử Ký Toàn Thư
[155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.09448818897638


Đại Việt Sử Ký Toàn Thư
[155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.81497797356828


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.09448818897638


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.03149606299213


Đại Việt Sử Ký Toàn Thư
[154]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.30708661417323


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.881889763779526


Đại Việt Sử Ký Toàn Thư
[155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.81497797356828


Đại Việt Sử Ký Toàn Thư
[155]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.45669291338582


Đại Việt Sử Ký Toàn Thư
[156]
Giờ Tỵ, quan quân tan vỡ. Vua bị hãm trong trận mà chết. Bọn đại tướng Đỗ Lễ, Nguyễn Nạp Hòa, hành khiển Phạm Huyền Linh đều chết cả.

Mapping source_excerpt to chunks:  78%|███████▊  | 233/300 [07:21<01:45,  1.58s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.675159235668794


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.52873563218391


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.81184668989547


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.785714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.463414634146346


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.72727272727273


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.00743494423792


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.81184668989547


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.785714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.463414634146346


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.72727272727273


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.00715563506261


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.20557491289199


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.250871080139376


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình chỉ huy hậu quân, không đến cứu nên thoát chết. Lê Quý Ly đốc quân chở lương, nghe tin vua băng, bỏ trốn về nước. Ngày hôm ấy ở kinh sư, ban ngày mà trời tối om, chợ búa phải đốt đuốc để mua bán. Xe cũi chở Tử Bình về qua Thiên Trường, người ta lấy gạch ngói ném vào thuyền mà chửi hắn.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  78%|███████▊  | 234/300 [07:23<02:04,  1.89s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.006568144499184


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.708542713567844


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.712842712842715


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.42268041237113


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.249657064471876


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.8905109489051


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.59605911330049


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.708542713567844


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.712842712842715


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.42268041237113


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.249657064471876


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.37050805452293


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.89027431421446


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, ngự sử đại phu Trương Đỗ (có sách chép là Xã) can vua rằng: "Chiêm Thành chống lệnh, tội cũng chưa đáng phải giết. Song nó ở tận cõi tây xa xôi, núi sông hiểm trở. Nay bệ hạ vừa mới lên ngôi, đức chính, giáo hóa chưa thấm nhuần được tới phương xa, nên sửa sang văn đức khiến nó tự đến thuần phục. Nếu nó không theo, sẽ sai tướng đi đánh cũng chưa muộn". Đỗ ba lần dâng sớ can vua không được, bèn treo mũ mà bỏ đi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).

Mapping source_excerpt to chunks:  78%|███████▊  | 235/300 [07:30<03:30,  3.24s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.53312302839116


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.391752577319586


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.961352657004824


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.57640750670241


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.54430379746835


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.96969696969697


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.391752577319586


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.961352657004824


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.57640750670241


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.54430379746835


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.96969696969697


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.14285714285714


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.57640750670241


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.221105527638194


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, ngày 13, thượng hoàng vì thấy vua chết vì nạn nước, mới lập con trưởng của vua là Kiến Đức đại vương Hiện nối nghiệp lên ngôi hoàng đế. [Vua] tự xưng là Giản Hoàng, đổi niên hiệu là Xương Phù năm thứ 1.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  79%|███████▊  | 236/300 [07:33<03:17,  3.09s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 56.09756097560976


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.553191489361694


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.19241192411924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 56.09756097560976


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.553191489361694


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.19241192411924


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.285714285714285


Đại Việt Sử Ký Toàn Thư
[155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.76190476190476


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 55.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.80952380952381


Đại Việt Sử Ký Toàn Thư
[154, 155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.87755102040817


Đại Việt Sử Ký Toàn Thư
[155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.76190476190476


Đại Việt Sử Ký Toàn Thư
[155]
Phế Đế Tên húy là Hiện, con trưởng của Duệ Tông, mẹ là bà Gia Từ hoàng hậu Lê thị, sinh ngày mồng 6 tháng 3, năm Đại Trị thứ 4, Tân Sửu (1361), đến khi Duệ Tông đi đánh phương Nam rồi mất, được Nghệ Tông lập nên làm vua.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.09523809523809


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  79%|███████▉  | 237/300 [07:35<02:55,  2.78s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.00000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.860465116279066


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.60401002506266


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.104166666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.860465116279066


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.60401002506266


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.104166666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.7129909365559


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.49999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.60401002506266


Đại Việt Sử Ký Toàn Thư
[154, 155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.00000000000001


Đại Việt Sử Ký Toàn Thư
[155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.50000000000001


Đại Việt Sử Ký Toàn Thư
[155]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155, 156]
Giặc buộc Giốc phải lạy, Giốc trả lời chúng: "Ta là quan của nước lớn, sao phải lạy chúng mày!". Giặc nổi giận, giết ông. Giốc luôn miệng chửi chúng. Việc này tâu lên, Giốc được truy phong là Mạ Tặc Trung Vũ hầư

Mapping source_excerpt to chunks:  79%|███████▉  | 238/300 [07:37<02:37,  2.54s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.95804195804196


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.91891891891891


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.270270270270274


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.945945945945944


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.75862068965517


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.19475655430711


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.91891891891891


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.62162162162162


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.91891891891891


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.270270270270274


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.945945945945944


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.75862068965517


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.19475655430711


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.91891891891891


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.62162162162162


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.270270270270274


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.270270270270274


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.945945945945944


Đại Việt Sử Ký Toàn Thư
[154]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.19475655430711


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.20689655172414


Đại Việt Sử Ký Toàn Thư
[155]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.5945945945946


Đại Việt Sử Ký Toàn Thư
[155, 156]
Đỗ Tử Bình kiến nghị thu mỗi hộ đinh nam 3 quan tiền. Vua nghe theo... Đến đây, Tử Bình bắt chước phép đánh thuế dung của nhà Đường, thuế má lại nặng thêm.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 47.97297297297297


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  80%|███████▉  | 239/300 [07:38<02:08,  2.10s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.32203389830509


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.0565371024735


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.67353951890034


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.0565371024735


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.67353951890034


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.333333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.33333333333333


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.0565371024735


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.78048780487805


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.33333333333333


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 52.666666666666664


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 9, sai quân dân chở tiền đồng giấu vào núi Thiên Kiện... Mùa đông, tháng 10, giấu [tiền] ở khám Khả Lãng, Lạng Sơn, là vì sợ nạn người Chiêm đốt cung điện.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 49.33333333333333


Mapping source_excerpt to chunks:  80%|████████  | 240/300 [07:39<01:48,  1.81s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.14869888475836


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.31797235023041


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.22604422604422


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.16129032258065


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.75184275184275


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.77880184331797


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.89156626506024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.70046082949308


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.31797235023041


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.22604422604422


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.16129032258065


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.75184275184275


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.77880184331797


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.89156626506024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.70046082949308


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.54377880184332


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.31797235023041


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.16129032258065


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.77880184331797


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.70046082949308


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.54377880184332


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, Quý Ly dẫn viên tướng chỉ huy quân Thần Vũ và Nguyễn Kim Ngao và tướng chỉ huy quân Thị vệ là Đỗ Dã Kha ra đánh. Kim Ngao quay thuyền trở lại để tránh mũi nhọn của giặc. Quý Ly chém Ngao để rao trong quân.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.08294930875576


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  80%|████████  | 241/300 [07:41<01:52,  1.90s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.016077170418015


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.02272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.61370716510904


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.51038575667656


Đại Việt Sử Ký Toàn Thư
[154, 155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.54455445544554


Đại Việt Sử Ký Toàn Thư
[155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.88235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.24277456647399


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.02272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.61370716510904


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.51038575667656


Đại Việt Sử Ký Toàn Thư
[154, 155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.54455445544554


Đại Việt Sử Ký Toàn Thư
[155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.29545454545454


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.02272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.59090909090909


Đại Việt Sử Ký Toàn Thư
[154, 155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 48.07121661721068


Đại Việt Sử Ký Toàn Thư
[155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.29545454545454


Đại Việt Sử Ký Toàn Thư
[155]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.43181818181818


Đại Việt Sử Ký Toàn Thư
[155, 156]
Cho tướng coi quân Thần Khôi là Nguyễn Đa Phương giữ hàng cọc đóng ở [cửa] biển Thần Đầư [3]... Mùa hạ, tháng 4, tin thắng trận báo về, phong Nguyễn Đa Phương làm Kim ngô vệ đại tướng quân.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  81%|████████  | 242/300 [07:42<01:39,  1.71s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.441947565543074


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.05555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.32374100719424


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.361111111111114


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.05555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.32374100719424


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.361111111111114


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.22222222222222


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.52777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.138888888888886


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.833333333333336


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.611111111111114


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 6, rước thần tượng các lăng ở Quắc Hương [4], Thái Đường [5], Long Hưng, Kiến Xương đưa về lăng lớn ở Yên Sinh để tránh [nạn] người Chiêm Thành vào cướp.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.52777777777778


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  81%|████████  | 243/300 [07:44<01:34,  1.66s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.55400696864111


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.693409742120345


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.83954154727794


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.60093896713615


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.75743348982786


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.920303605313094


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.97994269340975


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.693409742120345


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.83954154727794


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.60093896713615


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.75743348982786


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.21669106881405


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.55873925501432


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.412607449856736


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.126074498567334


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 6, chúa Chiêm Thành là Chế Bồng Nga cùng với thủ tướng La Ngai dẫn quân đi bộ theo chân núi... Thượng hoàng sai tướng chỉ huy quân Hoa Ngạch là Lê Mật Ôn đem quân đi chống giữ. Mật Ôn đến chân Tam Kỳ (nay là phủ Quảng Oai) định bày trận chống giữ. Nhưng giặc đã mai phục từ trước, quân voi đều xông ra, quan quân thua chạy, Mật Ôn bị giặc bắt sống.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

Mapping source_excerpt to chunks:  81%|████████▏ | 244/300 [07:49<02:35,  2.77s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.80701754385965


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.15992292870906


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.28329809725159


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45614035087719


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.02325581395349


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.80701754385965


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.15992292870906


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.28329809725159


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45614035087719


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.15789473684211


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.45614035087719


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng ở cung Bảo Hòa [2], sai Thiêm tri nội mật viện sự Nguyễn Mậu Tiên, Lễ bộ lang trung Phan Nghĩa và gia thần Vũ Hiếu hầu (không rõ tên) ở Tiên Du thay phiên nhau chầu chực. [Thượng hoàng] ban cho ăn và hỏi các việc cũ, ghi chép từng ngày, biên soạn thành 8 quyển, đầu đề là Bảo Hòa dư bút [3]
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  82%|████████▏ | 245/300 [07:52<02:27,  2.68s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.60587002096437


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.083003952569165


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.09090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.169611307420496


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72300469483567


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.52296819787986


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.60176991150443


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.46289752650176


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.083003952569165


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.09090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.13725490196079


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.169611307420496


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.72300469483567


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.52296819787986


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.52296819787986


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.169611307420496


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.87632508833922


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.87632508833922


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.169611307420496


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.20938628158845


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, nhà Minh sai sứ sang đòi 20 tăng nhân. Trước đây, nước ta đưa bọn nội nhân Nguyễn Tông Đạo, Nguyễn Toán đến Kim Lăng, vua Minh dùng làm cận thần, đãi ngộ rất hậu. Bọn Tông Đạo tâu: "Tăng nhân nước Nam biết dựng đạo tràng giỏi hơn tăng nhân phương Bắc". Đến đây [nhà Minh cho sứ] sang đòi.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  82%|████████▏ | 246/300 [07:54<02:21,  2.62s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.49122807017544


Đại Việt Sử Ký Toàn Thư
[155]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.122807017543856


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 48.24561403508771


Đại Việt Sử Ký Toàn Thư
[156]
Ứng Long đến nhà Hồ được cất nhắc sử dụng, đổi tên là Phi Khanh (Phi Khanh sinh ra [Nguyễn] Trãi, cũng đỗ thái học sinh).
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 45.614035087719294


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  82%|████████▏ | 247/300 [07:55<01:52,  2.12s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.98473282442748


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.4812030075188


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.38297872340426


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.96039603960396


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.4812030075188


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.4812030075188


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.38297872340426


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.31455399061033


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.96039603960396


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.984962406015036


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.38297872340426


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.360902255639104


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng 2, nhà Minh sai Lâm Bốt sang đòi giống các loại cây cau, vải, mít, nhãn, vì nộI nhân Nguyễn Tông Đạo nói hoa quả phương Nam có nhiều thứ ngon. Vua sai bọn Viên ngoại lang Phạm Đình đem sang, nhưng những cây ấy không chịu được rét, đi nửa đường đều chết khô cả.

Mapping source_excerpt to chunks:  83%|████████▎ | 248/300 [07:58<02:05,  2.42s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.07744107744108


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.30379746835443


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.77215189873418


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.40506329113924


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.967213114754095


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.40506329113924


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.77215189873418


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.30379746835443


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.77215189873418


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.40506329113924


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.967213114754095


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.40506329113924


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.40506329113924


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.56962025316456


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.30379746835443


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.40506329113924


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.56962025316456


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 43.67088607594937


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 3, Lấy Lê Quý Ly làm Đồng bình chương sự, ban cho một thanh gươm, một lá cờ đề 8 chữ "Văn võ toàn tài, quân thần đồng đức"2 Quý Ly làm bài thơ quốc ngữ tạ ơn .
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:  83%|████████▎ | 249/300 [08:00<01:52,  2.21s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.74774774774775


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.40740740740741


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.40740740740741


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.21848739495798


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 47.74774774774775


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.18518518518518


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.40740740740741


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.40740740740741


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.21848739495798


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.40740740740741


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.7037037037037


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.925925925925924


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 49.62962962962963


Đại Việt Sử Ký Toàn Thư
[156]
Mùa hạ, tháng 5, lấy Trần Đỗ làm cung lệnh. Đỗ là con Thượng vị hầu Tông, mẹ Đỗ cải giá lấy Quý Ly, cho nên có lệnh này. Sau Đỗ đổi làm họ Hồ.

Mapping source_excerpt to chunks:  83%|████████▎ | 250/300 [08:01<01:39,  1.98s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.92156862745098


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.8082191780822


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.234404536862


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.94117647058824


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.178082191780824


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.31464737793852


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.92156862745098


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.8082191780822


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.234404536862


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.94117647058824


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.178082191780824


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.178082191780824


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.52054794520548


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.26241134751773


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.150684931506845


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.40497335701599


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, ngày mồng 6, sáng sớm, Thượng hoàng vờ ngự về Yên Sinh, sai điện hậu hộ vệ, rồi sai chi hậu nội nhân gọi vua tới bàn việc nước. Vua chưa kịp ăn, vội đi ngay, chỉ có hai người theo hầu thôi. Đến nơi, Thượng hoàng bảo vua: "Đại Vương lại đây!"3, rồi lập tức sai người đem vua ra giam ở chùa Tư Phúc
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.

Mapping source_excerpt to chunks:  84%|████████▎ | 251/300 [08:04<01:46,  2.17s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.282685512367486


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.0728476821192


Đại Việt Sử Ký Toàn Thư
[154, 155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 39.0728476821192


Đại Việt Sử Ký Toàn Thư
[154, 155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.04635761589404


Đại Việt Sử Ký Toàn Thư
[154]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.70860927152318


Đại Việt Sử Ký Toàn Thư
[154, 155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[155]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[155, 156]
Duy có Dữ Nghị là bị đày ra Trại Đầu, sau xét không có tội, lại được bổ làm Tuyên phủ sứ lộ Bắc Giang. Đến năm Kiến Tân thứ 26, lại vì việc bè cánh bị giết.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 42.384105960264904


Đại Việt Sử Ký Toàn Thư
[156]

Mapping source_excerpt to chunks:  84%|████████▍ | 252/300 [08:05<01:28,  1.85s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.386243386243386


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.37655860349127


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.04651162790697


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.79069767441861


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.934782608695656


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.04651162790697


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.906976744186046


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.37655860349127


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.04651162790697


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.79069767441861


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.934782608695656


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.04651162790697


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.837209302325576


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.76744186046511


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.51162790697675


Đại Việt Sử Ký Toàn Thư
[154]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.72093023255814


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.04651162790697


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.837209302325576


Đại Việt Sử Ký Toàn Thư
[155]
Ngày 27, Thượng hoàng lập con út là Chiêm Định Vương Ngung làm Hoàng đế. Ngung lên ngôi, đổi niên hiệu là Quang Thái năm thứ 1, đại xá, tự xưng là Nguyên Hoàng. THUẬN TÔNG HOÀNG ĐẾ Tên huý là Ngung, là con út của Nghệ Tông
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.97674418604652


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  84%|████████▍ | 253/300 [08:07<01:30,  1.92s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.463414634146346


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.92664092664092


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.096234309623426


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.248062015503876


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.08494208494209


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.23232323232323


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.31274131274131


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.92664092664092


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.096234309623426


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.248062015503876


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.78403755868545


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.08494208494209


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.0062630480167


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.62934362934363


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.698841698841704


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.4015444015444


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.08494208494209


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.62934362934363


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly để tỳ tướng Phạm Khả Vĩnh ở lại cầm cự với giặc, còn mình thì trốn về. Nguyễn Đa Phương tạm chỉ huy quân Thánh Dực. Đêm đó, Đa Phương bàn với Khả Vĩnh: "Thế giặc như vậy, bọn ta cô quân, khó lòng cầm cự được lâu. Nếu rút quân về, giặc nhất định thừa cơ đuổi theo".
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.

Mapping source_excerpt to chunks:  85%|████████▍ | 254/300 [08:09<01:34,  2.05s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.888888888888886


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.77777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.37689969604863


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.84527220630372


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.15909090909091


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.888888888888886


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.776119402985074


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.44444444444444


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.77777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.37689969604863


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.84527220630372


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.15909090909091


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.84527220630372


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.666666666666664


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 11, Thượng hoàng sai Trần Khát Chân 4 chỉ huy quân Long Tiệp ra quân đánh giặc. Khát Chân vâng mệnh, khảng khái nhỏ nước mắt lạy tạ ra đi. Thượng hoàng cũng khóc, lấy mắt tiễn đưa.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  85%|████████▌ | 255/300 [08:11<01:20,  1.80s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 46.45669291338582


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.54929577464789


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.54929577464789


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.95774647887324


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[155]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[155, 156]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[156]
Trước đây, bà Lê thị, hoàng hậu của Duệ Tông là mẹ Linh Đức Vương, em họ của Quý Ly, Duệ Tông đi đánh phương Nam không trở về, bà cắt tóc làm ni cô.

Mapping source_excerpt to chunks:  85%|████████▌ | 256/300 [08:12<01:14,  1.69s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 45.18272425249169


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.08510638297872


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.71859296482412


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.659279778393355


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.221105527638194


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.673521850899746


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.713567839195974


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.733668341708544


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.58974358974359


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.08510638297872


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.71859296482412


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.659279778393355


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.221105527638194


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.673521850899746


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.713567839195974


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.733668341708544


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.231155778894475


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.221105527638194


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.71859296482412


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.221105527638194


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.231155778894475


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.81933842239185


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quý Ly tâu: "Đa Phương rất gan góc, tráng kiện, thần sợ hắn sẽ trốn sang nước Minh phương Bắc hay Chiêm Thành phương Nam, thả cọp để lại mối họa về sau, chi bằng giết đi là hơn". Rồi bắt Đa Phương phải tự tử.

Mapping source_excerpt to chunks:  86%|████████▌ | 257/300 [08:15<01:29,  2.07s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.465753424657535


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 40.87193460490464


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.192307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.67307692307693


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.0939226519337


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.394014962593516


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.230769230769226


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.269230769230774


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.192307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.35260115606936


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.67307692307693


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.0939226519337


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.394014962593516


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.230769230769226


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.66310160427807


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.192307692307686


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.67307692307693


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.230769230769226


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.66310160427807


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, nhà sư Thiên Nhiên là Phạm Sư Ôn làm phản, hô hào dân chúng tụ họp ở lộ Quốc Oai Thượng, tiếm xưng hiệu lớn... chiêu tập những bọn không quê quán, lập các quân hiệu Thần Kỳ, Dũng Đấu, Vô Hạn, đánh vào kinh sư.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.63461538461539


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  86%|████████▌ | 258/300 [08:17<01:28,  2.10s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.71844660194175


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.76094276094277


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.25407166123778


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.81184668989547


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.299674267100976


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.60260586319218


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.528301886792455


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.97394136807817


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.76094276094277


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.25407166123778


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.81184668989547


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.299674267100976


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.60260586319218


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.579804560260584


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.60260586319218


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.299674267100976


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.25407166123778


Đại Việt Sử Ký Toàn Thư
[154]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.299674267100976


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.60260586319218


Đại Việt Sử Ký Toàn Thư
[155]
Mùa xuân, tháng giêng, ngày 23, đô tướng Trần Khát Chân đại thắng quân Chiêm Thành ở Hải Triều, giết được chúa nó là Chế Bồng Nga... có tên tiểu thần của Bồng Nga là Ba Lậu Kê nhân bị Bồng Nga trách phạt, sợ bị giết, chạy sang doanh trại quân ta, trỏ vào chiến thuyền sơn xanh bảo rằng đó là thuyền của quốc vương hắn.

Mapping source_excerpt to chunks:  86%|████████▋ | 259/300 [08:20<01:34,  2.29s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.80064308681673


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.855967078189295


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.75184275184275


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.49180327868852


Đại Việt Sử Ký Toàn Thư
[155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.492440604751614


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.442622950819676


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.855967078189295


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.75184275184275


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.49180327868852


Đại Việt Sử Ký Toàn Thư
[155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.95081967213115


Đại Việt Sử Ký Toàn Thư
[155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.36065573770492


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.08196721311475


Đại Việt Sử Ký Toàn Thư
[154]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.49180327868852


Đại Việt Sử Ký Toàn Thư
[155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.36065573770492


Đại Việt Sử Ký Toàn Thư
[155]
Chỉ có thổ hào Phan Mã và Phạm Căng đem dân chúng quy thuận... lại có công đón đánh quân giặc bại trận chạy qua. Thượng hoàng thưởng cho rất hậu, cho làm tới Dực vệ quân, lại thăng làm Uy Minh tướng quân, chỉ huy quân Thánh Dực ở Tân Bình và Thuận Hóa.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  87%|████████▋ | 260/300 [08:22<01:33,  2.33s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.33898305084746


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.45762711864406


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.72093023255814


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.97082228116711


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.33898305084746


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.45762711864406


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.72093023255814


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.97082228116711


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.61016949152542


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.76271186440678


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.33898305084746


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.45762711864406


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.06047516198704


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.49152542372882


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.61016949152542


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 3, Quý Ly sai viên tướng coi quân Tả Thánh Dực Hoàng Phụng Thế đem quân đi tuần đất Chiêm Thành. Người Chiêm Thành đặt mai phục. Quân Phụng Thế tan vỡ, [Phụng Thế] bị giặc bắt. Quý Ly sai chém 30 viên đại đội phó dưới quyền của Phụng Thế.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  87%|████████▋ | 261/300 [08:25<01:30,  2.31s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.63822525597269


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.38258575197889


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.17766497461929


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 45.38258575197889


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.650124069478906


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.023696682464454


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.54976303317536


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.38258575197889


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.650124069478906


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, Thái úy Trang Định Vương Ngạc trốn ra trang Nam Định... Thượng hoàng sai viên tướng coi quân Ninh Vệ Nguyễn Nhân Liệt đuổi bắt về. Quý Ly ngầm sai Liệt giết đi. Nhân Liệt đánh chết Ngạc bị giáng làm Mẫn Vương.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.07582938388626


Đại Việt Sử Ký Toàn Thư
[155, 156]

Mapping source_excerpt to chunks:  87%|████████▋ | 262/300 [08:27<01:33,  2.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.95302013422819


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.31486880466472


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.565217391304344


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.02173913043478


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.64383561643835


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.77777777777778


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.565217391304344


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.067796610169495


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.02173913043478


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.64383561643835


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.02173913043478


Đại Việt Sử Ký Toàn Thư
[155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.19565217391305


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.565217391304344


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.02173913043478


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.84384384384384


Đại Việt Sử Ký Toàn Thư
[155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.19565217391305


Đại Việt Sử Ký Toàn Thư
[155]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.108695652173914


Đại Việt Sử Ký Toàn Thư
[155, 156]
Bùi Mộng Hoa dâng thư, đại ý nói: "Thần nghe trẻ con có câu hát rằng: "Thâm hiểm thay Thái sư ho Lê [2]. Xem thế, Quý Ly nhất định có ý dòm ngó ngôi báu". Thượng hoàng xem tờ tâu rồi đưa cho Quý Ly.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  88%|████████▊ | 263/300 [08:29<01:24,  2.29s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.3041825095057


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.00638977635783


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.003412969283275


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.00638977635783


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.003412969283275


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.62500000000001


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 12, xuống chiếu rằng quân lính và dân thường hễ ai trốn việc lao dịch [cho nhà nướ] thì phải phạt 4 quan tiền... Quý Ly soạn sách Minh đạo gồm 14 thiên dâng lên.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.


Mapping source_excerpt to chunks:  88%|████████▊ | 264/300 [08:31<01:11,  1.99s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.047619047619044


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.666666666666664


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[154]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[155]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.238095238095234


Đại Việt Sử Ký Toàn Thư
[156]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 46.42857142857143


Đại Việt Sử Ký Toàn Thư
[156]
Quốc tử trợ giáo Đoàn Xuân Lôi dâng thư nói bàn thế là không phải, bị đày đi châu gần.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 46.42857142857143

Mapping source_excerpt to chunks:  88%|████████▊ | 265/300 [08:32<00:58,  1.66s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.625


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.39461883408071


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.377833753148614


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.311688311688314


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.96952908587258


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.74874371859297


Đại Việt Sử Ký Toàn Thư
[155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.19626168224299


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.39461883408071


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.377833753148614


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.339622641509436


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.311688311688314


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.96952908587258


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 49.74874371859297


Đại Việt Sử Ký Toàn Thư
[155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.53363228699552


Đại Việt Sử Ký Toàn Thư
[155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.94618834080718


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.39461883408071


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.377833753148614


Đại Việt Sử Ký Toàn Thư
[154]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 49.74874371859297


Đại Việt Sử Ký Toàn Thư
[155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.19277108433735


Đại Việt Sử Ký Toàn Thư
[155]
Quý Dậu, [Quang Thái] năm thứ 6 [ 1693], (Minh Hồng Vũ năm thứ 26). Mùa xuân, tháng giêng, lấy Hồ Cương coi quân Tả Thánh Dực (Cương người Diễn Châu). Quý Ly ngầm tìm được dòng dõi họ Hồ, muốn đổi theo họ cũ, đưa Cương ra làm người tâm phúc.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  89%|████████▊ | 266/300 [08:34<01:01,  1.82s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.79365079365079


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.464646464646464


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.79365079365079


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.464646464646464


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.20634920634921

Mapping source_excerpt to chunks:  89%|████████▉ | 267/300 [08:34<00:49,  1.50s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.79365079365079


Đại Việt Sử Ký Toàn Thư
[154]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[154, 155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[155]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 49.20634920634921


Đại Việt Sử Ký Toàn Thư
[155, 156]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[156]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Sử thần Ngô Sĩ Liên nói: Năm đầu niên hiệu Kiến Gia, giặc cướp đua nhau nổi dậy, Huệ Tông nhu nhược không đánh dẹp được. Trần Tự Khánh vì cớ Huệ hậu bị thái hậu làm khổ mà đem quân phạm cửa khuyết xin đón xa giá. Đương lúc bấy giờ, lòng người không thể không ngờ vực, cho nên Huệ Tông có lệnh bắt Tự Khánh mà không bắt được. Tự Khánh muốn làm cho kỳ được mới nhiều lần làm kinh động đến vua, xa giá phải dời chổ mấy lần, tội rõ ràng rồi. Nhưng mà Huệ Tông và Huệ hậu rốt cuộc phải nhờ Tự Khánh mới được yên, thì tội ấy không kể đến. Thế là việc tuy là trái nhưng tình thì thuận, sử chép không nêu lên nhưng thực cũng có nêu đấy. Nếu không thế thì chỉ là kẻ đầu sỏ giặc cướp mà thôi.

final_score: 47.61904761904761


Đại Việt Sử Ký Toàn Thư
[156]
Thượng hoàng giận, đem gả cho Hãng là em Nguyên Uyên để làm nhục.
Giáp Thân, [Kiến Gia] năm thứ 14 [1224], (Từ tháng 10 về sau là niên hiệu cuả Chiêu Hoàng Thiên Chương Hữu Đạo năm thứ 1; Tống Gia Định năm thứ 17). Bệnh của vua ngày càng tăng mà không có con trai để nối nghiệp lớn, các công chúa đều được chia các lộ làm ấp thang mộc, uỷ nhiệm cho một mình chỉ huy sứ Trần Thủ Độ quản lĩnh các quân điện tiền hộ vệ cấm đình.
Mùa đông, tháng 10, xuống chiếu lập công chúa Chiêu Thánh làm Hoàng thái tử để truyền ngôi cho. Vua xuất gia ở chùa Chân Giáo trong đại nội.
final_score: 46.03174603174603


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.77880184331797


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.622119815668206


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.23963133640553


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.46242774566474


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.70046082949308


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.32717678100264


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.77880184331797


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.97156398104265


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.622119815668206


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.23963133640553


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.46242774566474


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, Thượng hoàng sai thợ vẽ tranh Chu Công giúp Thàng Vương [3], Hoắc Quang giúp Chiếu Đế [4], Gia Cát giúp Thục Hậu chúa [5], Tô Hiến Thành giúp Lý Cao Tông [6], gọi là tranh "Tứ phụ"7, ban cho Quý Ly, để giúp quan gia [8] cũng nên như thế.

Mapping source_excerpt to chunks:  89%|████████▉ | 268/300 [08:37<00:53,  1.67s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.90657439446367


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.99453551912568


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.93063583815029


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.769230769230774


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.99453551912568


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.715846994535525


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.93063583815029


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.769230769230774


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.355191256830594


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.99453551912568


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.26229508196722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.90163934426229


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.540983606557376


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.448087431693985


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quý Ly giết người tôn thất là Phủ quân ty Nguyên Uyên và con thứ của Cung Chính Vương Sư Hiền là Nguyên Dận, vì hai người này trong khi để tang Nghệ Tông hay nói đến chuyện Nhật Chương [4].
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  90%|████████▉ | 269/300 [08:38<00:47,  1.54s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.6551724137931


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.85294117647059


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.38709677419355


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.85294117647059


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.38709677419355


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.32352941176471


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.85294117647059


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.79411764705882


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.58823529411765


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.32352941176471


Đại Việt Sử Ký Toàn Thư
[156]
Mùa hạ, tháng 4, bắt đầu phát [tiền giấy]. Thông bảo hội sao. In xong, ra lệnh cho người đến đổi, cứ 1 quan tiền đồng đổi lấy 1 quan 2 tiền giấy.

Mapping source_excerpt to chunks:  90%|█████████ | 270/300 [08:39<00:42,  1.41s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.8406374501992


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.65079365079365


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.40425531914893


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 39.70588235294118


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.40425531914893


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 39.70588235294118


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.17647058823529


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 41.91176470588235


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.38235294117647


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.64705882352941


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 44.85294117647059


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.11764705882353


Đại Việt Sử Ký Toàn Thư
[156]
Tháng 6, quy định kiểu mũ áo các quan văn võ... Những quy chế về tiền giấy, về mũ áo trên đây đều làm theo lời của thiếu bảo Vương Nhữ Chu cả.

Mapping source_excerpt to chunks:  90%|█████████ | 271/300 [08:40<00:38,  1.33s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.27129337539432


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 50.28571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.714285714285715


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.57142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 50.28571428571429


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.42857142857143


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 48.57142857142858


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.857142857142854


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.28571428571429


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.42857142857143


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 52.0


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa thu, tháng 8, sai tướng chỉ huy quân Long Tiệp là Trần Tùng đi đánh Chiêm Thành, bắt được tướng nước ấy là Bố Đông đem về, ban cho họ tên là Kim Trung Liệt, chỉ huy quân Hổ Bôn.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  91%|█████████ | 272/300 [08:42<00:40,  1.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.94871794871795


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.52252252252252


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.99363057324841


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.05555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.651006711409394


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.35680751173709


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.67025089605734


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.333333333333336


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.675159235668794


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.99363057324841


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.05555555555556


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 47.651006711409394


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.35680751173709


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.67025089605734


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.22292993630573


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.904458598726116


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.94904458598726


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 50.0


Đại Việt Sử Ký Toàn Thư
[154]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.651006711409394


Đại Việt Sử Ký Toàn Thư
[154, 155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.67025089605734


Đại Việt Sử Ký Toàn Thư
[155]
Đinh Sửu, [Quang Thái] nămthứ 10 [1397], (Minh Hồng Vũ năm thứ 30). Mùa xuân, tháng giêng, sai Lại bộ thượng thư kiêm Thái sư lệnh Đỗ Tỉnh (có sách chép là Mẫn) đi xem đất và đo đạc động An Tôn phủ Thanh Hóa, đắp thành đào hào, lập nhà tông miếu, dựng đàn xã tắc, mở đường phố, có ý muốn dời kinh đô đến đó, tháng 3 thì công việc hoàn tất.

Mapping source_excerpt to chunks:  91%|█████████ | 273/300 [08:45<00:57,  2.12s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.79620034542314


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.93193717277487


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.97520661157025


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.23374340949033


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.57425742574258


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.224422442244226


Đại Việt Sử Ký Toàn Thư
[155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.91187739463601


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.57425742574258


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.93193717277487


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.97520661157025


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.23374340949033


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.57425742574258


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.224422442244226


Đại Việt Sử Ký Toàn Thư
[155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.51145038167938


Đại Việt Sử Ký Toàn Thư
[155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.89438943894389


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.89438943894389


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.56435643564357


Đại Việt Sử Ký Toàn Thư
[154]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.57425742574258


Đại Việt Sử Ký Toàn Thư
[154, 155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.224422442244226


Đại Việt Sử Ký Toàn Thư
[155]
Lúc ấy, Khu mật chủ sự Nguyễn Nhữ Thuyết dâng thư can, đại ý nói: "Ngày xưa, nhà Chu, nhà Ngụy dời kinh đô đều gặp điều chẳng lành. Nay đất Long Đỗ [3] có núi Tản Viên, có sông Lô nhị [4], núi cao sông sâu, đất bằng phẳng rộng rãi... An Tôn đất đai chật hẹp, hẻo lánh, ở nơi đầu non cuối nước, hợp với loạn mà không hợp với trị."

Mapping source_excerpt to chunks:  91%|█████████▏| 274/300 [08:48<01:00,  2.33s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.894568690095845


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.40559440559441


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.05119453924915


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.81939799331104


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.48582995951418


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.846846846846844


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.15050167224081


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.05119453924915


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.81939799331104


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.48582995951418


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 47.166361974405845


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.49498327759198


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, đổi trấn Thanh Hóa thành trấn Thanh Đô; trấn Quốc Oai thành trấn Quảng Oai; trấn Đà Giang thành trấn Thiên Hưng; trấn Nghệ An thành trấn Lâm An; trấn Trườn Yên thành trấn Thiên Quan; trấn Lạng Giang thành trấn Lạng Sơn; trấn Diễn Châu thành trấn Vọng Giang; trấn Tân Bình thành trấn Tây Bình.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;

Mapping source_excerpt to chunks:  92%|█████████▏| 275/300 [08:51<01:00,  2.41s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.230769230769226


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.3926499032882


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.69747899159664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.61682242990654


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.006993006993014


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.07116104868914


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.60839160839161


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.69747899159664


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.61682242990654


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.006993006993014


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.7910447761194


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.45454545454546


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.8041958041958


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.307692307692314


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.75524475524476


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.006993006993014


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.35664335664335


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 6, xuống chiếu hạn chế danh điền [6]. Đại vương và trưởng công chúa thì số ruộng không hạn chế; đến thứ dân thì số ruộng là 10 mẫu. Người nào có nhiều nếu có tội, thì cho tùy ý được lấy ruộng để chuộc tội, bị biếm chức hay mất chức cũng được làm như vậy. Số ruộng thừa phải hiến cho nhà nước.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  92%|█████████▏| 276/300 [08:53<00:59,  2.46s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.6103896103896


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.0251572327044


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.540880503144656


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.693811074918564


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.76729559748428


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.90220820189275


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.65408805031446


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.0251572327044


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 46.540880503144656


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.693811074918564


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.76729559748428


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.90220820189275


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.65408805031446


Đại Việt Sử Ký Toàn Thư
[155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.0251572327044


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.540880503144656


Đại Việt Sử Ký Toàn Thư
[154]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.90220820189275


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.51827242524917


Đại Việt Sử Ký Toàn Thư
[155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.911949685534594


Đại Việt Sử Ký Toàn Thư
[155]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.540880503144656


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hữu thiêm tri chính sự hành Khu mật viện sự Phạm Cự Luận chỉ huy quân Thần Sách đánh bọn giặc cỏ áo đỏ ở trấn Tuyên Quang, thua trận bị chết, được tặng Tả bộc xạ
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.28301886792453



Mapping source_excerpt to chunks:  92%|█████████▏| 277/300 [08:55<00:48,  2.12s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.0958904109589


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 51.178451178451176


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 50.70422535211267


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.284345047923324


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 51.12359550561798


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 51.178451178451176


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 50.70422535211267


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.284345047923324


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 51.12359550561798


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 51.178451178451176


Đại Việt Sử Ký Toàn Thư
[154]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.70422535211267


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.284345047923324


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.366013071895416


Đại Việt Sử Ký Toàn Thư
[155]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 53.37078651685394


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mậu Dần, [Quang Thái] năm thứ 11 [1398], (từ tháng 3 trở đi là Thiếu Đế Kiến Tân năm thứ 1, Minh Hồng Vũ năm thứ 31). Mùa xuân, tháng 3, ngày 15, Lê Quý Ly bức vua phải nhường ngôi cho hoàng tử An
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.

Mapping source_excerpt to chunks:  93%|█████████▎| 278/300 [08:57<00:44,  2.02s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.34975369458128


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.56962025316456


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.895261845386536


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.38502673796791


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.34975369458128


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.56962025316456


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.895261845386536


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.320197044334975


Đại Việt Sử Ký Toàn Thư
[155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.827586206896555


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.33497536945813


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.320197044334975


Đại Việt Sử Ký Toàn Thư
[154]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.84236453201971


Đại Việt Sử Ký Toàn Thư
[155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.320197044334975


Đại Việt Sử Ký Toàn Thư
[155]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.78325123152709


Đại Việt Sử Ký Toàn Thư
[155, 156]
Ra lệnh cho những người có ruộng phải khai báo số mẫu ruộng. Hành khiển Hà Đức Lân nói kín với người nhà rằng: "Đặt ra phép này chỉ để cướp ruộng của dân thôi". Quý Ly nghe được, giáng Lân làm Hộ bộ thượng thư.

Mapping source_excerpt to chunks:  93%|█████████▎| 279/300 [08:59<00:46,  2.24s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.87499999999999


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.08510638297872


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.61702127659575


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.6


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.08510638297872


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.61702127659575


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.6


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.27659574468085


Đại Việt Sử Ký Toàn Thư
[155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.40425531914894


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[154]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.14893617021277


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.680851063829785


Đại Việt Sử Ký Toàn Thư
[155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.87234042553191


Đại Việt Sử Ký Toàn Thư
[155]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.74468085106383


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tướng Chiêm Thành là Chế Đa Biệt cùng với em là Mộ Hoa Từ Ca Diệp đem cả nhà sang hàng. Ban tên cho Đa Biệt là Đại Trung, phong là Kim Ngô vệ tướng quân, Ca Diệp làm Cấm vệ đô, đều ban họ Đinh
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  93%|█████████▎| 280/300 [09:01<00:38,  1.94s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.88679245283019


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.93305439330544


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.92307692307692


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.26415094339623


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.627376425855516


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.88679245283019


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.93305439330544


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.92307692307692


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.26415094339623


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.66197183098591


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.627376425855516


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.12244897959184


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.77358490566038


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.28301886792453


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.48897795591182


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Quý Ly cương bức vua phải xuất gia thờ Đạo giáo, ra ở quán Ngọc Thanh thôn Đạm Thủy [2], mật sai nội tẩm học sinh Nguyễn Cẩn đi theo để trông coi... Đến đây, sai Xa kỵ vệ thượng tướng quân Phạm Khả Vĩnh thắt cổ chết. Chôn ở lăng Yên Sinh, miếu hiệu là Thuận Tông.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.12244897959184


Đại Việt Sử Ký Toàn Thư
[155]

Mapping source_excerpt to chunks:  94%|█████████▎| 281/300 [09:03<00:40,  2.11s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.72890484739676


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.14417744916821


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45614035087719


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.57602862254025


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.971887550200805


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.14417744916821


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.45614035087719


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.25352112676056


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.263157894736835


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.45614035087719


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.46289752650176


Đại Việt Sử Ký Toàn Thư
[154, 155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[155]
Bọn Thái bảo Trần Hãng, Thượng tướng quân Trần Khát Chân mưu giết Quý Ly không thành, bị giết. Hôm ấy, Quý Ly họp thề ở Đốn Sơn [4]. Bọn Khát Chân đã có ý giết Quý Ly... Cháu Khả Vĩnh là Phạm Tổ Thu và thích khách là Phạm Ngưu Tất cầm gươm định lên, Khát Chân trừng mắt ngăn lại, nên việc không xong.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  94%|█████████▍| 282/300 [09:06<00:40,  2.26s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.75


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 40.67796610169492


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.7888198757764


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.924398625429546


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.546583850931675


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.85026737967914


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.214532871972324


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.950819672131146


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.7888198757764


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.924398625429546


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.546583850931675


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.85026737967914


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.73684210526315


Đại Việt Sử Ký Toàn Thư
[155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.2360248447205


Đại Việt Sử Ký Toàn Thư
[155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.77952755905512


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.950819672131146


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.09937888198758


Đại Việt Sử Ký Toàn Thư
[154]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.546583850931675


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.47826086956522


Đại Việt Sử Ký Toàn Thư
[155]
Sự việc bị phát giác, bọn tôn thất Hãng, Trụ quốc Nhật Đôn, tướng quân Trần Khát Chân, Phạm Khả Vĩnh, hành khiển Hà Đức Lân, Lương Nguyên Bửu, Phạm Ông Thiện, Phạm Ngưu Tất và các liêu thuộc, thân thích gồm hơn 370 người đều bị giết cả, tịch thu gia sản, con gái bắt làm nô tỳ, con trai từ 1 tuổi trở lên bị chôn sống, hoặc bị dìm nước.

Mapping source_excerpt to chunks:  94%|█████████▍| 283/300 [09:10<00:51,  3.02s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.80701754385965


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.36917562724014


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.397188049209134


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 40.917107583774246


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.80701754385965


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.50877192982456


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.36917562724014


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 46.397188049209134


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.845070422535215


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 42.10526315789473


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.80701754385965


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.85964912280702


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 46.31578947368421


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.21052631578948


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 8, tên cướp Nguyễn Nhữ Cái trốn vào núi Thiết Sơn làm giả tiền giấy tiêu dùng. Gặp lúc Thuận Tông bị giết, Khát Chân bị chém, mới chiêu dụ dân lành được hơn vạn người, hoạt động ở các xứ Lập Thạch, sông Đáy, Lịch Sơn [6], sông Đà, Tản Viên, cướp bóc bừa bãi, các châu huyện không sao chống được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  95%|█████████▍| 284/300 [09:14<00:49,  3.12s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.48936170212766


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.88311688311688


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.8051948051948


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.23711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.83116883116883


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 40.92664092664092


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.2077922077922


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.88311688311688


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.8051948051948


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.23711340206185


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.90243902439024


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.83116883116883


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.532467532467535


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.15584415584416


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.8051948051948


Đại Việt Sử Ký Toàn Thư
[154]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.83116883116883


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.83116883116883


Đại Việt Sử Ký Toàn Thư
[155]
Tháng 2, ngày 28, Quý Ly bức vua nhường ngôi và buộc người tôn thất và các quan ba lần dâng biểu khuyên lên ngôi. Quý Ly giả vờ cố tình từ chối nói: "Ta sắp xuống lỗ đến nơi rồi, còn mặt mũi nào trông thấy tiên đế ở dưới đất nữa?". Rồi tự lập làm vua, đặt niên hiệu là Thánh Nguyên, quốc hiệu là Đại Ngu [1], đổi thành họ Hồ.

Mapping source_excerpt to chunks:  95%|█████████▌| 285/300 [09:17<00:45,  3.03s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.48366013071896


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.443729903536976


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.94904458598726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.22292993630573


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.32081911262798


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.31210191082803


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.80936454849499


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.675159235668794


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.94904458598726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.94904458598726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.22292993630573


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.32081911262798


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.31210191082803


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.80936454849499


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.675159235668794


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.21768707482994


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.5859872611465


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.94904458598726


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.22292993630573


Đại Việt Sử Ký Toàn Thư
[154]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.31210191082803


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.31210191082803


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.5859872611465


Đại Việt Sử Ký Toàn Thư
[155]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.13375796178344


Đại Việt Sử Ký Toàn Thư
[155, 156]
Mùa thu, tháng 8, Quý Ly mở khoa thi thái học sinh. Lấy đỗ bọn Lưu Thúc Kiệm 20 người. Nguyễn Trãi, Lý Tử Tấn, Vũ Mộng Nguyên, Hoàng Hiến, Nguyễn Thành đều đỗ kỳ này.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.

Mapping source_excerpt to chunks:  95%|█████████▌| 286/300 [09:18<00:34,  2.48s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.849624060150376


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.86466165413534


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.33204633204633


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 46.616541353383454


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 45.86466165413534


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.33204633204633


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.609022556390975


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 46.616541353383454


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.86466165413534


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 47.36842105263158


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 48.1203007518797


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.616541353383454


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 46.616541353383454


Đại Việt Sử Ký Toàn Thư
[156]
Hán Thương đánh thuế các thuyền buôn, định 3 mức thượng, trung, hạ. Mức thượng đánh thuế mỗi thuyền 5 quan, mức trung 4 quan, mức hạ 3 quan.

Mapping source_excerpt to chunks:  96%|█████████▌| 287/300 [09:19<00:26,  2.08s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.72185430463576


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.02272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.663430420711975


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.455927051671736


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.13636363636363


Đại Việt Sử Ký Toàn Thư
[155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.31818181818182


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.02272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 54.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 55.663430420711975


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 50.455927051671736


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 51.13636363636363


Đại Việt Sử Ký Toàn Thư
[155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 52.27272727272727


Đại Việt Sử Ký Toàn Thư
[155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.72727272727273


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.02272727272727


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 54.666666666666664


Đại Việt Sử Ký Toàn Thư
[154]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 55.663430420711975


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 51.13636363636363


Đại Việt Sử Ký Toàn Thư
[155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 52.83018867924528


Đại Việt Sử Ký Toàn Thư
[155]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 51.70454545454546


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tân Tỵ, [1410], (Hồ Hán Thương Thiệu Thành năm thứ 1, Minh Kiến Văn năm thứ 3). Mùa xuân, tháng 2, sét đánh điếm canh trên thành. Hán Thương đổi lịch Hiệp kỷ của nhà Trần, dùng lịch Thuận Thiên.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  96%|█████████▌| 288/300 [09:20<00:22,  1.84s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.375


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.63265306122449


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.77777777777777


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.002277904328025


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.375586854460096


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.95798319327731


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.77777777777777


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08163265306122


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.002277904328025


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.375586854460096


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.95798319327731


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.93877551020408


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.89795918367348


Đại Việt Sử Ký Toàn Thư
[154]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[154, 155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.48979591836735


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.93877551020408


Đại Việt Sử Ký Toàn Thư
[155]
Mùa hạ, tháng 4, Hán Thương sai làm sổ hộ tịch trong cả nước, cho ghi họ Hồ có hai phái ở Diễn Châu và Thanh Hóa. Biên hết vào sổ những nhân khẩu từ 2 tuổi trở lên và lấy số hiện tại làm thực số, không cho phép người lưu vong mà vẫn biên tên trong sổ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.

Mapping source_excerpt to chunks:  96%|█████████▋| 289/300 [09:23<00:22,  2.05s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.50000000000001


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.509433962264154


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.20618556701031


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.5807560137457


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.93785310734464


Đại Việt Sử Ký Toàn Thư
[154, 155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.31627056672761


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.509433962264154


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.20618556701031


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.42424242424242


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 41.5807560137457


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.93785310734464


Đại Việt Sử Ký Toàn Thư
[154, 155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.26804123711341


Đại Việt Sử Ký Toàn Thư
[155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.04332129963899


Đại Việt Sử Ký Toàn Thư
[155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.5807560137457


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.6426116838488


Đại Việt Sử Ký Toàn Thư
[154, 155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 44.329896907216494


Đại Việt Sử Ký Toàn Thư
[155]
Các nô đều thích vào trán để đánh dấu: Quan nô thì thích hình viên ngọc hỏa châu, có khi lấy bổ sung vào quân điện tiền; của công chúa thì thích hình cây dương, cây đường; của đại vương thì thích 2 khuyên đỏ, của quan nhất phẩm thì thích 1 khuyên đen; của quan nhị phẩm trở xuống thích 2 khuyên đen.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.

Mapping source_excerpt to chunks:  97%|█████████▋| 290/300 [09:27<00:26,  2.63s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 39.37500000000001


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.43715846994536


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.690140845070424


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 39.89071038251366


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 40.98360655737705


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.117994100294986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.07650273224044


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 41.07142857142857


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.43715846994536


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 41.690140845070424


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 39.89071038251366


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 40.98360655737705


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 40.117994100294986


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.07650273224044


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 41.690140845070424


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.53005464480874


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 42.07650273224044


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 42.622950819672134


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 42.07650273224044


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hán Thương hạ lệnh cho các lộ nung gạch để dùng vào việc xây thành. Trước đây xây thành Tây Đô, tải nhiều đá tới xây, ít lâu sau lại bị sụp đổ, đến đây mới xây trên bằng gạch, dưới bằng đá.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks:  97%|█████████▋| 291/300 [09:28<00:20,  2.22s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.22988505747126


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.91187739463601


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.99616858237548


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.213114754098356


Đại Việt Sử Ký Toàn Thư
[155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 40.92664092664092


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 40.22988505747126


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 42.91187739463601


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.99616858237548


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.1924882629108


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 42.213114754098356


Đại Việt Sử Ký Toàn Thư
[155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.21072796934866


Đại Việt Sử Ký Toàn Thư
[155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.40044742729307


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.1455938697318


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.91187739463601


Đại Việt Sử Ký Toàn Thư
[154]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[154, 155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.29501915708812


Đại Việt Sử Ký Toàn Thư
[155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.21072796934866


Đại Việt Sử Ký Toàn Thư
[155]
Chúa Chiêm Ba Đích Lại sợ, sai cậu là Bố Điền dâng một voi trắng, một voi đen và các sản vật địa phương, lại dâng đất Chiêm Động để xin rút quân. Bố Điền tới, Quý Ly bắt ép phải sửa tờ biểu là dâng nộp cả động Cổ Lũy. Rồi chia đấy ấy thành bốn châu Thăng,Hoa, Tư, Nghĩa.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.

Mapping source_excerpt to chunks:  97%|█████████▋| 292/300 [09:30<00:18,  2.28s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 43.125


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.907407407407405


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.60633484162896


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.43891402714932


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.09090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.78846153846154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.518518518518526


Đại Việt Sử Ký Toàn Thư
[155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.89140271493213


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 48.86877828054299


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.60633484162896


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.43891402714932


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.37349397590361


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.09090909090909


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.78846153846154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.518518518518526


Đại Việt Sử Ký Toàn Thư
[155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.24886877828054


Đại Việt Sử Ký Toàn Thư
[155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 48.86877828054299


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.796380090497735


Đại Việt Sử Ký Toàn Thư
[154]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.09090909090909


Đại Việt Sử Ký Toàn Thư
[154, 155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.89140271493213


Đại Việt Sử Ký Toàn Thư
[155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.15384615384615


Đại Việt Sử Ký Toàn Thư
[155]
Sĩ nhân Nguyễn Bẩm dâng thư cho rằng Tiền Hồ nên nhường ngôi, lui về ở Kim Âu, Hậu Hồ, thì nên tôn là thượng hoàng , thái tử Nhuế lên ngôi Quan gia. Quý Ly giận lắm, cho là Bẩm chỉ trích nhà vua, sự tình nghiêm trọng, sai đem chém.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.

Mapping source_excerpt to chunks:  98%|█████████▊| 293/300 [09:33<00:15,  2.25s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.004184100418406


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.95774647887324


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.41637010676157


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.140845070422536


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.54929577464789


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.95774647887324


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.41637010676157


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 40.140845070422536


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.54929577464789


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.887323943661976


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.366197183098585


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.070422535211264


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 45.77464788732394


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 47.887323943661976


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 46.47887323943662


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.09090909090909


Đại Việt Sử Ký Toàn Thư
[156]
Hán Thương lấy phủ lộ Thanh Hóa làm đất Tam phụ của kinh kỳ; đổi phủ Thanh Hóa thành phủ Thiên Xương, gồm với Cửu Chân và Ái Châu gọi là Tam phụ.

Mapping source_excerpt to chunks:  98%|█████████▊| 294/300 [09:34<00:11,  1.90s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 41.25


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.39622641509434


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.75184275184275


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.672413793103445


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.80369515011547


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.53164556962026


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 42.75184275184275


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 42.672413793103445


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.80369515011547


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.53164556962026


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.258620689655174


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 45.258620689655174


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.689655172413794


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 44.80369515011547


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.103448275862064


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.258620689655174


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương sai giết người phương thuật là Trần Đức Huy... Việc bị phát giác, thu được một quyển sách phương thuật, một con dấu nguỵ, một thanh gươm nhỏ, mộc chiếc mõ đồng. Xử tội lăng trì, sổ quân thì ném xuống nước hoặc đốt đi không hỏi đến.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.

Mapping source_excerpt to chunks:  98%|█████████▊| 295/300 [09:36<00:10,  2.06s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.52554744525548


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.715328467153284


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.96124031007752


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.62151394422311


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.71544715447154


Đại Việt Sử Ký Toàn Thư
[155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 42.352941176470594


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 46.715328467153284


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.84615384615385


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.96124031007752


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.18181818181818


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 44.62151394422311


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 44.71544715447154


Đại Việt Sử Ký Toàn Thư
[155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.25547445255474


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.715328467153284


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[154]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 45.11278195488722


Đại Việt Sử Ký Toàn Thư
[154, 155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.79562043795621


Đại Việt Sử Ký Toàn Thư
[155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[155]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 45.98540145985402


Đại Việt Sử Ký Toàn Thư
[155, 156]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 45.25547445255474


Đại Việt Sử Ký Toàn Thư
[156]
Các quân vào đất Chiêm, làm nhiều chiến cụ; vây thành Chà Bản sắp lấy được, nhưng vì quân đi đã 9 tháng, hết lương ăn, không thắng phải rút về.

Mapping source_excerpt to chunks:  99%|█████████▊| 296/300 [09:38<00:07,  1.85s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 44.99999999999999


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.336569579288025


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.774574049803405


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.742729306487696


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.04332129963899


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.95302013422819


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.78846153846154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.22429906542056


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 44.982698961937714


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.40044742729307


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.774574049803405


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.742729306487696


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.04332129963899


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.95302013422819


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 42.78846153846154


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.22429906542056


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.29530201342282


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.85763490241102


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.51901565995525


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương định thể thức thi chọn nhân tài: Cứ tháng 8 năm nay thi hương, ai đỗ thì được miễn tuyển bổ [1]; lại tháng 8 năm sau thi hội, ai đỗ thì thi bổ thái học sinh. Rồi năm sau nữa thi lại bắt đàu thi hương như năm trước. Bấy giờ học trò chuyên nghiệp học hành, mong được bổ dụng, nhưng mới được thi ở bộ Lễ rồi gặp loạn phải thôi. Phép thi phỏng theo lối văn tự ba trường của nhà Nguyên [2] nhưng chia làm 4 kỳ, lại có kỳ thi viết chữ và thi toán, thành ra 5 kỳ.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.742729306487696


Đại Việt Sử Ký Toàn Thư

Mapping source_excerpt to chunks:  99%|█████████▉| 297/300 [09:45<00:10,  3.65s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 40.29304029304029


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.50561797752809


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.25842696629213


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.01123595505618


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 42.69662921348315


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 45.50561797752809


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.25842696629213


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.01123595505618


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.38202247191011


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.50561797752809


Đại Việt Sử Ký Toàn Thư
[154]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[154, 155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 46.62921348314607


Đại Việt Sử Ký Toàn Thư
[155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.82022471910112


Đại Việt Sử Ký Toàn Thư
[155]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.05882352941176


Đại Việt Sử Ký Toàn Thư
[155, 156]
Tùng cùng với người Chiêm đầu hàng là Chế Sơn Nô âm mưu làm phản, ngầm liên kết với người Chiêm Thành để trao đổi tin tức cho nhau. Việc bị tiết lộ, Tùng và con gái Quý đều bị xử tử.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.

Mapping source_excerpt to chunks:  99%|█████████▉| 298/300 [09:47<00:05,  2.93s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.07119741100323


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.47311827956989


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 45.16129032258065


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 42.47311827956989


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 45.16129032258065


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 44.623655913978496


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 44.08602150537635


Đại Việt Sử Ký Toàn Thư
[154]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.548387096774185


Đại Việt Sử Ký Toàn Thư
[154, 155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.01075268817204


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 46.7741935483871


Đại Việt Sử Ký Toàn Thư
[155]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 48.1994459833795


Đại Việt Sử Ký Toàn Thư
[155, 156]
Quý Ly sai hành khiển Hoàng Hối Khanh làm cát địa sứ. Hối Khanh đem các thôn như Cổ Lâu, gồm cả thảy 59 thôn trả cho nhà Minh. Quý Ly trách mắng, lăng nhục Hối Khanh vì trả lại đất nhiều quá.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.

Mapping source_excerpt to chunks: 100%|█████████▉| 299/300 [09:48<00:02,  2.47s/it]

Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.

final_score: 42.85714285714286


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.773279352226716


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.007194244604314


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.32374100719424


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.007194244604314


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi;
final_score: 43.939393939393945


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.

final_score: 47.773279352226716


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 41.007194244604314


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.32374100719424


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 41.007194244604314


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón.
final_score: 44.60431654676259


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
 Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
việc lớn của nước, quốc sử không thể không chép được. Có lẽ Lê Văn Hưu thấy đều gọi là Thọ lăng, cho là không đúng lễ nên bỏ đi, nhưng thế không phải là phép làm sử.
Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được.
Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu.
Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp buổi loạn lạc, giặc cướp tứ tung, mình bị bệnh nặng, không biết sớm cầu con nối, họ Lý bèn mất.

final_score: 46.76258992805755


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Tân Mùi, [Kiến Gia] năm thứ 1 [1211], (Tống Gia Định năm thứ 4). Mùa xuân, tháng giêng, đổi niên hiệu.
Tháng 2,, vua lại sai Phụng ngự là Phạm Bố đi đón Trần thị. Tự Khánh bèn sai bọn Phùng Tá Chu đưa Trần thị đi. Gặp khi Tô Trung Từ và Đỗ Quảng đang đánh nhau ở [bến] Triều Đông [2], Tá Chu bèn đỗ thuyền ở bến Đại Thông. Đến khi Đỗ Quang bị thua, vua sai Bố và Trung Từ đón Trần thị vào cung, lập làm nguyên phi cho Trung Từ làm Thái uý phụ chính; phong Thuận Lưu bá Trần Tự Khánh làm Chương Thành hầu [3].
Bấy giờ thừa hưởng thái bình đã lâu ngày, giường mối dần bỏ, dân không biết việc binh, giặc cướp nổi lên không ngăn cấm được. Vua mới lên ngôi, đem việc nước giao cho Thái uý Đàm Dĩ Mông. Dĩ Mông là người không có học thức, không có mưu thuật, lại nhu nhược không quyết đoán, chính sự ngày một đổ nát.

final_score: 45.32374100719424


Đại Việt Sử Ký Toàn Thư
[154]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
 Nhâm Thân, [Kiến Gia] năm thứ 2 [1212], (Tống Gia Định năm thứ 5).
Mùa xuân, tháng 2, sai người cùng một vú nuôi là Đoàn Thượng chiêu mộ dân châu Hồng đi bắt giặc cướp. Bấy giờ thế nước suy yếu, triều đình không có chính sách hay, đói kém luôn luôn, nhân dân cùng khốn, [Đoàn] Thượng thừa thế tự tiện làm oai làm phúc, không ai dám nói gì. Sau tội trạng tỏ rõ, bị các quan hặc, phải giam vào ngục để hỏi tội. Thượng mới rút gươm, cởi trần chạy về châu Hồng, nhóm họp bè đảng, đắp thành xưng vương, cướp bóc lương dân, triều đình không thể ngăn được.
Quý Dậu, [Kiến Gia] nămthứ 3 [1213], (Tống Gia Định năm thứ 5). Mùa xuân, tháng 2, Trần Tự Khánh đem quân xâm phạm cửa khuyết xin đón xa giá. Vua lấy làm ngờ, xuống chiếu lấy quân các đạo đi bắt Tự Khánh, giáng nguyên phi làm ngự nữ.

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[154, 155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Giáp Tuất, [Kiến Gia] năm thứ 4 [1214], (Tống Gia Định năm thứ 7). Mùa xuân, tháng giêng, Trần Tự Khánh đem quân đến [bến] Triều Đông, tự vào quân môn tạ tội, lại xin đón xa giá. Vuacàng ngờ, bèn cùng với thái hậu và ngự nữ chạy đến núi Trĩ Sơn ở châu Lạng. Tự Khánh nghe tin xa giá long đong mà ngự nữ thì lâu nay bị thái hậu làm khổ, lại đem quân đến xin đón xa giá như trước. Vua cũng chưa tin, lại cùng với thái hậu và ngự nữ chạy sang huyện Binh Hợp [1].
Mùa hạ, tháng 5, Tự Khánh đánh Đinh Khả và Bùi Đô ở châu Đại Hoàng, phá tan được.

final_score: 43.88489208633094


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Bính Tý, [Kiến Gia] năm thứ 6 [1216], (Tống gia Định năm thứ 9). Mùa xuân, sách phong ngự nữ làm Thuận Trinh phu nhân. Thái hậu cho Trần Tự Khánh là kẻ phản trắc, thường chỉ phu nhân mà nói là bè đảng của giặc, bảo vua đuổi bỏ đi; lại sai người nói với phu nhân bảo phải tự sát. Vua biết mới ngăn lại. Thái hậu bỏ thuốc độc vào món ăn uống của phu nhân. Mỗi bữa ăn vua chia cho phu nhân một nữa và không lúc nào cho rời bên cạnh. Thái hậu lại [29] sai người cầm chén thuốc độc bắt phu nhân phải chết. Vua lại ngăn không cho, rồi đêm ấy cùng với phu nhân lẻn đi đến chổ quân của Tự Khánh;
gặp khi trời đã sáng, phải nghĩ lại ở nhà tướng quân Lê Mịch ở huyện Yên Duyên, gặp tướng của Tự Khánh là Vương Lê đem binh thuyền đến đón. Vua mới đỗ lại ở bãi Cửu Liên [2]. Truyền cho Tự Khánh đến chầu.
Mùa hạ, tháng 6, hoàng trưởng nữ sinh ở bãi Cửu Liên, sau phong làm công chúa Thuận Thiên.
Mùa đông, tháng 12, sách phong [Thuận Trinh] phu nhân làm hoàng hậu, phong Tự Khánh làm Thái uý phụ chính, cho anh trai Tự Khánh là Trần Thừa (tức thượng hoàng nhà Trần) làm Nội thị phán thủ. Tự Khánh cùng với Thượng tướng quân Phan Lân xếp đặt quân ngũ, chế tạo binh khí, luyện tập võ nghệ, quân thế dần dần phấn chấn.

final_score: 44.60431654676259


Đại Việt Sử Ký Toàn Thư
[155]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Vua có bệnh trúng phong, chũa thuốc không khỏi mà chưa có thái tử, trong cung chỉ sinh công chúa mà thôi.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, châu bá là Lý Bất Nhiễm đánh phá được.
 Đinh Sửu, [Kiến Gia] năm thứ 7 [1217], (Tống Gia Định năm thứ 10). Mùa xuân, tháng 3, vua dần dần phát điên, có khi tự xưng là Thiên tướng giáng, tay cầm giáo và mộc, cắm cờ nhỏ vào búi tóc, đùa múa từ sớm đến chiều không nghỉ, khi thôi đùa nghịch thì đổ mồ hôi, nóng bức khát nước, uống rượu ngủ li bì đến hôm sau mới tỉnh. Chính sự không quyết đoán, giao phó cả cho Trần Tự Khánh. Quyền lớn trong nước dần dần về tay kẻ khác.
Mậu Dần, [Kiến Gia] năm thứ 8 [1218], (Tống Gia Định năm thứ 11). Mùa xuân, tháng 3, động đất.
Sao chổi mọc ở phương tây nam.
Mùa thu, tháng 8, xuống chiếu bằt cư sĩở chùa Phù Đổng là Nguyễn Nộn, vì bắt được vàng ngọc mà không đem dâng.
Tháng 9, hoàng thứ nữ sinh, sau phong làm công chúa Chiêu Thánh.
Mùa đông, tháng 10, Trần Tự Khánh đi đánh người Man ở Quảng Oai [3] không được.
Chiêm Thành và Chân Lạp đến cướp châu Nghệ An, Lý Bất Nhiễm đánh tan được, thăng tước hầu, ban thực ấp 7. [500] hộ, thực phong 1. [500] hộ.

final_score: 47.48201438848921


Đại Việt Sử Ký Toàn Thư
[155, 156]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.
Kỷ Mão, [Kiến Gia] năm thứ 9 [1219], (Tống Gia Định năm thứ 12). Mùa xuân, tháng 2, Trần Tự Khánh tâu xin tha cho Nguyễn Nộn, cho đi theo quân đánh giặc để chuộc tội. Vua y cho. Mùa đông, tháng 10, sai Nguyễn Nộn đem quân đi đánh người Man ở Quảng Oai.
Canh Thìn, [Kiến Gia] năm thứ 10 [1220], (Tống Gia Định năm thứ 13). Mùa xuân, tháng 3, Nguyễn Nộn giữ hương Phù đổng, tự xưng là Hoài Đạo Vương, dâng biểu xưng thần, xin đi dẹp loạn đểchuộc tội. Vua sai người đem sắc thư đến tuyên dụ. Song vì vua có bệnh phong, không thể chế ngự được.
Tân Tỵ, [Kiến Gia] năm thứ 11 [1221], (Tống Gia Định năm thứ 14). Mùa xuân, tháng giêng, tìm khắp thầy thuốc trong nước để chữa bệnh cho vua, nhưng không hiệu nghiệm gì. Vua thì ở tít trong cung, giặc cướp bừa bãi, nhân dân ở ngoài thành lưu ly cực khổ lắm.
 Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống Gia Định năm thứ 15). Mùa xuân, tháng 2, chia trong nước làm 24 lộ, lộ chia cho công chúa ở, lấy các hoành nô thuộc lệ và quân nhân bản lộ, chia nhau làm giáp.
Làm đồ binh khí và ghe thuyền để tuần bắt giặc cướp.
Quý Mùi, [Kiến Gia] năm thứ 13 [1223], (Tống Gia Định năm thứ 16). Mùa xuân, tháng 10, hạn, lúa bị sâu cắn.
Tháng 12, thế quân của Nguyễn Nộn ngày càng mạnh.
Trần Tự Khánh chết, truy phong làm Kiến Quốc Đại Vương; lấy Trần Thừa làm Phụ quốc Thái uý, khi vào chầu không xưng tên.

final_score: 44.60431654676259


Đại Việt Sử Ký Toàn Thư
[156]
Hán Thương ra lệnh cho các quan viên không được đi hia, chỉ cho đi giày tơ gai sống. Lệ cũ đời trước: quan từ lục phẩm trở lên mới được đi hia.

Mapping source_excerpt to chunks: 100%|██████████| 300/300 [09:49<00:00,  1.97s/it]

Total claims: 300
Usable for all chunk sizes: 297
Example:
{
  "claim_id": "claim_000001",
  "claim": "Lý Huệ Tông lên ngôi khi mới 16 tuổi và ở ngôi trong 14 năm.",
  "source_excerpt": "Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].",
  "source_pages": [
    154
  ],
  "book_name": "Đại Việt Sử Ký Toàn Thư",
  "source_window_id": "window_00001",
  "difficulty": "easy",
  "explanation": "Thông tin về tuổi lên ngôi và thời gian trị vì của vua Lý Huệ Tông được ghi chép trực tiếp trong đoạn trích.",
  "metadata": {
    "created_by": "gemini",
    "needs_human_review": true,
    "dataset_type": "multi_chunk_retrieval_benchmark"
  },
  "qrels": {
    "chunk_256": [
      {
        "chunk_id": "019e5654-af0f-703f-81e6-84b66b8ea660",
        "pages": [
          154
        ],
        "match_score": 83.2794,
        "fuzzy_score": 73.2794,
        "page_overlap": 1,
        "exact_match": false,
        "token_count": 149,
        "text_preview": "Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp..."
      },
      {
        "chunk_id": "019e5654-af08-7521-97fc-64c555797a10",
        "pages": [
          154
        ],
        "match_score": 83.031,
        "fuzzy_score": 73.031,
        "page_overlap": 1,
        "exact_match": false,
        "token_count": 92,
        "text_preview": "Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được. Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu."
      }
    ],
    "chunk_512": [
      {
        "chunk_id": "019e5677-399e-7e71-b07f-dbce7e195260",
        "pages": [
          154
        ],
        "match_score": 83.2794,
        "fuzzy_score": 73.2794,
        "page_overlap": 1,
        "exact_match": false,
        "token_count": 318,
        "text_preview": "Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp..."
      }
    ],
    "chunk_1024": [
      {
        "chunk_id": "019e5742-d5f1-77a4-be9b-af7fe96d1fcd",
        "pages": [
          154
        ],
        "match_score": 83.2794,
        "fuzzy_score": 73.2794,
        "page_overlap": 1,
        "

In [ ]:
def save_jsonl(rows: List[Dict[str, Any]], path: Path):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def save_json(rows: List[Dict[str, Any]], path: Path):
    with path.open("w", encoding="utf-8") as f:
        json.dump(rows, f, ensure_ascii=False, indent=2)


def flatten_for_csv(rows: List[Dict[str, Any]]) -> pd.DataFrame:
    flat_rows = []

    for row in rows:
        flat = {
            "claim_id": row["claim_id"],
            "claim": row["claim"],
            "source_excerpt": row["source_excerpt"],
            "source_pages": ",".join(map(str, row.get("source_pages", []))),
            "book_name": row["book_name"],
            "difficulty": row["difficulty"],
            "usable_all": row["is_usable_for_all_chunk_sizes"],
        }

        for key in ["chunk_256", "chunk_512", "chunk_1024"]:
            q = row["qrels"].get(key, [])
            flat[f"{key}_count"] = len(q)
            flat[f"{key}_top_chunk_id"] = q[0]["chunk_id"] if q else ""
            flat[f"{key}_top_score"] = q[0]["match_score"] if q else ""
            flat[f"{key}_exact_match"] = q[0]["exact_match"] if q else ""

        flat_rows.append(flat)

    return pd.DataFrame(flat_rows)


save_jsonl(final_dataset, OUTPUT_JSONL)
save_json(final_dataset, OUTPUT_JSON)

df = flatten_for_csv(final_dataset)
df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

print("Saved:")
print(OUTPUT_JSONL)
print(OUTPUT_JSON)
print(OUTPUT_CSV)

df.head()

Saved:
/content/dvsk_embedding_benchmark_qrels.jsonl
/content/dvsk_embedding_benchmark_qrels.json
/content/dvsk_embedding_benchmark_qrels.csv

,claim_id,claim,source_excerpt,source_pages,book_name,difficulty,usable_all,chunk_256_count,chunk_256_top_chunk_id,chunk_256_top_score,chunk_256_exact_match,chunk_512_count,chunk_512_top_chunk_id,chunk_512_top_score,chunk_512_exact_match,chunk_1024_count,chunk_1024_top_chunk_id,chunk_1024_top_score,chunk_1024_exact_match
0,claim_000001,Lý Huệ Tông lên ngôi khi mới 16 tuổi và ở ngôi...,Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấ...,154,Đại Việt Sử Ký Toàn Thư,easy,True,2,019e5654-af0f-703f-81e6-84b66b8ea660,83.2794,False,1,019e5677-399e-7e71-b07f-dbce7e195260,83.2794,False,1,019e5742-d5f1-77a4-be9b-af7fe96d1fcd,83.2794,False
1,claim_000002,Thái uý Đàm Dĩ Mông bị đánh giá là người thiếu...,"Vua mới lên ngôi, đem việc nước giao cho Thái ...",154,Đại Việt Sử Ký Toàn Thư,medium,True,1,019e5654-af27-77d3-bdbd-bd8dca5c217c,140.0,True,1,019e5677-39b5-7c9e-98a6-60e40145e716,140.0,True,1,019e5742-d797-7b17-8bd3-d453fa6754c7,140.0000,True
2,claim_000003,"Lý Huệ Tông từng mắc bệnh tâm thần, tự xưng là...","Mùa xuân, tháng 3, vua dần dần phát điên, có k...",155,Đại Việt Sử Ký Toàn Thư,medium,True,1,019e5654-af67-726a-9b8b-b67bdab20534,140.0,True,1,019e5677-39ef-71bd-b844-7b6bc7c45313,140.0,True,1,019e5742-d7ff-7f68-b7f1-5f08edd5a248,140.0000,True
3,claim_000004,Trần Tự Khánh được phong làm Thái uý phụ chính...,"Mùa đông, tháng 12, sách phong [Thuận Trinh] p...",155,Đại Việt Sử Ký Toàn Thư,hard,True,1,019e5654-af57-783b-bf58-276e60e0861c,140.0,True,1,019e5677-39e7-7a4c-a3d9-0aa5826dae69,140.0,True,1,019e5742-d7e1-7897-8606-6a6753225f14,140.0000,True
4,claim_000005,Vua Huệ Tông đã chia đất nước thành 24 lộ vào ...,"Nhâm Ngọ, [Kiến Gia] năm thứ 12 [1222], (Tống ...",156,Đại Việt Sử Ký Toàn Thư,easy,True,1,019e5654-af90-74df-ae40-0687e081efb3,140.0,True,1,019e5677-3a17-7981-b327-847c2551882f,140.0,True,1,019e5742-d820-7de6-9b32-023a21d6ae5c,140.0000,True

In [ ]:
USABLE_JSONL = Path("/content/dvsk_embedding_benchmark_qrels_usable_all.jsonl")
USABLE_JSON = Path("/content/dvsk_embedding_benchmark_qrels_usable_all.json")
USABLE_CSV = Path("/content/dvsk_embedding_benchmark_qrels_usable_all.csv")

save_jsonl(usable_all, USABLE_JSONL)
save_json(usable_all, USABLE_JSON)

usable_df = flatten_for_csv(usable_all)
usable_df.to_csv(USABLE_CSV, index=False, encoding="utf-8-sig")

print("Usable all:", len(usable_all))
print(USABLE_JSONL)
print(USABLE_JSON)
print(USABLE_CSV)

files.download(str(OUTPUT_JSONL))
files.download(str(OUTPUT_JSON))
files.download(str(OUTPUT_CSV))

files.download(str(USABLE_JSONL))
files.download(str(USABLE_JSON))
files.download(str(USABLE_CSV))

files.download(str(FAILED_JSON))

Usable all: 297
/content/dvsk_embedding_benchmark_qrels_usable_all.jsonl
/content/dvsk_embedding_benchmark_qrels_usable_all.json
/content/dvsk_embedding_benchmark_qrels_usable_all.csv

 ``` {
  "claim_id": "claim_000001",
  "claim": "Huệ Tông là con trưởng của Cao Tông.",
  "source_excerpt": "Huệ Tông Hoàng Đế tên huý là Sảm, con trưởng của Cao Tông...",
  "source_pages": [154],
  "book_name": "Đại Việt Sử Ký Toàn Thư",
  "difficulty": "easy",
  "qrels": {
    "chunk_256": [
      {
        "chunk_id": "019e...",
        "pages": [154],
        "match_score": 100.0,
        "exact_match": true
      }
    ],
    "chunk_512": [
      {
        "chunk_id": "019f...",
        "pages": [154],
        "match_score": 98.2,
        "exact_match": true
      }
    ],
    "chunk_1024": [
      {
        "chunk_id": "020a...",
        "pages": [154, 155],
        "match_score": 96.7,
        "exact_match": true
      }
    ]
  }
} ```

In [ ]:
# !pip install -q qdrant-client sentence-transformers pandas tqdm numpy underthesea

# đánh giá

In [ ]:
import os
import re
import json
import math
import gc
import numpy as np
import pandas as pd

from pathlib import Path
from typing import Any, Dict, List

from tqdm import tqdm
from qdrant_client import QdrantClient
from sentence_transformers import SentenceTransformer

from underthesea import word_tokenize
from google.colab import files


DATASET_PATH = Path("/content/dvsk_embedding_benchmark_qrels_usable_all.jsonl")

SUMMARY_CSV = Path("/content/embedding_eval_summary_multi_qrels.csv")
DETAIL_CSV = Path("/content/embedding_eval_details_multi_qrels.csv")


QDRANT_URL = userdata.get("QDRANT_URL")
QDRANT_API_KEY = userdata.get("QDRANT_API_KEY")

if not QDRANT_URL or not QDRANT_API_KEY:
    raise RuntimeError("Thiếu QDRANT_URL hoặc QDRANT_API_KEY trong biến môi trường Colab.")

qdrant = QdrantClient(
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY,
    timeout=60,
)

In [ ]:
MODEL_CONFIGS = [
    {
        "name": "bkai_256",
        "hf_model": "bkai-foundation-models/vietnamese-bi-encoder",
        "collection": "history_bkai_chunk_256",
        "chunk_key": "chunk_256",
        "needs_word_segmentation": True,
    },
    {
        "name": "dangvantuan_256",
        "hf_model": "dangvantuan/vietnamese-embedding",
        "collection": "history_dangvantuan_chunk_256",
        "chunk_key": "chunk_256",
        "needs_word_segmentation": True,
    },
    {
        "name": "halong_256",
        "hf_model": "hiieu/halong_embedding",
        "collection": "history_halong_chunk_256",
        "chunk_key": "chunk_256",
    },
    {
        "name": "bge_m3_256",
        "hf_model": "BAAI/bge-m3",
        "collection": "history_bge_m3_chunk_256",
        "chunk_key": "chunk_256",
    },
    {
        "name": "aiteamvn_256",
        "hf_model": "AITeamVN/Vietnamese_Embedding",
        "collection": "history_aiteamvn_chunk_256",
        "chunk_key": "chunk_256",
    },
    {
        "name": "halong_512",
        "hf_model": "hiieu/halong_embedding",
        "collection": "history_halong_chunk_512",
        "chunk_key": "chunk_512",
    },
    {
        "name": "bge_m3_512",
        "hf_model": "BAAI/bge-m3",
        "collection": "history_bge_m3_chunk_512",
        "chunk_key": "chunk_512",
    },
    {
        "name": "aiteamvn_512",
        "hf_model": "AITeamVN/Vietnamese_Embedding",
        "collection": "history_aiteamvn_chunk_512",
        "chunk_key": "chunk_512",
    },

    {
        "name": "bge_m3_1024",
        "hf_model": "BAAI/bge-m3",
        "collection": "history_bge_m3_chunk_1024",
        "chunk_key": "chunk_1024",
    },
    {
        "name": "aiteamvn_1024",
        "hf_model": "AITeamVN/Vietnamese_Embedding",
        "collection": "history_aiteamvn_chunk_1024",
        "chunk_key": "chunk_1024",
    },
]

In [ ]:
def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows = []

    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))

    return rows


dataset = load_jsonl(DATASET_PATH)

print("Total samples:", len(dataset))
print(json.dumps(dataset[0], ensure_ascii=False, indent=2)[:2500])

Total samples: 297
{
  "claim_id": "claim_000001",
  "claim": "Lý Huệ Tông lên ngôi khi mới 16 tuổi và ở ngôi trong 14 năm.",
  "source_excerpt": "Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự... Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226].",
  "source_pages": [
    154
  ],
  "book_name": "Đại Việt Sử Ký Toàn Thư",
  "source_window_id": "window_00001",
  "difficulty": "easy",
  "explanation": "Thông tin về tuổi lên ngôi và thời gian trị vì của vua Lý Huệ Tông được ghi chép trực tiếp trong đoạn trích.",
  "metadata": {
    "created_by": "gemini",
    "needs_human_review": true,
    "dataset_type": "multi_chunk_retrieval_benchmark"
  },
  "qrels": {
    "chunk_256": [
      {
        "chunk_id": "019e5654-af0f-703f-81e6-84b66b8ea660",
        "pages": [
          154
        ],
        "match_score": 83.2794,
        "fuzzy_score": 73.2794,
        "page_overlap": 1,
        "exact_match": false,
        "token_count": 149,
        "text_preview": "Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 năm Giáp Dần [1194], năm Mậu Thìn, Trị Bình Long Ứng thứ 4 [1208], tháng giêng, sách lập hoàng thái tử. Cao Tông băng, bèn lên ngôi báu, ở ngôi 14 năm [1211-1224], truyền ngôi cho Chiêu Hoàng, sau bị Trần Thủ Độ giết, thọ 33 tuổi [1194-1226]. Vua gặp..."
      },
      {
        "chunk_id": "019e5654-af08-7521-97fc-64c555797a10",
        "pages": [
          154
        ],
        "match_score": 83.031,
        "fuzzy_score": 73.031,
        "page_overlap": 1,
        "exact_match": false,
        "token_count": 92,
        "text_preview": "Hoàng thái tử Sảm lên ngôi ở trước linh cữu bấy giờ mới 16 tuổi. Tôn mẹ là Đàm thị là Hoàng thái hậu, cùng nghe chính sự. Lại đem thuyền rồng đi đón Trần thị. Anh Trần thị là Trần Tự Khánh cho rằng bấy giờ đương lúc loạn lạc, chưa đưa đi ngay được. Sai sứ cáo phó với nhà Tống, nhà Tống sai người sang làm lễ tế điếu."
      }
    ],
    "chunk_512": [
      {
        "chunk_id": "019e5677-399e-7e71-b07f-dbce7e195260",
        "pages": [
          154
        ],
        "match_score": 83.2794,
        "fuzzy_score": 73.2794,
        "page_overlap": 1,
        "exact_match": false,
        "token_count": 318,
        "text_preview": "Huệ Tông Hoàng Đế Tên huý là Sảm [1], con trưởng của Cao Tông, mẹ là hoàng hậu họ Đàm, sinh tháng 7 nă

In [ ]:
def get_positive_chunk_ids(sample: Dict[str, Any], chunk_key: str) -> List[str]:
    qrels = sample.get("qrels", {}).get(chunk_key, [])

    ids = []

    for item in qrels:
        cid = item.get("chunk_id")
        if cid:
            ids.append(str(cid))

    return list(dict.fromkeys(ids))


for key in ["chunk_256", "chunk_512", "chunk_1024"]:
    counts = [len(get_positive_chunk_ids(row, key)) for row in dataset]
    print(key)
    print("samples with qrels:", sum(c > 0 for c in counts))
    print("avg positive chunks:", sum(counts) / len(counts))

chunk_256
samples with qrels: 297
avg positive chunks: 1.063973063973064
chunk_512
samples with qrels: 297
avg positive chunks: 1.0606060606060606
chunk_1024
samples with qrels: 297
avg positive chunks: 1.0505050505050506

In [ ]:
def recall_at_k(retrieved_ids: List[str], positive_ids: List[str], k: int) -> float:
    top_k = retrieved_ids[:k]
    return 1.0 if any(pid in top_k for pid in positive_ids) else 0.0


def reciprocal_rank_at_k(retrieved_ids: List[str], positive_ids: List[str], k: int) -> float:
    for idx, rid in enumerate(retrieved_ids[:k], start=1):
        if rid in positive_ids:
            return 1.0 / idx
    return 0.0


def dcg_at_k(retrieved_ids: List[str], positive_ids: List[str], k: int) -> float:
    dcg = 0.0

    for idx, rid in enumerate(retrieved_ids[:k], start=1):
        rel = 1.0 if rid in positive_ids else 0.0
        if rel > 0:
            dcg += rel / math.log2(idx + 1)

    return dcg


def ndcg_at_k(retrieved_ids: List[str], positive_ids: List[str], k: int) -> float:
    dcg = dcg_at_k(retrieved_ids, positive_ids, k)

    ideal_hits = min(len(positive_ids), k)

    if ideal_hits == 0:
        return 0.0

    idcg = sum(
        1.0 / math.log2(i + 1)
        for i in range(1, ideal_hits + 1)
    )

    return dcg / idcg if idcg > 0 else 0.0

In [ ]:
def normalize_query(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def preprocess_query(text: str, config: Dict[str, Any]) -> str:
    text = normalize_query(text)

    if config.get("needs_word_segmentation", False):
        return word_tokenize(text, format="text")

    return text

In [ ]:
def search_qdrant(
    client: QdrantClient,
    collection_name: str,
    query_vector: List[float],
    limit: int = 10,
) -> List[Dict[str, Any]]:

    result = client.query_points(
        collection_name=collection_name,
        query=query_vector,
        limit=limit,
        with_payload=True,
        with_vectors=False,
    )

    rows = []

    for point in result.points:
        payload = point.payload or {}

        chunk_id = (
            payload.get("chunk_id")
            or payload.get("id")
            or str(point.id)
        )

        rows.append({
            "chunk_id": str(chunk_id),
            "score": float(point.score),
            "pages": payload.get("pages", []),
            "text_preview": str(payload.get("raw_text", ""))[:300],
        })

    return rows

In [ ]:
def encode_queries(
    model: SentenceTransformer,
    queries: List[str],
    batch_size: int = 16,
) -> np.ndarray:

    embeddings = model.encode(
        queries,
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )

    return embeddings

### đánh giá model

In [ ]:
def evaluate_one_model(
    config: Dict[str, Any],
    dataset: List[Dict[str, Any]],
    top_k: int = 10,
    batch_size: int = 16,
) -> Dict[str, Any]:

    model_name = config["name"]
    hf_model = config["hf_model"]
    collection = config["collection"]
    chunk_key = config["chunk_key"]
    trust_remote_code = bool(config.get("trust_remote_code", False))

    print("\n" + "=" * 80)
    print("Evaluating:", model_name)
    print("HF model:", hf_model)
    print("Collection:", collection)
    print("Qrels:", chunk_key)

    eval_rows = []

    usable_dataset = [
        row for row in dataset
        if len(get_positive_chunk_ids(row, chunk_key)) > 0
    ]

    print("Usable samples:", len(usable_dataset))

    model = SentenceTransformer(
        hf_model,
        trust_remote_code=trust_remote_code,
    )

    queries = [
        preprocess_query(row["claim"], config)
        for row in usable_dataset
    ]

    query_vectors = encode_queries(
        model=model,
        queries=queries,
        batch_size=batch_size,
    )

    for row, vector in tqdm(
        list(zip(usable_dataset, query_vectors)),
        desc=f"Searching {model_name}"
    ):
        positive_ids = get_positive_chunk_ids(row, chunk_key)

        try:
            search_results = search_qdrant(
                client=qdrant,
                collection_name=collection,
                query_vector=vector.tolist(),
                limit=top_k,
            )

            retrieved_ids = [x["chunk_id"] for x in search_results]

            eval_rows.append({
                "model_name": model_name,
                "collection": collection,
                "chunk_key": chunk_key,
                "claim_id": row["claim_id"],
                "claim": row["claim"],
                "difficulty": row.get("difficulty", "medium"),
                "positive_chunk_ids": positive_ids,
                "retrieved_ids": retrieved_ids,
                "top_scores": [x["score"] for x in search_results],
                "recall@1": recall_at_k(retrieved_ids, positive_ids, 1),
                "recall@3": recall_at_k(retrieved_ids, positive_ids, 3),
                "recall@5": recall_at_k(retrieved_ids, positive_ids, 5),
                "recall@10": recall_at_k(retrieved_ids, positive_ids, 10),
                "mrr@10": reciprocal_rank_at_k(retrieved_ids, positive_ids, 10),
                "ndcg@10": ndcg_at_k(retrieved_ids, positive_ids, 10),
                "error": "",
            })

        except Exception as e:
            eval_rows.append({
                "model_name": model_name,
                "collection": collection,
                "chunk_key": chunk_key,
                "claim_id": row["claim_id"],
                "claim": row["claim"],
                "difficulty": row.get("difficulty", "medium"),
                "positive_chunk_ids": positive_ids,
                "retrieved_ids": [],
                "top_scores": [],
                "recall@1": 0.0,
                "recall@3": 0.0,
                "recall@5": 0.0,
                "recall@10": 0.0,
                "mrr@10": 0.0,
                "ndcg@10": 0.0,
                "error": str(e),
            })

    details_df = pd.DataFrame(eval_rows)

    summary = {
        "model_name": model_name,
        "collection": collection,
        "chunk_key": chunk_key,
        "num_queries": len(details_df),
        "recall@1": details_df["recall@1"].mean(),
        "recall@3": details_df["recall@3"].mean(),
        "recall@5": details_df["recall@5"].mean(),
        "recall@10": details_df["recall@10"].mean(),
        "mrr@10": details_df["mrr@10"].mean(),
        "ndcg@10": details_df["ndcg@10"].mean(),
        "error_count": int((details_df["error"] != "").sum()),
    }

    del model
    gc.collect()

    return {
        "summary": summary,
        "details": details_df,
    }

### main

In [ ]:
all_summaries = []
all_details = []

for config in MODEL_CONFIGS:
    result = evaluate_one_model(
        config=config,
        dataset=dataset,
        top_k=10,
        batch_size=16,
    )

    all_summaries.append(result["summary"])
    all_details.append(result["details"])

    summary_df = pd.DataFrame(all_summaries)
    details_df = pd.concat(all_details, ignore_index=True)

    summary_df.to_csv(SUMMARY_CSV, index=False, encoding="utf-8-sig")
    details_df.to_csv(DETAIL_CSV, index=False, encoding="utf-8-sig")

    display(summary_df.sort_values(
        by=["recall@5", "mrr@10", "ndcg@10"],
        ascending=False
    ))

================================================================================
Evaluating: bkai_256
HF model: bkai-foundation-models/vietnamese-bi-encoder
Collection: history_bkai_chunk_256
Qrels: chunk_256
Usable samples: 297

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching bkai_256: 100%|██████████| 297/297 [00:34<00:00,  8.58it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0

================================================================================
Evaluating: dangvantuan_256
HF model: dangvantuan/vietnamese-embedding
Collection: history_dangvantuan_chunk_256
Qrels: chunk_256
Usable samples: 297

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching dangvantuan_256: 100%|██████████| 297/297 [00:34<00:00,  8.73it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: halong_256
HF model: hiieu/halong_embedding
Collection: history_halong_chunk_256
Qrels: chunk_256
Usable samples: 297

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching halong_256: 100%|██████████| 297/297 [00:34<00:00,  8.70it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: bge_m3_256
HF model: BAAI/bge-m3
Collection: history_bge_m3_chunk_256
Qrels: chunk_256
Usable samples: 297

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching bge_m3_256: 100%|██████████| 297/297 [00:34<00:00,  8.72it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: aiteamvn_256
HF model: AITeamVN/Vietnamese_Embedding
Collection: history_aiteamvn_chunk_256
Qrels: chunk_256
Usable samples: 297

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching aiteamvn_256: 100%|██████████| 297/297 [00:34<00:00,  8.69it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: halong_512
HF model: hiieu/halong_embedding
Collection: history_halong_chunk_512
Qrels: chunk_512
Usable samples: 297

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching halong_512: 100%|██████████| 297/297 [00:34<00:00,  8.67it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: bge_m3_512
HF model: BAAI/bge-m3
Collection: history_bge_m3_chunk_512
Qrels: chunk_512
Usable samples: 297

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching bge_m3_512: 100%|██████████| 297/297 [00:34<00:00,  8.56it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,297,0.363636,0.636364,0.744108,0.814815,0.516842,0.585759,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: aiteamvn_512
HF model: AITeamVN/Vietnamese_Embedding
Collection: history_aiteamvn_chunk_512
Qrels: chunk_512
Usable samples: 297

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching aiteamvn_512: 100%|██████████| 297/297 [00:35<00:00,  8.42it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,297,0.363636,0.636364,0.744108,0.814815,0.516842,0.585759,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,297,0.363636,0.619529,0.740741,0.831650,0.516183,0.588990,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: bge_m3_1024
HF model: BAAI/bge-m3
Collection: history_bge_m3_chunk_1024
Qrels: chunk_1024
Usable samples: 297

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching bge_m3_1024: 100%|██████████| 297/297 [00:34<00:00,  8.57it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,297,0.363636,0.636364,0.744108,0.814815,0.516842,0.585759,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,297,0.363636,0.619529,0.740741,0.831650,0.516183,0.588990,0
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,297,0.346801,0.602694,0.693603,0.791246,0.497970,0.565317,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
Evaluating: aiteamvn_1024
HF model: AITeamVN/Vietnamese_Embedding
Collection: history_aiteamvn_chunk_1024
Qrels: chunk_1024
Usable samples: 297

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Searching aiteamvn_1024: 100%|██████████| 297/297 [00:34<00:00,  8.61it/s]

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,297,0.363636,0.636364,0.744108,0.814815,0.516842,0.585759,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,297,0.363636,0.619529,0.740741,0.831650,0.516183,0.588990,0
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,297,0.346801,0.602694,0.693603,0.791246,0.497970,0.565317,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0
9,aiteamvn_1024,history_aiteamvn_chunk_1024,chunk_1024,297,0.336700,0.569024,0.653199,0.764310,0.473830,0.542257,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

In [ ]:
summary_df = pd.DataFrame(all_summaries)

summary_df = summary_df.sort_values(
    by=["chunk_key", "recall@5", "mrr@10", "ndcg@10"],
    ascending=[True, False, False, False]
)

summary_df.to_csv(SUMMARY_CSV, index=False, encoding="utf-8-sig")

summary_df

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,297,0.346801,0.602694,0.693603,0.791246,0.497970,0.565317,0
9,aiteamvn_1024,history_aiteamvn_chunk_1024,chunk_1024,297,0.336700,0.569024,0.653199,0.764310,0.473830,0.542257,0
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,297,0.363636,0.636364,0.744108,0.814815,0.516842,0.585759,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,297,0.363636,0.619529,0.740741,0.831650,0.516183,0.588990,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0

# idk

In [ ]:
# @title
for chunk_key in ["chunk_256", "chunk_512", "chunk_1024"]:
    print("\n" + "=" * 80)
    print(chunk_key)

    display(
        summary_df[summary_df["chunk_key"] == chunk_key]
        .sort_values(
            by=["recall@5", "mrr@10", "ndcg@10"],
            ascending=False
        )
    )

================================================================================
chunk_256

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,297,0.356902,0.643098,0.764310,0.851852,0.522682,0.596870,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,297,0.367003,0.649832,0.757576,0.868687,0.529843,0.603282,0
2,halong_256,history_halong_chunk_256,chunk_256,297,0.323232,0.552189,0.636364,0.764310,0.462133,0.529423,0
0,bkai_256,history_bkai_chunk_256,chunk_256,297,0.255892,0.478114,0.535354,0.636364,0.381665,0.440378,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,297,0.245791,0.434343,0.508418,0.609428,0.355821,0.411251,0

================================================================================
chunk_512

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,297,0.363636,0.636364,0.744108,0.814815,0.516842,0.585759,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,297,0.363636,0.619529,0.740741,0.831650,0.516183,0.588990,0
5,halong_512,history_halong_chunk_512,chunk_512,297,0.319865,0.538721,0.656566,0.740741,0.447997,0.515263,0

================================================================================
chunk_1024

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,297,0.346801,0.602694,0.693603,0.791246,0.49797,0.565317,0
9,aiteamvn_1024,history_aiteamvn_chunk_1024,chunk_1024,297,0.336700,0.569024,0.653199,0.764310,0.47383,0.542257,0

In [ ]:
# @title
for chunk_key in ["chunk_256", "chunk_512", "chunk_1024"]:
    print("\n" + "=" * 80)
    print(chunk_key)

    display(
        summary_df[summary_df["chunk_key"] == chunk_key]
        .sort_values(
            by=["recall@5", "mrr@10", "ndcg@10"],
            ascending=False
        )
    )

================================================================================
chunk_256

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,198,0.313131,0.676768,0.777778,0.888889,0.508882,0.591908,0
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,198,0.313131,0.651515,0.772727,0.868687,0.503245,0.585383,0
2,halong_256,history_halong_chunk_256,chunk_256,198,0.313131,0.590909,0.661616,0.762626,0.462039,0.528407,0
0,bkai_256,history_bkai_chunk_256,chunk_256,198,0.247475,0.525253,0.575758,0.661616,0.393879,0.458133,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,198,0.186869,0.308081,0.388889,0.494949,0.271178,0.319218,0

================================================================================
chunk_512

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,198,0.343434,0.601010,0.747475,0.853535,0.506035,0.584962,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,198,0.373737,0.616162,0.722222,0.838384,0.520717,0.592898,0
5,halong_512,history_halong_chunk_512,chunk_512,198,0.328283,0.540404,0.676768,0.757576,0.461253,0.527468,0

================================================================================
chunk_1024

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,198,0.343434,0.616162,0.717172,0.80303,0.503547,0.571963,0
9,aiteamvn_1024,history_aiteamvn_chunk_1024,chunk_1024,198,0.383838,0.606061,0.691919,0.80303,0.517126,0.581624,0

In [ ]:
# @title
for chunk_key in ["chunk_256", "chunk_512", "chunk_1024"]:
    print("\n" + "=" * 80)
    print(chunk_key)

    display(
        summary_df[summary_df["chunk_key"] == chunk_key]
        .sort_values(
            by=["recall@5", "mrr@10", "ndcg@10"],
            ascending=False
        )
    )

================================================================================
chunk_256

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,100,0.26,0.59,0.70,0.82,0.445762,0.520886,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,100,0.22,0.56,0.68,0.80,0.410996,0.486695,0
2,halong_256,history_halong_chunk_256,chunk_256,100,0.23,0.47,0.56,0.66,0.367381,0.423954,0
0,bkai_256,history_bkai_chunk_256,chunk_256,100,0.18,0.41,0.47,0.55,0.304135,0.357596,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,100,0.16,0.40,0.45,0.55,0.281163,0.334261,0

================================================================================
chunk_512

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,100,0.25,0.55,0.68,0.79,0.425992,0.504167,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,100,0.27,0.53,0.68,0.72,0.418111,0.479437,0
5,halong_512,history_halong_chunk_512,chunk_512,100,0.25,0.45,0.57,0.66,0.372440,0.431719,0

================================================================================
chunk_1024

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,100,0.21,0.47,0.61,0.72,0.374591,0.448236,0
9,aiteamvn_1024,history_aiteamvn_chunk_1024,chunk_1024,100,0.27,0.50,0.60,0.71,0.413020,0.477859,0

In [ ]:
# @title
for chunk_key in ["chunk_256", "chunk_512", "chunk_1024"]:
    print("\n" + "=" * 80)
    print(chunk_key)

    display(
        summary_df[summary_df["chunk_key"] == chunk_key]
        .sort_values(
            by=["recall@5", "mrr@10", "ndcg@10"],
            ascending=False
        )
    )

================================================================================
chunk_256

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
3,bge_m3_256,history_bge_m3_chunk_256,chunk_256,299,0.331104,0.662207,0.769231,0.859532,0.511941,0.590574,0
4,aiteamvn_256,history_aiteamvn_chunk_256,chunk_256,299,0.384615,0.665552,0.755853,0.856187,0.541545,0.609794,0
2,halong_256,history_halong_chunk_256,chunk_256,299,0.344482,0.581940,0.658863,0.765886,0.476411,0.541238,0
0,bkai_256,history_bkai_chunk_256,chunk_256,299,0.260870,0.501672,0.561873,0.652174,0.391744,0.452157,0
1,dangvantuan_256,history_dangvantuan_chunk_256,chunk_256,299,0.230769,0.418060,0.498328,0.588629,0.342147,0.397334,0

================================================================================
chunk_512

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
6,bge_m3_512,history_bge_m3_chunk_512,chunk_512,299,0.394649,0.642140,0.765886,0.849498,0.544377,0.614115,0
7,aiteamvn_512,history_aiteamvn_chunk_512,chunk_512,299,0.377926,0.635452,0.752508,0.856187,0.530522,0.605423,0
5,halong_512,history_halong_chunk_512,chunk_512,299,0.331104,0.561873,0.658863,0.745819,0.463081,0.528853,0

================================================================================
chunk_1024

,model_name,collection,chunk_key,num_queries,recall@1,recall@3,recall@5,recall@10,mrr@10,ndcg@10,error_count
8,bge_m3_1024,history_bge_m3_chunk_1024,chunk_1024,299,0.351171,0.615385,0.698997,0.812709,0.505414,0.577041,0
9,aiteamvn_1024,history_aiteamvn_chunk_1024,chunk_1024,299,0.361204,0.581940,0.655518,0.782609,0.490858,0.558963,0

In [ ]:
files.download(str(SUMMARY_CSV))
files.download(str(DETAIL_CSV))